back/src/adapters/secondary/InMemoryFeatureFlagRepository.ts
back/src/adapters/secondary/pg/PgFeatureFlagRepository.integration.test.ts
back/src/adapters/secondary/pg/migrations/1683709661344_add-maintenance-feature-flags.ts
front/src/app/App.tsx
front/src/app/contents/commonContent.ts
front/src/app/pages/admin/TechnicalOptions.tsx
front/src/core-logic/domain/featureFlags/featureFlags.slice.ts
front/src/core-logic/domain/featureFlags/featureFlags.test.ts
front/src/core-logic/domain/testHelpers/test.helpers.ts
libs/react-design-system/src/immersionFacile/components/index.ts
libs/react-design-system/src/immersionFacile/components/maintenance-callout/MaintenanceCallout.scss
libs/react-design-system/src/immersionFacile/components/maintenance-callout/MaintenanceCallout.styles.ts
libs/react-design-system/src/immersionFacile/components/maintenance-callout/MaintenanceCallout.tsx
libs/react-design-system/src/immersionFacile/components/maintenance-callout/index.ts
shared/src/featureFlags.ts

Feature / Maintenance mode feature flag

---

front/src/app/components/search/ContactModalContent.tsx
front/src/app/components/search/SearchResult.tsx

add link to partner website in search results

---

back/src/adapters/primary/scripts/seed.ts
front/src/app/components/SiretFetcherInput.tsx
front/src/app/components/SiretModalContent.tsx
front/src/core-logic/adapters/SiretGatewayThroughBack/HttpSiretGatewayThroughBack.ts

- update seed script
- handle siret error correctly

fix modification detablissement existant

---

front/src/app/components/forms/commons/SchedulePicker/SchedulePicker.tsx
front/src/app/components/forms/convention/ConventionForm.tsx
front/src/app/components/forms/convention/ConventionFormFields.tsx
front/src/app/components/forms/convention/ConventionSummary.tsx
front/src/app/components/forms/convention/conventionHelpers.ts
front/src/app/components/forms/convention/sections/hour-location/ImmersionHourLocationSection.tsx
front/src/app/contents/forms/convention/formConvention.tsx
front/src/app/contents/forms/convention/textSetup.tsx
front/src/app/pages/convention/ConventionDocumentPage.tsx
front/src/app/pages/convention/ConventionImmersionPage.tsx
front/src/core-logic/domain/convention/convention.slice.ts
shared/src/schedule/ScheduleUtils.ts

Feedback convention form multi steps

---

front/src/app/components/forms/convention/ConventionForm.tsx
front/src/app/pages/convention/ConventionPageForExternals.tsx

Documentation des query params de convention disponible ici :
https://pad.incubateur.net/BYrTd10MQf-JEop7KGo45w?view

add milo-paris as Convention external consumer

---

back/src/adapters/secondary/pg/PgEstablishmentAggregateRepository.getSiretOfEstablishmentsToSuggestUpdate.integration.test.ts
back/src/adapters/secondary/pg/PgNotificationRepository.integration.test.ts
back/src/domain/immersionOffer/useCases/RequestEditFormEstablishment.ts
back/src/domain/immersionOffer/useCases/RequestEditFormEstablishment.unit.test.ts
back/src/domain/immersionOffer/useCases/SuggestEditEstablishment.ts
back/src/domain/immersionOffer/useCases/SuggestEditEstablishment.unit.test.ts
back/src/domain/immersionOffer/useCases/notifications/NotifyConfirmationEstablishmentCreated.ts
back/src/domain/immersionOffer/useCases/notifications/NotifyConfirmationEstablishmentCreated.unit.test.ts
back/src/domain/immersionOffer/useCases/notifications/NotifyContactRequest.ts
back/src/domain/immersionOffer/useCases/notifications/NotifyContactRequest.unit.test.ts
front/src/app/pages/admin/EmailPreviewTab.tsx
front/src/core-logic/domain/admin/notifications/notifications.test.ts
shared/src/email/EmailParamsByEmailType.ts
shared/src/email/emailTemplatesByName.ts

Liste des templates modifiés :  
NEW_ESTABLISHMENT_CREATED_CONTACT_CONFIRMATION,
EDIT_FORM_ESTABLISHMENT_LINK,
SUGGEST_EDIT_FORM_ESTABLISHMENT,
CONTACT_BY_EMAIL_REQUEST

add business address and business name to severals emails template

---

front/src/app/components/forms/convention/ConventionForm.tsx
front/src/core-logic/domain/convention/convention.slice.ts
front/src/core-logic/domain/convention/convention.test.ts

- added clearFetchedConvention on ConventionForm cleanup function
- fixed cleanup function on ConventionForm + reinit conventionSlice formUi values on clearFetchedConvention

337 fix convention duplicate id

---

front/src/app/components/forms/convention/ConventionSignForm.tsx
front/src/app/components/forms/convention/SignatureActions.tsx
front/src/app/contents/forms/convention/textSetup.tsx
front/src/app/pages/convention/ConventionSignPage.tsx

- refacto ConventionSignPage using ts-pattern, fixed display of convention ready to sign message
- fix pattern matching to avoid TS Type instantiation is excessively deep and possibly infinite error

336 fix message votre convention est prête à être signée sur le form de signature de convention

---

.github/workflows/cypress-run.yml

- edited GH actions to run Cypress locally - logs in the GH action
- fixed apos on curl command

use local cypress in ci

---

back/src/_testBuilders/emailAssertions.ts
back/src/adapters/primary/routers/convention/addConventionAndSendMails.e2e.test.ts
back/src/adapters/primary/routers/convention/signeeRejectsImmersionApplication.e2e.test.ts
back/src/adapters/primary/scripts/seed.ts
back/src/adapters/secondary/notificationGateway/BrevoNotificationGateway.manual.test.ts
back/src/domain/convention/useCases/notifications/NotifySignatoriesThatConventionSubmittedNeedsSignature.ts
cypress/cypress/support/conventionForm/commands.ts
cypress/e2e/conventionWorkflow.spec.cy.ts
cypress/package.json
front/src/app/pages/admin/EmailPreviewTab.tsx
front/src/app/pages/admin/NotificationsTab.tsx
shared/src/convention/convention.targets.ts
shared/src/email/EmailParamsByEmailType.ts
shared/src/email/emailTemplatesByName.ts
shared/src/index.ts
shared/src/seedSharedData.ts

- share seed agency id with cypress
- ajust cypress convention workflow tests

use targets for conventions

---

front/src/app/components/admin/ConventionManageContent.tsx
front/src/app/components/forms/convention/ConventionForm.tsx
front/src/app/components/forms/convention/ConventionFormFields.tsx
front/src/app/components/forms/convention/useUpdateConventionValuesInUrl.ts
front/src/app/pages/convention/ConventionCustomAgencyPage.tsx
front/src/app/pages/convention/ConventionImmersionPage.tsx
front/src/app/pages/convention/ConventionMiniStagePage.tsx
front/src/app/pages/convention/ConventionPageForExternals.tsx
front/src/app/routes/Router.tsx

Contient aussi le fix du bug remonté par @nathalie-reyre (https://staging.immersion-facile.beta.gouv.fr/pilotage-convention?jwt=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJhcHBsaWNhdGlvbklkIjoiYjZiOGE5MGUtNjQ2Zi00ZTQxLWI4MTAtYjQ2N2MwNzg3ZGZhIiwicm9sZSI6InZhbGlkYXRvciIsImlhdCI6MTY4ODQ3NzA1MCwiZXhwIjoxNjkxMTU1NDUwLCJlbWFpbEhhc2giOiJlYmEwNTJiYjk0YzA4MmYwNjQ0MDA1NzEzZjMxYWNiMSJ9.40hPhC_njc5ZqvPh223v07PuvWsQ-2DcaneA6YQHOtpoZDChhxauK46odur2wtQGVofdi0kKaOD39ROYqDaJeA)

Reorganize convention form

---

back/src/adapters/primary/routers/createEstablishment/contactEstablishment.e2e.test.ts
back/src/adapters/primary/routers/emailValidation/createValidateEmailRouter.ts
back/src/adapters/primary/server.ts
back/src/domain/immersionOffer/useCases/ContactEstablishment.ts
back/src/domain/immersionOffer/useCases/ContactEstablishment.unit.test.ts
back/src/domain/immersionOffer/useCases/notifications/NotifyContactRequest.ts
back/src/domain/immersionOffer/useCases/notifications/NotifyContactRequest.unit.test.ts
front/src/app/components/search/ContactByEmail.tsx
shared/src/contactEstablishmentRequest/contactEstablishmentRequest.dto.ts
shared/src/contactEstablishmentRequest/contactEstablishmentRequest.schema.ts

- move validateEmailsRouter so that it does not go throw apiKeyAuth middleware
- move validation logic for contact request in ContactEstablishment usecase
- change ContactEstablishmentEventPayload to minimum : discussionId and message

389 bug sur les mises en contact sans offre

---

front/src/app/components/establishments/AddEstablishmentsByBatch.tsx
front/src/app/contents/meta/metaContents.ts
front/src/app/pages/admin/AdminPage.tsx
front/src/app/pages/admin/EstablishmentsTab.tsx
front/src/app/routes/routeParams/adminTabs.ts

reorganize Admin Headers

---

back/package.json
back/src/adapters/primary/helpers/sendHttpResponse.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/contactEstablishmentPublicV2.e2e.test.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/createOpenApiV2.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/publicApiV2.routes.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/searchImmersionApiPublicV2.e2e.test.ts
back/src/adapters/primary/routers/createEstablishment/contactEstablishment.e2e.test.ts
back/src/adapters/primary/routers/searchImmersion/createSearchImmersionRouter.ts
back/src/adapters/primary/routers/searchImmersion/searchImmersion.e2e.test.ts
back/src/domain/immersionOffer/useCases/ConvertSearchimmersionQueryParamsToSearchImmerssionParamsDto.ts
doc/api/search/contactEstablishmentV2.md
front/package.json
front/src/app/components/search/ContactByEmail.tsx
front/src/config/createHttpDependencies.ts
front/src/core-logic/adapters/ImmersionSearchGateway/HttpImmersionSearchGateway.ts
libs/react-design-system/src/immersionFacile/storyPrefixes.ts
pnpm-lock.yaml
shared/package.json
shared/src/index.ts
shared/src/searchImmersion/searchImmersion.routes.ts

- adapt search and contact routes with shared-routes contrats
- fix typo
- fix e2e test with error handling difference (shared-routes)

fix contact establishment with shared routes

---

shared/src/convention/ConventionDto.unit.test.ts
shared/src/convention/convention.dto.ts

Il n'y a plus d'âge minimum pour demander un mini-stage.  
Nous avons tout de même voulu garder pour le moment un âge minimum de 10 ans.

modifier l'âge minimum pour demande mini stage cci 14ans -> 10ans

---

back/src/adapters/primary/scripts/seed.ts
back/src/adapters/secondary/InMemoryFeatureFlagRepository.ts
back/src/adapters/secondary/pg/PgFeatureFlagRepository.integration.test.ts
back/src/adapters/secondary/pg/PgFeatureFlagRepository.ts
back/src/domain/convention/useCases/ResyncOldConventionsToPe.unit.test.ts
back/src/domain/core/ports/FeatureFlagRepository.ts
back/src/domain/generic/featureFlag/SetFeatureFlag.ts
front/src/app/components/agency/RegisterUsersToAgencies.tsx

- add email in users listing in admin : affect user to agency
- fix feature flags insersion in seed
- add list of emails in subscribe user to agency cards and fix feature flags seed
New look when checking user to agency :

improve UI to affect user to agency

---

back/src/_testBuilders/EstablishmentEntityBuilder.ts
back/src/adapters/secondary/immersionOffer/InMemoryEstablishmentAggregateRepository.ts
back/src/adapters/secondary/pg/PgEstablishmentAggregateRepository.integration.test.ts
back/src/adapters/secondary/pg/PgEstablishmentAggregateRepository.test.helpers.ts
back/src/adapters/secondary/pg/PgEstablishmentAggregateRepository.ts
back/src/adapters/secondary/pg/PgEstablishmentGroupRepository.ts
back/src/adapters/secondary/pg/migrations/1690365887734_replace-is-active-column-by-is-open-in-establishment-table.ts
back/src/domain/immersionOffer/entities/EstablishmentEntity.ts
back/src/domain/immersionOffer/ports/EstablishmentAggregateRepository.ts
back/src/domain/immersionOffer/useCases/InsertEstablishmentAggregateFromFormEstablishement.unit.test.ts
back/src/domain/immersionOffer/useCases/UpdateEstablishmentAggregateFromFormEstablishement.unit.test.ts
back/src/domain/immersionOffer/useCases/UpdateEstablishmentsFromSirenApiScript.ts
back/src/domain/immersionOffer/useCases/UpdateEstablishmentsFromSireneApiScript.unit.test.ts
back/src/utils/makeFormEstablishmentToEstablishmentAggregate.ts

- replace is active by is open in establishment entity
- add migration to replace is active by is opent in establishments table
- replace is active by is open in pg establishment aggregate repository

324 establishment aggregate changer isactive par isopen

---

front/src/app/contents/standard/budget.ts

Sur la page de budget: supprimer le paragraphe sous le titre "Évolution du budget depuis 2021"

update wording on budget page

---

back/src/domain/convention/useCases/RenewConventionMagicLink.ts
back/src/domain/convention/useCases/RenewConventionMagicLink.unit.test.ts
front/src/app/pages/convention/ConventionManagePage.tsx
front/src/app/routes/Router.tsx
front/src/app/routes/routes.ts
shared/src/domElementIds.ts
shared/src/routes/routes.ts

Suppression de l'ancienne route /verification

Supprimer la route manageConventionOld

---

front/src/core-logic/adapters/AddressGateway/HttpAddressGateway.ts
front/src/core-logic/adapters/AddressGateway/InMemoryAddressGateway.ts
front/src/core-logic/adapters/AddressGateway/TestAddressGateway.ts
front/src/core-logic/adapters/AgencyGateway/HttpAgencyGateway.ts
front/src/core-logic/adapters/AgencyGateway/InMemoryAgencyGateway.ts
front/src/core-logic/adapters/AgencyGateway/TestAgencyGateway.ts
front/src/core-logic/adapters/AssessmentGateway/HttpImmersionAssessmentGateway.ts
front/src/core-logic/adapters/AssessmentGateway/SimulatedImmersionAssessmentGateway.ts
front/src/core-logic/adapters/AssessmentGateway/TestImmersionAssessmentGateway.ts
front/src/core-logic/adapters/InclusionConnected/HttpInclusionConnectedGateway.ts
front/src/core-logic/adapters/InclusionConnected/SimulatedInclusionConnectedGateway.ts
front/src/core-logic/adapters/InclusionConnected/TestInclusionConnectedGateway.ts
front/src/core-logic/adapters/NavigationGateway/ReactNavigationGateway.ts
front/src/core-logic/adapters/OpenApiDocGateway/HttpOpenApiDocGateway.ts
front/src/core-logic/adapters/OpenApiDocGateway/InMemoryOpenApiDocGateway.ts
front/src/core-logic/adapters/RomeAutocompleteGateway/InMemoryRomeAutocompleteGateway.ts
front/src/core-logic/adapters/SearchGateway/SimulatedSearchGateway.ts
front/src/core-logic/adapters/SiretGatewayThroughBack/HttpSiretGatewayThroughBack.ts
front/src/core-logic/adapters/SiretGatewayThroughBack/SimulatedSiretGatewayThroughBack.ts
front/src/core-logic/adapters/SiretGatewayThroughBack/TestSiretGatewayThroughBack.ts
shared/src/agency/AgencyDtoBuilder.ts
shared/src/convention/ConventionDtoBuilder.ts

- fix eslint warning on frontend
- fix eslint warning on shared

front eslint fixes

---

back/src/adapters/primary/routers/apiKeyAuthRouter/createOpenApiV2.ts
back/src/adapters/secondary/poleEmploi/HttpPoleEmploiGateway.manual.test.ts
back/src/adapters/secondary/poleEmploi/HttpPoleEmploiGateway.ts

- add log in HttpPoleEmploiGateway
- change swagger servers to avoid CORS error

add log in http pe gateway

---

back/src/adapters/primary/scripts/seed.ts
back/src/adapters/secondary/pg/PgConventionQueries.integration.test.ts
back/src/adapters/secondary/pg/PgConventionQueries.ts
shared/src/convention/convention.schema.ts
shared/src/zodUtils.ts

- fix signatory schema, tutor should be actor and have no signedAt field
- fix zEnumValidation to have correct openAPI doc

fix api v2 issues

---

back/src/domain/offer/useCases/SearchImmersion.ts
back/src/domain/offer/useCases/SearchImmersion.unit.test.ts
shared/src/convention/ConventionDtoBuilder.ts
shared/src/convention/convention.dto.ts
shared/src/convention/convention.schema.ts
shared/src/convention/convention.ts

- improve label of deleted establisment test
- change ConventionValidators to ConventionValidatorInputNames

fix deleted establishment test label

---

front/src/app/components/forms/convention/sections/schedule/ScheduleSection.tsx
front/src/app/components/search/SearchListResults.tsx
libs/react-design-system/src/immersionFacile/components/hero-header/HeroHeader.scss
shared/src/romeAndAppellationDtos/rome.unit.test.ts
shared/src/romeAndAppellationDtos/romeAndAppellation.schema.ts
shared/src/search/SearchQueryParams.schema.ts

- rm at() method
- rm addMonth on dateMax (schedule)
- appellationCodeSchemaOptional really optional, used in search query params

737 quickfixes de soucis remontés par sentry

---

front/scalingo/nginx.conf.erb

Ça nous permettra d'utiliser des images uploadées dans les tickets directement sur le site.

allow content from github in CSP

---

back/src/adapters/primary/helpers/httpErrors.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/createApiKeyAuthRouter.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/createApiKeyAuthRouter.v1.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/getImmersionById.e2e.test.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/getImmersionBySiretAndRome.e2e.test.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/searchImmersionApi.e2e.test.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/searchImmersionApiPublicV1.e2e.test.ts
back/src/adapters/primary/routers/establishment/addFormEstablishment.e2e.test.ts
back/src/adapters/primary/scripts/seed.ts
back/src/adapters/secondary/InMemoryFeatureFlagRepository.ts
back/src/adapters/secondary/pg/migrations/1699264669326_add-feature-flags-enableApiV0-enableApiV1.ts
back/src/adapters/secondary/pg/repositories/PgFeatureFlagRepository.integration.test.ts
front/src/app/pages/admin/TechnicalOptionsTab.tsx
front/src/core-logic/domain/featureFlags/featureFlags.slice.ts
front/src/core-logic/domain/featureFlags/featureFlags.test.ts
front/src/core-logic/domain/testHelpers/test.helpers.ts
shared/src/featureFlags.ts

Les api V0 et V1 sont dépréciées.  
Elles seront supprimées prochainement.
Pour le moment, nous choisissons de les activer/désactiver à l'aide de feature flags.

Ajouter un Feature Flag pour les api V0 et V1

---

back/src/adapters/primary/routers/establishment/createEstablishmentRouter.ts
back/src/adapters/primary/routers/establishment/requestEditFormEstablishmentRoute.e2e.test.ts
front/src/app/components/SiretFetcherInput.tsx
front/src/core-logic/adapters/EstablishmentGateway/HttpEstablishmentGateway.ts
shared/src/routes/establishementRoutes.ts

fix request establishment modification link request

---

back/src/adapters/primary/routers/convention/convention.e2e.test.ts
back/src/adapters/primary/routers/convention/createConventionRouter.ts
back/src/adapters/secondary/pg/repositories/PgConventionQueries.integration.test.ts
shared/src/apiConsumer/apiConsumer.schema.ts
shared/src/convention/convention.routes.ts
shared/src/convention/convention.schema.ts
shared/src/schedule/Schedule.schema.ts
shared/src/schedule/ScheduleUtils.unit.test.ts

- use shared-routes in unauthenticated convention express router
- add a convention in findSimilarConventions integration test

use shared route for conventions

---

back/src/adapters/secondary/core/InMemoryEventBus.ts
back/src/adapters/secondary/core/TimeGateway/CustomTimeGateway.ts
back/src/adapters/secondary/notificationGateway/InMemoryNotificationGateway.ts
back/src/adapters/secondary/pg/repositories/PgApiConsumerRepository.ts
back/src/adapters/secondary/pg/repositories/PgOutboxRepository.ts
back/src/domain/convention/ports/PoleEmploiGateway.ts
back/src/domain/core/eventBus/EventBus.ts
back/src/domain/core/eventBus/events.ts
front/src/core-logic/domain/convention/convention.test.ts
shared/src/apiConsumer/ApiConsumer.ts
shared/src/convention/convention.dto.ts
shared/src/convention/conventionRefinements.ts
shared/src/notifications/notifications.dto.ts
shared/src/schedule/Schedule.dto.ts
shared/src/schedule/Schedule.schema.ts
shared/src/schedule/ScheduleUtils.ts
shared/src/utils/date.ts

- Mise à jour du type utilisée pour les dates de la convention
- Différencier les types dateString et dateTimeIsoString

Mise à jour du type utilisée pour les dates de la convention

---

front/src/app/components/forms/convention/ConventionForm.tsx

Mis à jour du wording des doublons de convention

---

back/src/adapters/primary/config/appConfig.ts
back/src/adapters/secondary/notificationGateway/BrevoNotificationGateway.ts
back/src/adapters/secondary/notificationGateway/BrevoNotificationGateway.unit.test.ts

- comment black list for demo
- fix emailDomainBlackList env variable

fix email sending

---

back/src/adapters/secondary/pg/migrations/1700825003262_add-index-to-notification-emails-joined-tables.ts

- add index to notifications joined tables in column created_at
- improve notification getEmailsByFilters query

add index on notifications joined

---

front/src/app/components/forms/agency/AddAgencyForm.tsx

improve wording in add agency form

---

back/src/adapters/secondary/pg/kysely/model/database.ts
back/src/adapters/secondary/pg/migrations/1701942937132_add-review-date-column-in-conventions-table.ts
back/src/adapters/secondary/pg/repositories/PgConventionRepository.integration.test.ts
back/src/adapters/secondary/pg/repositories/PgConventionRepository.ts
back/src/adapters/secondary/pg/repositories/pgConventionSql.ts
back/src/domain/convention/useCases/UpdateConventionStatus.ts
back/src/domain/convention/useCases/UpdateConventionStatus.unit.test.ts
front/src/app/contents/admin/conventionValidation.tsx
front/src/app/contents/forms/convention/formConvention.tsx
shared/src/convention/ConventionDtoBuilder.ts
shared/src/convention/convention.dto.ts
shared/src/convention/convention.schema.ts
shared/src/zodUtils.ts

- add review date column to convention table
- update convention repository
- add review date to convention dto
- update reviewDate when accepted by counselor
- display review date in convention validation page

864 etq utilisateur je connais la date dapprobation dune structure accompagnante

---

front/src/app/pages/home/HomePage.tsx
libs/react-design-system/src/immersionFacile/components/fixed-stamp/FixedStamp.styles.ts
libs/react-design-system/src/immersionFacile/components/fixed-stamp/FixedStamp.tsx

981-offre-temporaire-semaine-des-métiers-du-numérique

---

back/src/adapters/secondary/pg/migrations/1702040870380_replace-empty-value-in-columns-business-name-customized-and-customized-name-by-null.ts
back/src/domain/offer/useCases/AddFormEstablishment.ts
front/src/app/components/forms/establishment/CreationSiretRelatedInputs.tsx
shared/src/formEstablishment/FormEstablishment.schema.ts

- add migration to replace empty value for customized name by null
- upgrade form establishment schema to have better controle on customized name values

594 renforcer le controle schema establishment pour customizedname

---

back/src/adapters/secondary/InMemoryConventionQueries.ts
back/src/adapters/secondary/pg/repositories/PgConventionQueries.integration.test.ts
back/src/adapters/secondary/pg/repositories/PgConventionQueries.ts
back/src/domain/convention/entities/Agency.ts
back/src/domain/convention/ports/ConventionQueries.ts
back/src/domain/convention/useCases/ConventionsReminder.ts
back/src/domain/convention/useCases/ConventionsReminder.unit.test.ts
back/src/domain/convention/useCases/agencies/AddAgency.unit.test.ts
back/src/domain/convention/useCases/agencies/UpdateAgency.unit.test.ts
back/src/domain/convention/useCases/agencies/UpdateAgencyStatus.unit.test.ts

- fix reminder sent every day
- change same agency error message to french

fix reminders

---

back/src/adapters/primary/scripts/seed.ts
shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.routes.ts

- add a saved-error to the seed
- fix unhandled zod error on saved-error

 fix unhandled zod error on saved-error

---

front/src/app/components/layout/LayoutHeader.tsx
front/src/app/contents/home/content.ts
shared/src/domElementIds.ts

make 'Piloter mon entreprise' available publicly

---

front/src/app/components/forms/convention/ConventionSummarySection.tsx

- added tor and representative firstname/lastname to the convention summary
- added 'sub titles' for each signatories
- added types to the fields
- added test to check summary sections update

748 etq quutilisateurs je visualise plus de détails sur le bloc signataire de convention avant de la signer

---

back/src/adapters/secondary/pg/migrations/1705424391084_remove-outdated-feature-flags.ts

- remove outdated feature flags and fix schema
- fix migration to also remove enableUploadLogo feature flag

migration to remove outdated feature flags

---

playwright/package.json

Tentative de fix de la pipeline

Réduire EVENT_CRAWLER_PERIOD_MS pour les tests playwright sur la dev

---

back/src/adapters/primary/routers/admin/adminRouter.e2e.test.ts
back/src/adapters/primary/routers/magicLink/getConventionStatusDashboardUrl.e2e.test.ts
back/src/domain/dashboard/useCases/GetDashboardUrl.ts
front/src/core-logic/adapters/AdminGateway/HttpAdminGateway.ts
front/src/core-logic/adapters/AdminGateway/SimulatedAdminGateway.ts
front/src/core-logic/adapters/AdminGateway/TestAdminGateway.ts
front/src/core-logic/adapters/Convention/HttpConventionGateway.ts
front/src/core-logic/adapters/Convention/InMemoryConventionGateway.ts
front/src/core-logic/domain/admin/dashboardUrls/dashboardUrls.epics.ts
front/src/core-logic/domain/admin/dashboardUrls/dashboardUrls.test.ts
front/src/core-logic/domain/convention/convention.epics.ts
front/src/core-logic/domain/convention/convention.test.ts
front/src/core-logic/ports/AdminGateway.ts
front/src/core-logic/ports/ConventionGateway.ts
shared/src/admin/admin.routes.ts
shared/src/convention/convention.routes.ts
shared/src/dashboard/dashboard.dto.ts
shared/src/dashboard/dashboard.schema.ts

- rework GetDashboardUrl to return name off dashboard with url
- fix frontend to match dashboard return with name and url, and use it to fix parallele dashboard calls

1149 etq admin je ne vois plus les tdb agence

---

back/src/domain/convention/useCases/SendEmailWhenAgencyIsActivated.ts
back/src/domain/convention/useCases/SendEmailWhenAgencyIsActivated.unit.test.ts
shared/src/agency/agency.schema.ts
shared/src/agency/agency.ts

- fix edit agency schema
- send email activated email to both counsellors and validators

fix agency without safir and activation mail

---

front/src/app/components/ConsentManager.tsx
front/src/app/components/forms/establishment/sections/SearchableBySection.tsx

- Fix redirection sur la page de politique de confidentialité depuis le composant de cookies
- Fix wording sur le formulaire d'ajout d'entreprise

Fix wording recette

---

back/src/adapters/secondary/core/EventCrawlerImplementations.ts
back/src/domain/convention/useCases/ConventionsReminder.ts
shared/src/utils.ts

- **Revert "when crawling events**
- **Revert "refactor cron events: process by batch"**

rollback event related commits

---

back/src/adapters/secondary/core/EventCrawlerImplementations.ts
back/src/adapters/secondary/core/InMemoryOutboxRepository.ts
back/src/adapters/secondary/pg/migrations/1708954107350_add-in-process-to-type-event-status.ts
back/src/adapters/secondary/pg/repositories/PgOutboxRepository.integration.test.ts
back/src/adapters/secondary/pg/repositories/PgOutboxRepository.ts
back/src/domain/core/eventBus/events.ts
back/src/domain/core/ports/OutboxRepository.ts

add 'in-process' status to events

---

front/src/app/components/forms/autocomplete/AddressAutocomplete.tsx
front/src/app/components/forms/autocomplete/AppellationAutocomplete.tsx
front/src/app/components/forms/autocomplete/PlaceAutocomplete.tsx
front/src/core-logic/domain/geosearch/geosearch.slice.ts
front/src/core-logic/domain/geosearch/geosearch.test.ts
shared/src/romeAndAppellationDtos/romeAndAppellation.dto.ts

Stand by, en attendant de passer #1231 .

Feature / better feedback on autocompletes

---

back/src/adapters/secondary/pg/repositories/PgOutboxRepository.integration.test.ts
back/src/adapters/secondary/pg/repositories/PgOutboxRepository.ts
shared/src/search/SearchResult.schema.ts

- **fix error on pg outbox repositior on markEventsAsInProcess when events is empty**
- **fix SearchResult schema**

fixes recette

---

front/src/app/routes/routeParams/convention.ts
front/src/app/routes/routes.ts

fix appellations params in url

---

.github/workflows/deploy-to-scalingo.yml

Nouvelle tentative de notifier Discord des release notes de la nouvelle version

---

.github/workflows/deploy-to-scalingo.yml

Fix envoi des release notes à Discord (3e tentative)

---

back/src/domains/core/notifications/adapters/PgNotificationRepository.integration.test.ts
back/src/domains/core/notifications/adapters/PgNotificationRepository.ts

- **change artefact actions versions**
- **improve get notifications performance by limiting to last 2 days**

improve performances

---

back/src/config/pg/kysely/model/database.ts
back/src/config/pg/migrations/1710248347259_remove-establishments-immersion-contacts-table.ts
back/src/domains/establishment/adapters/PgDiscussionRepository.integration.test.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.getSiretOfEstablishmentsToSuggestUpdate.integration.test.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.test.helpers.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts
back/src/domains/establishment/adapters/PgGroupRepository.integration.test.ts
back/src/domains/establishment/adapters/PgGroupRepository.ts
back/src/scripts/seed.ts

- add migration to remove joint table between establishment and contact and rename immersion contact table
- remove establishments immersion contact implementation

#1248 - refacto immersion contact supprimer la table de jointure inutile

---

back/src/adapters/primary/routers/DtoAndSchemas/v2/input/ContactEstablishmentPublicV2.dto.ts
back/src/adapters/primary/routers/DtoAndSchemas/v2/input/ContactEstablishmentPublicV2.schema.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/contactEstablishmentPublicV2.e2e.test.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/createApiKeyAuthRouter.v2.ts
back/src/adapters/primary/routers/apiKeyAuthRouter/getSearchResultBySiretAndAppellationCodeV2.e2e.test.ts

FIX de la route d'API V2 de contact d'établissement

---

.github/workflows/deploy-to-scalingo.yml

- **support usage of backticks in deploy discord message**
- **try to fix Discord message on dev**

TECH amélioration du message de deploy

---

front/src/app/components/MetabaseView.tsx
front/src/app/pages/StatsPage.tsx

Ajout d'un nouvel onglet avec les stats des immersions sur la page [/stats](https://if-dev-front-pr1476.osc-fr1.scalingo.io/stats)
Closes #1081

#1081 - ajout d'un onglet Immersion sur la page de stats

---

back/src/domains/establishment/adapters/InMemoryEstablishmentAggregateRepository.ts
back/src/domains/establishment/adapters/InMemoryFormEstablishmentRepository.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.test.helpers.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts
back/src/domains/establishment/adapters/PgFormEstablishmentRepository.integration.test.ts
back/src/domains/establishment/adapters/PgFormEstablishmentRepository.ts
back/src/domains/establishment/ports/EstablishmentAggregateRepository.ts
back/src/domains/establishment/ports/FormEstablishmentRepository.ts
back/src/domains/inclusion-connected-users/use-cases/GetInclusionConnectedUser.ts
back/src/domains/inclusion-connected-users/use-cases/GetInclusionConnectedUser.unit.test.ts
front/src/app/pages/establishmentDashboard/EstablishmentDashboardPage.tsx
shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.dto.ts
shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.schema.ts

Plusieurs problèmes identifiés en staging sur la page de pilotage d'entreprises d'un utilisateur inclusion connecté:

FIX Pilotage d'entreprise: afficher les establishments de l'utilisateur ic plutôt que ses formEstablishments

---

back/src/config/pg/kysely/model/database.ts
back/src/config/pg/migrations/1712737182683_fix-establishment-aggregate.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts
back/src/domains/establishment/entities/EstablishmentEntity.ts

#1491 - fix valeurs optionnelles retirées à la mise à jour établissement

---

back/src/config/pg/migrations/1712836954831_add-index-on-search-related-tables.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts

- **add index on position on establishment locations**
- **optimize search query in establishment aggregate repository**

FIX - grosse amélioration des performances de la recherche

---

back/src/config/pg/kysely/model/database.ts
back/src/config/pg/migrations/1714381144194_add-number-employees-column-in-convention-table.ts
back/src/domains/convention/adapters/PgConventionRepository.integration.test.ts
back/src/domains/convention/adapters/PgConventionRepository.ts
back/src/domains/convention/adapters/pgConventionSql.ts
front/src/app/components/forms/convention/ConventionForm.tsx
front/src/app/contents/forms/convention/formConvention.tsx
shared/src/convention/ConventionDtoBuilder.ts
shared/src/convention/convention.dto.ts
shared/src/convention/convention.schema.ts

- create migration to add establishment number of employees column in convention table
- add establishment number of employees range in convention dto
- store establishment number  employees range in db

#1550 - stocker l'effectif de l'entreprise dans la convention

---

back/src/domains/core/authentication/inclusion-connect/adapters/PgInclusionConnectedUserRepository.integration.test.ts
back/src/domains/core/authentication/inclusion-connect/adapters/PgInclusionConnectedUserRepository.ts
back/src/domains/establishment/helpers/EstablishmentBuilders.ts

returns the establishments when querying the inculsion connected user by id (in PG)

FIX on peut maintenant voir et éditer sa fiche entreprise quand on est Inclusion Connecté et pas admin

---

.github/workflows/review-app-deploy.yml

Se connecter sur la review app en inclusion connect

TECH - Fix review-app redirection après connexion sur inclusion connect

---

back/src/config/pg/migrations/1717066330932_add-index-in-outbox-table.ts

Nous avons énormément de données dans la table outbox.
Ajouter d'index pour améliorer la perfomance de nos requetes sur cette table.

TECH - ajout d'index sur la table outbox

---

front/src/app/contents/home/content.ts
front/src/app/pages/admin/ManageConventionFormSection.tsx
front/src/app/pages/establishment-dashboard/ManageDiscussionFormSection.tsx
shared/src/domElementIds.ts
shared/src/email/emailTemplatesByName.ts

- **#1466 - add mtm campaign on emails CTA**
- **#1647 - add ids on establishment dashboard buttons**
- **#1704 - hero header home cards wording**

#1466 / #1647 / #1704 - Ajustements interface et mails

---

.github/workflows/continous-delivery.yml

- suppression du job de déploiement sur dev
- suppression du job Playwright sur dev

TECH - Modification du workflow github

---

front/src/app/pages/convention/ConventionDocumentPage.tsx

- **reinject scripts in html content to pdf generator**
- **remove script properly**

Fix / suppression des balises script lors de la génération pdf

---

front/src/core-logic/domain/inclusionConnected/inclusionConnected.test.ts
shared/src/inclusionConnect/inclusionConnect.dto.ts

ETQ admin et utilisateur IC qui a un rôle de "valideur", je veux pouvoir valider une convention

TECH - un utilisateur ic peut avoir plusieurs rôles

---

back/src/adapters/primary/routers/convention/addConventionAndSendMails.e2e.test.ts
back/src/adapters/primary/routers/convention/convention.e2e.test.ts
back/src/adapters/primary/routers/convention/signeeRejectsImmersionApplication.e2e.test.ts
back/src/config/bootstrap/createUseCases.ts
back/src/config/pg/kysely/model/database.ts
back/src/config/pg/migrations/1718746014021_add-column-convention-id-to-discussions-table.ts
back/src/domains/convention/use-cases/AddConvention.ts
back/src/domains/convention/use-cases/AddConvention.unit.test.ts
back/src/domains/convention/use-cases/RenewConvention.ts
back/src/domains/core/events/events.ts
back/src/domains/core/events/subscribeToEvents.ts
back/src/domains/establishment/adapters/PgDiscussionRepository.integration.test.ts
back/src/domains/establishment/adapters/PgDiscussionRepository.ts
back/src/domains/establishment/use-cases/discussions/MarkDiscussionLinkedToConvention.ts
back/src/domains/establishment/use-cases/discussions/MarkDiscussionLinkedToConvention.unit.test.ts
front/src/app/components/admin/establishments/DiscussionManageContent.tsx
front/src/app/components/forms/convention/ConventionFormWrapper.tsx
front/src/core-logic/adapters/Convention/HttpConventionGateway.ts
front/src/core-logic/adapters/Convention/InMemoryConventionGateway.ts
front/src/core-logic/domain/convention/convention.epics.ts
front/src/core-logic/domain/convention/convention.slice.ts
front/src/core-logic/domain/convention/convention.test.ts
front/src/core-logic/ports/ConventionGateway.ts
shared/src/convention/addConventionInput.ts
shared/src/convention/convention.routes.ts
shared/src/discussion/discussion.dto.ts
shared/src/discussion/discussion.schema.ts
shared/src/index.ts

- **save conventionId linked to discussion, on addConvention**
- **fix frontend to fit with discussionId optionnaly provided to addConvention**
- **reorganise DiscussionDto**

1697 lier une convention initié à partir d'une mise en relation par les id de la mer et de la convention

---

back/src/config/pg/kysely/model/database.ts
back/src/domains/establishment/adapters/PgDeletedEstablishmentRepository.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts

Mention spéciale sur une query qui utilise une fonction PostGIS. On peut le faire avec kysely avec l'ExpressionBuilder.

TECH - passage de requêtes établissement / établissement supprimé sous kysely

---

.github/workflows/continous-delivery.yml
.github/workflows/fullcheck.yml

- **trying to fix release to have correct references**
- **fix workflow release note**

FIX réparation des releases notes (2ème essais)

---

.github/workflows/generate-release.yml
.github/workflows/review-app.yml

- **fix workflow release with 'needs'**
- **fix release workflow**

TECH fix des releases

---

back/src/adapters/primary/routers/establishment/editFormEstablishment.e2e.test.ts
back/src/adapters/primary/routers/establishment/retrieveFormEstablishmentFromAggregate.e2e.test.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts
back/src/domains/establishment/adapters/PgFormEstablishmentRepository.integration.test.ts
back/src/domains/establishment/adapters/PgFormEstablishmentRepository.ts
back/src/domains/establishment/helpers/EstablishmentBuilders.ts
back/src/domains/establishment/helpers/makeEstablishmentAggregate.ts
back/src/domains/establishment/use-cases/RetrieveFormEstablishmentFromAggregates.ts
back/src/domains/establishment/use-cases/RetrieveFormEstablishmentFromAggregates.unit.test.ts
back/src/domains/establishment/use-cases/UpdateEstablishmentAggregateFromFormEstablishement.unit.test.ts
back/src/scripts/seed.ts
shared/src/formEstablishment/FormEstablishmentDtoBuilder.ts

- **init fix for establishment update (searchableBy)**
- **fixed searchableBy in establishment / form establishment repo**

Fix / Mise à jour d'entreprise (searchableBy)

---

front/src/app/components/forms/autocomplete/PlaceAutocomplete.tsx
front/src/app/components/search/SearchListResults.tsx
front/src/app/pages/search/SearchPage.tsx
front/src/core-logic/domain/geosearch/geosearch.slice.ts
front/src/core-logic/domain/geosearch/geosearch.test.ts

Fix / Corrections de divers bug sur la page de recherche

---

back/src/domains/core/api-consumer/use-cases/BroadcastToPartnersOnConventionUpdates.ts
back/src/domains/core/events/adapters/InMemoryEventBus.ts
back/src/domains/core/events/adapters/InMemoryEventBus.unit.test.ts

Cette PR fix la relance d'un évènement

TECH - Fix récupération de la dernière publication d'évènement

---

back/src/config/pg/migrations/1721067519821_add-index-on-date-end-in-convention-table-and-on-email-kind-in-notifications-email-table.ts
back/src/domains/convention/adapters/InMemoryConventionQueries.ts
back/src/domains/convention/adapters/PgConventionQueries.integration.test.ts
back/src/domains/convention/adapters/PgConventionQueries.ts
back/src/domains/convention/ports/ConventionQueries.ts
back/src/domains/core/events/events.ts
back/src/domains/core/unit-of-work/adapters/createInMemoryUow.ts
back/src/domains/establishment/use-cases/SendBeneficiariesAssesmentsEmails.unit.test.ts
back/src/domains/establishment/use-cases/SendBeneficiariesPdfAssessmentsEmails.ts
back/src/domains/establishment/use-cases/SendEmailsWithAssessmentCreationLink.ts
back/src/domains/establishment/use-cases/SendEmailsWithAssessmentCreationLink.unit.test.ts

- optimise pg query
- add index on date end and email kind
- core

#1826 - etq entreprise je veux recevoir l'email de bilan

---

back/package.json
back/src/adapters/primary/routers/convention/convention.e2e.test.ts
back/src/domains/convention/use-cases/ResyncOldConventionsToPe.unit.test.ts
back/src/domains/convention/use-cases/broadcast/BroadcastToPoleEmploiOnConventionUpdates.ts
back/src/domains/convention/use-cases/broadcast/BroadcastToPoleEmploiOnConventionUpdates.unit.test.ts
pnpm-lock.yaml
shared/src/convention/ConventionDtoBuilder.ts

This reverts commit e86f7ed80f75924c6342b1614bc1a3635ec72245.
Revert "change France Travail date birth format to match FT format"
This reverts commit 146f53c1914cc18ae8ea7f5a87adc328ff2a0c5a.

Revert "use date-fns-tz to set time in Paris, for France Travail broadcast" and "change France Travail date birth format to match FT format"

---

front/src/app/components/forms/agency/AddAgencyForm.tsx

#1913 - Modification du wording lorsque le prescripteur a une délégation

---

back/src/domains/convention/use-cases/partners-errored-convention/MarkPartnersErroredConventionAsHandled.unit.test.ts
back/src/domains/core/api-consumer/use-cases/BroadcastToPartnersOnConventionUpdates.ts
back/src/domains/core/saved-errors/adapters/InMemorySavedErrorRepository.ts
back/src/domains/core/saved-errors/adapters/PgSavedErrorRepository.integration.test.ts
back/src/domains/core/saved-errors/adapters/PgSavedErrorRepository.ts
back/src/domains/core/saved-errors/ports/SavedErrorRepository.ts
shared/src/errors/errors.ts

#1915 - ETQ prescripteur non FT, je veux pouvoir marquer une convention comme traitée

---

.github/workflows/review-app.yml
.github/workflows/validation-pr.yml

Ajout d'un job dans la CI de la PR qui échoue s'il y a un conflit de migration avec la branche main.

TECH - bloquer les conflits de migrations DB

---

back/src/adapters/primary/routers/inclusionConnect/inclusionConnectedAllowed.e2e.test.ts
front/src/app/pages/agency-dashboard/AgencyDashboardPage.tsx
front/src/app/pages/agency-dashboard/MarkPartnersErroredConventionAsHandledFormSection.tsx
front/src/core-logic/adapters/InclusionConnected/HttpInclusionConnectedGateway.ts
front/src/core-logic/domain/apiConsumer/apiConsumer.test.ts
front/src/core-logic/domain/convention/convention.test.ts
front/src/core-logic/domain/discussion/discussion.test.ts
front/src/core-logic/domain/feedback/feedback.slice.ts
front/src/core-logic/domain/feedback/feedback.test.ts
front/src/core-logic/domain/partnersErroredConvention/partnersErroredConvention.epics.ts
front/src/core-logic/domain/partnersErroredConvention/partnersErroredConvention.selector.ts
front/src/core-logic/domain/partnersErroredConvention/partnersErroredConvention.slice.ts
front/src/core-logic/domain/partnersErroredConvention/partnersErroredConvention.test.ts
shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.routes.ts

Discussion:
- ~~possibilité d'améliorer le typage (feedback.slice ligne 51)~~
~~Erreurs sur plusieurs tests à corriger.~~

#1825 - Fix le message d'erreur si 403 quand on veut marquer la convention comme traitée

---

back/src/adapters/primary/routers/admin/adminRouter.e2e.test.ts
back/src/domains/core/feature-flags/adapters/InMemoryFeatureFlagRepository.ts
back/src/domains/core/feature-flags/adapters/PgFeatureFlagRepository.integration.test.ts
back/src/domains/core/feature-flags/use-cases/SetFeatureFlag.unit.test.ts
back/src/scripts/seed.ts
front/src/app/pages/admin/technical-options-sections/FeatureFlagsSection.tsx
front/src/app/pages/search/SearchPage.tsx
front/src/core-logic/domain/featureFlags/featureFlags.slice.ts
front/src/core-logic/domain/featureFlags/featureFlags.test.ts
front/src/core-logic/domain/testHelpers/test.helpers.ts
shared/src/featureFlag/featureFlags.dto.ts
shared/src/featureFlag/featureFlags.schema.ts

- **init - types, back unit / integration / e2e tests**
- **adjust UI on feature flag boolean section, show score sortedBy option on SearchPage**
- **scoring sort by in UI search page**

#1656 - Activation recherche par scoring (feature flag)

---

back/package.json
back/src/config/pg/kysely/kyselyUtils.ts
back/src/config/pg/migrations/1721813251861_add-discussion-indexes.ts
back/src/domains/core/notifications/adapters/PgNotificationRepository.ts
back/src/domains/core/rome/use-cases/AppellationSearch.ts
back/src/domains/establishment/adapters/PgDiscussionRepository.integration.test.ts
back/src/domains/establishment/adapters/PgDiscussionRepository.ts
back/src/domains/establishment/ports/DiscussionRepository.ts
pnpm-lock.yaml

- **improve appellations log and also log parameters on SQL ERROR**
- **improve pg discussion repository queries**

TECH amélioration perfo concernant les discussions et echanges

---

back/src/scripts/seed.ts
front/src/app/components/immersion-offer/ContactByEmail.tsx
front/src/app/pages/search/SearchPage.tsx
playwright/tests/search/search.spec.ts
shared/src/contactEstablishmentRequest/contactEstablishmentRequest.dto.ts
shared/src/contactEstablishmentRequest/contactEstablishmentRequest.schema.ts
shared/src/domElementIds.ts

- **fixed filters update**
- **fixed search distanceKm + optional experienceAdditionalInformation**
- **add e2e tests**

Fix / Filtres sur la recherche + formulaire de contact MER mail

---

back/src/config/pg/migrations/1722002306970_remove-empty-custom-business-name.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts
front/src/app/components/forms/establishment/CreationSiretRelatedInputs.tsx
front/src/app/components/forms/establishment/EditionSiretRelatedInputs.tsx
shared/src/formEstablishment/FormEstablishment.schema.ts
shared/src/zodUtils.ts
shared/src/zodUtils.unit.test.ts

#1866 - traiter les noms d'entreprises personnalisés qui sont vides (chaînes de texte vide)

---

back/src/domains/convention/adapters/InMemoryConventionQueries.ts
back/src/domains/convention/adapters/PgConventionQueries.ts
back/src/domains/convention/ports/ConventionQueries.ts
back/src/domains/establishment/use-cases/SendBeneficiariesAssesmentsEmails.unit.test.ts
back/src/domains/establishment/use-cases/SendBeneficiariesPdfAssessmentsEmails.ts
back/src/domains/establishment/use-cases/SendEmailsWithAssessmentCreationLink.ts
back/src/domains/establishment/use-cases/SendEmailsWithAssessmentCreationLink.unit.test.ts
back/src/scripts/triggerSendingBeneficiaryPdfAssessmentEmails.ts
back/src/scripts/triggerSendingEmailsWithAssessmentCreationLink.ts
back/src/scripts/utils.ts
shared/src/assessment/assessment.dto.ts
shared/src/assessment/assessment.schema.test.ts
shared/src/assessment/assessment.schema.ts

==> merger la PR https://github.com/gip-inclusion/immersion-facile/pull/1970 avant

#1912 - Rattraper les mails de bilans qui n'ont pas été envoyés

---

back/src/scripts/seed.ts
front/package.json
front/src/app/pages/admin/technical-options-sections/ApiConsumersSection.tsx
front/src/core-logic/domain/apiConsumer/apiConsumer.slice.ts
front/src/core-logic/domain/apiConsumer/apiConsumer.test.ts
front/vite.config.ts
playwright/package.json
playwright/tests/admin/apiConsumerWorkflow.spec.ts
playwright/tsconfig.json
pnpm-lock.yaml

- **update Vite + clear api consumer in redux + editApiConsumerButtonLocator without expect**

Tech - Playwright flaky + mise à jour Vite

---

front/src/app/contents/home/content.ts

Amélioration des textes et ajout d'un lien vers l'inscirption a un webinaire.

#2007 Establishment & Agency new wording

---

front/src/app/contents/error/textSetup.tsx
front/src/app/contents/error/types.ts
front/src/app/pages/error/ErrorPageContent.tsx

#1568 - Ajout d'infos de debug dans les mails de contact support (page erreur)

---

front/src/app/contents/error/textSetup.tsx
front/src/app/main.tsx
front/src/app/pages/error/MinimalErrorPage.tsx
front/src/app/routes/routeParams/convention.ts
shared/src/errors/errors.ts

#2042 - Renvoyer un message d'erreur en cas de mauvais copier-coller d'URL (recherche, partage de convention)

---

back/src/adapters/primary/routers/admin/adminRouter.e2e.test.ts
back/src/config/pg/migrations/1723126978255_remove-counsellor-rights-on-users.ts
back/src/domains/inclusion-connected-users/use-cases/LinkFranceTravailUsersToTheirAgencies.ts
back/src/domains/inclusion-connected-users/use-cases/LinkFranceTravailUsersToTheirAgencies.unit.test.ts
back/src/domains/inclusion-connected-users/use-cases/UpdateIcUserRoleForAgency.ts
back/src/domains/inclusion-connected-users/use-cases/UpdateIcUserRoleForAgency.unit.test.ts
front/src/app/components/agency/AgencyUsers.tsx
playwright/tests/admin/manageUser.spec.ts
shared/src/errors/errors.ts

- remove counsellor option when agency is only one step validation
- throw an error if trying to update user right with role counsellor for agency with only one step validation
- change default role for user from counsellor to agency viewer

#1996 - Sur une agence prescriptrice sans double validation il y a un conseiller

---

back/src/domains/convention/adapters/PgConventionQueries.integration.test.ts
back/src/domains/convention/adapters/PgConventionQueries.ts

Actuellement, nous nous basons sur la date de fin de l'immersion pour envoyer les mails de demandes bilans:
- au bénéficiaire, 1 jour avant la fin de l'immersion
- à l'entreprise, 1 jour après la fin de l'immersion
Or, il arrive que des conventions soient créées à posteriori après la fin de l'immersion, ou créée au jour le jour.
Dans ces cas là, aucun mail de bilan ne leur est envoyé.
Envoyer un mail de bilan si la convention est validée, quelque soit la date de fin de l'immersion.

#1967 - Envoi de bilans pour des conventions passées qui viennent d'être validées

---

back/src/domains/convention/adapters/InMemoryConventionQueries.ts
back/src/domains/convention/adapters/PgConventionQueries.integration.test.ts
back/src/domains/convention/adapters/pgConventionSql.ts
back/src/domains/convention/entities/Convention.ts
back/src/domains/convention/use-cases/broadcast/BroadcastToPoleEmploiOnConventionUpdates.ts
back/src/domains/convention/use-cases/broadcast/BroadcastToPoleEmploiOnConventionUpdates.unit.test.ts
back/src/domains/core/api-consumer/helpers/agency.ts
back/src/domains/core/api-consumer/use-cases/BroadcastToPartnersOnConventionUpdates.unit.test.ts
front/src/app/contents/forms/convention/formConvention.tsx
shared/src/convention/convention.dto.ts
shared/src/convention/convention.schema.ts

- broadcast to pole emplois refers to
- broadcast to partners refers to

#1885 -  Synchroniser les conventions des agences d'accompagnement

---

back/src/config/bootstrap/createUseCases.ts
back/src/domains/establishment/use-cases/ContactEstablishment.ts
back/src/domains/establishment/use-cases/ContactEstablishment.unit.test.ts
back/src/domains/establishment/use-cases/notifications/NotifyContactRequest.ts
back/src/domains/establishment/use-cases/notifications/NotifyContactRequest.unit.test.ts
front/src/app/pages/admin/EmailPreviewTab.tsx
shared/src/email/EmailParamsByEmailType.ts
shared/src/email/emailTemplatesByName.ts

Mail de relance modifié:
Mail initial de mise en relation modifié:

Modification wording mail de relance MER et modification bouton mail initial MER

---

back/src/config/pg/migrations/1724773322988_remove-counsellor-and-validator-emails-backup-in-agencies.ts

Faire un db:down sur la staging avant de merge

TECH - Migration - suppression view_one_mail_per_agency_sib

---

front/src/app/components/agency/RegisterUsersToAgencies.tsx
front/src/app/pages/admin/AdminPage.tsx
shared/src/admin/adminTabs.ts

- **admin tab with admin props (isVisible)**
- **sort icUsersNeedingReview by lastname**

Fix / Ajustements de l'interface d'admin (onglet Notifications / liste déroulante des utilisateurs à rapprocher)

---

back/src/config/pg/migrations/1725895161568_update-discussion-status-to-accepted-if-linked-convention.ts

Migration testée uniquement en local.

#2156 - Mise à jour du statut des discussions liées à une convention

---

front/src/app/components/agency/AgencyUserModificationForm.tsx
front/src/app/components/agency/AgencyUsers.tsx
front/src/app/components/agency/EditAgency.tsx
front/src/app/components/agency/IcUserAgenciesToReview.tsx
playwright/tests/admin/manageUser.spec.ts
playwright/tests/dashboard/agencyWorkflow.spec.ts
shared/src/domElementIds.ts

- implement user form in register user to agency card

#2109 - Gestion de droits lors du rattachement d'un utilisateur à une agence

---

front/src/app/pages/establishment-dashboard/EstablishmentDashboardPage.tsx

- **fix establishment tutor can get conventions**
- **enable convention id input for establishment tutor**

Fix - Champ pour entrer l'id de convention est dispo pour les tuteurs en entreprise

---

back/package.json
back/scalingo/cron.json
back/src/config/pg/kysely/kyselyUtils.ts
back/src/domains/agency/adapters/pe-agencies-referential/HttpRome4Gateway.manual.test.ts
back/src/domains/agency/adapters/pe-agencies-referential/HttpRome4Gateway.ts
back/src/scripts/handleEndOfScriptNotification.ts
back/src/scripts/triggerUpdateRomeData.ts

Pris en compte des nouveaux romes et appellations + modification de l'existant

#1723 - Mettre à jour le DB avec les données du ROME V4

---

back/src/adapters/primary/routers/inclusionConnect/createInclusionConnectedAllowedRouter.ts
back/src/adapters/primary/routers/inclusionConnect/inclusionConnectedAllowed.e2e.test.ts
back/src/domains/inclusion-connected-users/use-cases/GetInclusionConnectedUser.ts
back/src/domains/inclusion-connected-users/use-cases/GetInclusionConnectedUser.unit.test.ts
front/src/core-logic/adapters/InclusionConnected/HttpInclusionConnectedGateway.ts
shared/src/inclusionConnectedAllowed/InclusionConnectedUser.builder.ts
shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.dto.ts
shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.routes.ts
shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.schema.ts

- **refactor GetInclusionConnectedUser to use currentUser instead of jwt**
- **WIP**

TECH - refacto du usecase GetInclusionConnectedUser pour qu'il soit exploitable par un admin (en vu de la page user)

---

back/src/scripts/handleCRONScript.ts
back/src/scripts/markEstablishmentsAsSearchableWhenMaxContactsAllows.ts
back/src/scripts/triggerContactRequestReminder3Days.ts
back/src/scripts/triggerContactRequestReminder7Days.ts
back/src/scripts/triggerConventionReminder.ts
back/src/scripts/triggerDeleteEmailAttachements.ts
back/src/scripts/triggerDeleteOldDiscussionMessages.ts
back/src/scripts/triggerEstablishmentLeadReminders.ts
back/src/scripts/triggerMarkOldConventionAsDeprecated.ts
back/src/scripts/triggerRefreshMaterializedViews.ts
back/src/scripts/triggerResyncOldConventionsToPe.ts
back/src/scripts/triggerSendingBeneficiaryPdfAssessmentEmails.ts
back/src/scripts/triggerSendingEmailsWithAssessmentCreationLink.ts
back/src/scripts/triggerSuggestEditFormEstablishmentEvery6Months.ts
back/src/scripts/triggerUpdateAllEstablishmentsScores.ts
back/src/scripts/triggerUpdateEstablishmentsFromSireneApiScript.ts
back/src/scripts/triggerUpdateRomeData.ts

- **rename handle CRON script notification**
- **send CRON data to sentry for better visualisation**

TECH - utilisation de Sentry pour visualiser les CRON job en success / erreurs dans le temps

---

back/src/config/pg/kysely/model/database.ts
back/src/config/pg/migrations/1729516729333_add-individual-protection-description-column-to-convention-table.ts
back/src/domains/convention/adapters/PgConventionRepository.ts
back/src/domains/convention/adapters/pgConventionSql.ts
front/src/app/components/forms/convention/ConventionSummarySection.tsx
front/src/app/components/forms/convention/sections/immersion-details/ImmersionDetailsSection.tsx
front/src/app/contents/forms/convention/formConvention.tsx
front/src/app/pages/convention/ConventionDocumentPage.tsx
front/src/app/routes/routeParams/convention.ts
shared/src/convention/ConventionDtoBuilder.ts
shared/src/convention/convention.dto.ts
shared/src/convention/convention.schema.ts
shared/src/domElementIds.ts

- add individual protection description field in convention form and summary (front)
- add individual protection description column in convention table and in repo (back)

#2307 - Ajout des informations de protection individuelle  dans le form de convention

---

back/src/adapters/primary/routers/technical/createTechnicalRouter.ts
back/src/adapters/primary/routers/technical/technicalRouter.e2e.test.ts
shared/src/errors/errors.ts

- **inbound parsing investigation -- TO ROLLBACK**
- **fix typo émail -> email**

Fix - Plus de logs sur le technicalRouter (contient des choses à rollback)

---

back/src/domains/convention/use-cases/notifications/NotifyIcUserAgencyRightChanged.ts
back/src/domains/convention/use-cases/notifications/NotifyIcUserAgencyRightChanged.unit.test.ts
front/src/app/pages/admin/EmailPreviewTab.tsx
shared/src/email/EmailParamsByEmailType.ts
shared/src/email/emailTemplatesByName.ts

#2318 - Modification du mail de notification de changement de droit d'un utilisateur

---

libs/react-design-system/src/immersionFacile/components/submit-confirmation-section/SubmitConfirmationSection.tsx

#2393 Fix - réduire l'espace sur l'ecran de confirmation d'envoi de convention

---

doc/adr/review-and-deployment-process.md

La PR ne pourra être mergée qu'après validation de tous les devs + PO

#2452 - ADR processus de recette et de mise en prod

---

back/src/adapters/primary/routers/establishment/retrieveFormEstablishmentFromAggregate.e2e.test.ts
back/src/domains/establishment/adapters/InMemoryEstablishmentAggregateRepository.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts
back/src/domains/establishment/adapters/PgFormEstablishmentRepository.integration.test.ts
back/src/domains/establishment/entities/EstablishmentEntity.ts
back/src/domains/establishment/helpers/EstablishmentBuilders.ts
back/src/domains/establishment/ports/EstablishmentAggregateRepository.ts
back/src/domains/establishment/use-cases/RetrieveFormEstablishmentFromAggregates.unit.test.ts
back/src/domains/establishment/use-cases/SearchImmersion.ts
back/src/domains/establishment/use-cases/SearchImmersion.unit.test.ts
front/src/core-logic/domain/establishmentPath/establishment.slice.ts
shared/src/formEstablishment/FormEstablishment.dto.ts
shared/src/formEstablishment/FormEstablishment.schema.ts
shared/src/formEstablishment/FormEstablishmentDtoBuilder.ts
shared/src/search/SearchQueryParams.dto.ts
shared/src/search/SearchQueryParams.schema.ts

#2326 - recherche - filtres handicap dans le back

---

.github/ISSUE_TEMPLATE/bug_report.md

Remplissage automatique du type de ticket "bug" sur le template

Mise à jour du template de problèmes: bug_report.md

---

.github/ISSUE_TEMPLATE/feature_request.md

Remplissage automatique du type de ticket "feature" sur le template

Mise à jour du template de feature: feature_request.md

---

back/src/adapters/primary/routers/agencies/agencies.e2e.test.ts
back/src/domains/agency/use-cases/ListAgenciesByFilter.ts
back/src/domains/agency/use-cases/ListAgenciesByFilter.unit.test.ts
back/src/domains/agency/use-cases/PrivateListAgencies.ts
back/src/domains/agency/use-cases/PrivateListAgencies.unit.test.ts
front/src/app/components/agency/AgencyAdminAutocomplete.tsx
front/src/app/components/agency/AgencyStatusBadge.tsx
front/src/app/components/agency/EditAgency.tsx
front/src/app/components/forms/agency/AdminAgencyDetail.tsx
front/src/app/components/forms/agency/EditAgencyForm.tsx
front/src/app/components/forms/register-agencies/MultipleAgencyInput.tsx
front/src/app/components/forms/register-agencies/RegisterAgenciesForm.tsx
front/src/app/pages/admin/AdminUserDetail.tsx
front/src/core-logic/adapters/AgencyGateway/SimulatedAgencyGateway.ts
front/src/core-logic/domain/admin/agenciesAdmin/agencyAdmin.epics.ts
front/src/core-logic/domain/admin/agenciesAdmin/agencyAdmin.test.ts
front/src/core-logic/domain/agencies/agencies.test.ts
shared/src/agency/agency.dto.ts
shared/src/agency/agency.schema.ts
shared/src/routes/agencyRoutes.ts

- retrieved all the agencies without filtering status in admin agency page
- retrieved all the agencies without filtering status in admin agency page

#2485 -  Remonter toutes les agences quel que soit leur status dans le champ autocomplete de selection d'agence dans l'admin

---

back/package.json
back/src/config/bootstrap/createGateways.ts
back/src/domains/core/email-validation/adapters/EmailableEmailValidationGateway.manual.test.ts
back/src/domains/core/email-validation/adapters/EmailableEmailValidationGateway.routes.ts
back/src/domains/core/email-validation/adapters/EmailableEmailValidationGateway.ts
back/src/domains/core/notifications/adapters/BrevoNotificationGateway.manual.test.ts
back/src/domains/core/notifications/adapters/BrevoNotificationGateway.ts
back/src/domains/core/notifications/adapters/BrevoNotificationGateway.unit.test.ts
back/src/domains/core/pdf-generation/adapters/ScalingoPdfGeneratorGateway.ts
back/src/domains/core/rome/adapters/DiagorienteAppellationsGateway.manual.test.ts
back/src/domains/core/rome/adapters/DiagorienteAppellationsGateway.routes.ts
back/src/domains/marketing/adapters/establishmentMarketingGateway/BrevoEstablishmentMarketingGateway.manual.test.ts
back/src/domains/marketing/adapters/establishmentMarketingGateway/BrevoEstablishmentMarketingGateway.ts
back/src/utils/apiBrevoUrl.ts
front/package.json
pnpm-lock.yaml
shared/package.json

- **update shared-routes**
- **user fetch shared routes for Diagoriente adapter**
- **log correctly PdfGenerator calls**
- **use fetch shared routes for Emailable adapter**
- **use fetch shared routes for BrevoEstablishmentMarketingGateway adapter**
- **use fetch shared routes for BrevoNotificationGateway adapter**

TECH passage de certains adapters a fetch, pour avoir le monitoring des erreurs

---

doc/adr/security/pnpm_dependencies_vulnerabilities.md

Piste pour assurer des versions minimum sur les sous dépendances.
``` json
{
"pnpm": {
"overrides": {
"lodash@<2.1.0": "^2.1.0"
}
}
}
```
https://blog.logto.io/pnpm-upgrade-transitive-dependencies
https://pnpm.io/cli/audit
https://pnpm.io/cli/outdated

TECH - ADR - Dependabot

---

front/src/app/components/UserDetail.tsx
front/src/app/components/layout/LayoutHeader.tsx
front/src/app/pages/MyProfile.tsx
front/src/app/pages/admin/AdminUserDetail.tsx
front/src/app/routes/InclusionConnectedPrivateRoute.tsx
front/src/app/routes/Router.tsx
front/src/app/routes/routes.ts

- **refactor UserDetail in a component to make profile page easier**
- **create my-profile page**

#2504  - création de la page mon profil (disponible depuis le bouton en haut à droite, Mon profil)

---

front/src/app/components/search/SearchListResults.tsx
front/src/app/components/search/SearchMiniMap.tsx
front/src/app/hooks/search.hooks.ts
front/src/app/pages/search/SearchPage.tsx
front/src/app/pages/search/SearchResultPage.tsx
front/src/app/routes/routes.ts
front/src/core-logic/domain/search/search.slice.ts

- **currentPage in searchSlice**
- **removed currentPage from redux, update form values and url params**

#2399 - Conservation de l'info de page consultée (résultats de recherche)

---

front/src/app/pages/search/SearchPage.tsx
libs/react-design-system/src/immersionFacile/components/section-stats/SectionStats.scss

- **updated search icons**
- **adjust home stats alignment**

Fix - Ajustements d'UI (icônes, recalages)

---

back/src/config/pg/migrations/1732192784073_establishment-contacts-to-establishment-rights.ts

TECH - fix migration - apply default contact mode for establishments without legacy contact

---

back/src/domains/establishment/use-cases/RequestEditFormEstablishment.ts
front/src/app/components/SiretFetcherInput.tsx
front/src/app/components/forms/establishment/EstablishmentForm.tsx
front/src/app/pages/error/ErrorPage.tsx
front/src/app/pages/error/ErrorPageContent.tsx
front/src/app/pages/establishment/RenewEstablishmentMagicLinkButton.tsx
front/src/app/utils/jwt.ts
shared/src/domElementIds.ts
shared/src/errors/errors.ts

#2526 - Ajout du bouton pour renvoyer un lien de MAJ d'entreprise

---

front/src/app/components/agency/AgencyUserModificationForm.tsx
front/src/app/components/forms/commons/EmailValidationInput.tsx
front/src/app/components/forms/convention/sections/beneficiary/BeneficiaryCurrentEmployerFields.tsx
front/src/app/components/forms/convention/sections/beneficiary/BeneficiaryFormSection.tsx
front/src/app/components/forms/convention/sections/beneficiary/BeneficiaryRepresentativeFields.tsx
front/src/app/components/forms/convention/sections/establishment/EstablishementTutorFields.tsx
front/src/app/components/forms/convention/sections/establishment/EstablishmentRepresentativeFields.tsx
front/src/app/components/forms/establishment/BusinessContact.tsx
front/src/app/components/immersion-offer/ContactByEmail.tsx

Selon le navigateur, il n'est pas possible de soumettre un formulaire de convention avec des accents dans les adresses email.

#2621 - Soumission du formulaire de convention bloqué à cause des accents dans les mails

---

front/src/app/components/forms/autocomplete/AppellationAutocomplete.tsx

- **suppr. Proposal / Option from AppellationAutocomplete**
- **AppellationAutocomplete getOption label bugfix**

#2692 - Tentative de fix sur le champ autocomplete de métier (recherche, convention)

---

back/src/domains/agency/adapters/InMemoryAgencyRepository.ts
back/src/domains/establishment/adapters/InMemoryEstablishmentAggregateRepository.ts
back/src/domains/establishment/adapters/la-bonne-boite/HttpLaBonneBoiteGateway.manual.test.ts
back/src/domains/establishment/adapters/la-bonne-boite/HttpLaBonneBoiteGateway.ts
back/src/domains/establishment/adapters/la-bonne-boite/InMemoryLaBonneBoiteGateway.ts
back/src/domains/establishment/adapters/la-bonne-boite/LaBonneBoiteCompanyDto.ts
back/src/domains/establishment/use-cases/SearchImmersion.ts
back/src/domains/establishment/use-cases/SearchImmersion.unit.test.ts
back/src/utils/distanceBetweenCoordinatesInMeters.ts

Permet de filtrer les résultats LBB sur la distance

#2730 - Calcul de la distance du point de recherche pour les resultats LBB - Permet d'appliquer le fitre de distance sur les résultats LBB

---

back/src/config/pg/migrations/1736507222905_update-immersion-assessments-number-of-missed-hours-type.ts
back/src/domains/convention/adapters/PgAssessmentRepository.ts
front/src/app/components/forms/assessment/AssessmentForm.tsx
shared/src/domElementIds.ts
shared/src/utils/date.ts
shared/src/utils/date.unit.test.ts

#2283 - bilan: séparation des heures manquées en deux champs

---

front/src/app/components/forms/assessment/AssessmentForm.tsx
libs/react-design-system/src/immersionFacile/components/convention-total-hours/ConventionTotalHours.tsx
libs/react-design-system/src/immersionFacile/components/convention-weekly-schedule/ConventionWeeklySchedule.tsx

#2283 - retours sur le bilan

---

back/src/domains/core/sirene/adapters/AnnuaireDesEntreprisesSiretGateway.manual.test.ts
back/src/domains/core/sirene/adapters/AnnuaireDesEntreprisesSiretGateway.ts
back/src/domains/core/sirene/adapters/InseeSiretGateway.ts

Ne prend pas en compte:
- amélioration des log/monitoring
- mise en place du caching

TECH - Amélioration AnnuaireDesEntrepriseSiretGateway pour basculer sur InseeSiretGateway en cas d'erreur

---

back/src/config/bootstrap/appConfig.ts
back/src/config/bootstrap/createGateways.ts
back/src/config/bootstrap/logPartnerResponses.ts
back/src/config/bootstrap/partnerNames.ts
back/src/domains/core/sirene/adapters/AnnuaireDesEntreprisesSiretGateway.manual.test.ts
back/src/domains/core/sirene/adapters/InseeSiretGateway.manual.test.ts
back/src/domains/core/sirene/adapters/InseeSiretGateway.routes.ts
back/src/domains/core/sirene/adapters/InseeSiretGateway.ts
back/src/scripts/triggerUpdateEstablishmentsFromSireneApiScript.ts
shared/src/errors/errors.ts
shared/src/errors/httpErrors.ts

- **refacto getSiretGateway**
- **WIP refacto Insee API gateway to use shared routes**

#2838 - TECH  ajout de monitoring sur les API siret (INSEE et annuaire des entreprises)

---

back/src/domains/core/address/adapters/HttpAddressGateway.ts
back/src/domains/core/caching-gateway/adapters/makeRedisWithCache.integration.test.ts
back/src/domains/core/caching-gateway/port/WithCache.ts
back/src/domains/core/email-validation/adapters/EmailableEmailValidationGateway.ts
back/src/domains/core/rome/adapters/DiagorienteAppellationsGateway.ts

- **improve types of withCache**
À merger après : #2885

TECH - amélioration du typage de withCache

---

front/package.json
pnpm-lock.yaml

remplace la PR #2854 (car pas assez de droit sur cette branche pour passer la PR)

TECH - mise à jour de vite

---

front/src/app/components/forms/register-agencies/RegisterAgenciesForm.tsx

Fix - Recherche d'agence par nom ou siret

---

back/src/config/pg/kysely/model/database.ts
back/src/config/pg/migrations/1737646984091_add-number-of-hours-actually-made-in-assessment-table.ts
back/src/domains/convention/adapters/PgAssessmentRepository.integration.test.ts
back/src/domains/convention/adapters/PgAssessmentRepository.ts
back/src/domains/convention/entities/AssessmentEntity.ts
back/src/domains/convention/use-cases/CreateAssessment.ts
back/src/domains/convention/use-cases/CreateAssessment.unit.test.ts
back/src/domains/convention/use-cases/GetAssessmentByConventionId.unit.test.ts
back/src/utils/assessment.ts
front/src/app/components/forms/assessment/AssessmentForm.tsx
shared/src/assessment/assessment.schema.test.ts
shared/src/assessment/assessment.schema.ts
shared/src/convention/convention.routes.ts
shared/src/schedule/ScheduleUtils.ts

n'inclue pas la récupération et le recalcule des données du passé. Ça pourra se faire dans une prochaine PR

#2809 - j'ai le nombre exact d'heure effectuées dans l'immersion stocké (exploitable dans un tableau de bord metabase)

---

front/src/app/components/forms/register-agencies/RegisterAgenciesForm.tsx
front/src/app/components/user-profile/UserProfile.tsx

Prise en compte de retours sur la fonctionnalité de rattachement à d'autres agences:
- modifications de la couleurs de boutons

#2639 - retours sur les couleurs de boutons

---

back/src/domains/inclusion-connected-users/use-cases/UpdateUserForAgency.ts
back/src/domains/inclusion-connected-users/use-cases/UpdateUserForAgency.unit.test.ts

1. Deux utilisateurs non inclusion connectés sont rattachés à une agence: user1 et user2
2. On modifie le mail de user1 pour user2, on a alors une erreur technique:
Bloquer ce cas d'utilisation et afficher un message plus explicite:

#2972 - Empêcher l'utilisateur de modifier un mail utilisateur d'agence pour un autre mail déjà rattaché à cette même agence

---

back/src/domains/convention/use-cases/notifications/NotifyAgencyThatAssessmentIsCreated.ts
back/src/domains/convention/use-cases/notifications/NotifyAgencyThatAssessmentIsCreated.unit.test.ts
back/src/domains/establishment/use-cases/SendBeneficiariesPdfAssessmentsEmails.unit.test.ts
front/src/app/components/forms/assessment/AssessmentForm.tsx
front/src/app/pages/convention/AssessmentDocumentPage.tsx
playwright/tests/assessment/assessmentWorkflow.spec.ts
shared/src/assessment/assessment.dto.ts
shared/src/assessment/assessment.helpers.ts
shared/src/assessment/assessment.schema.ts

- fix do not pre select options in assessment form
- fix rebase

#2901 - Ne plus pré sélectionner les champs du formulaire de bilan

---

back/src/domains/inclusion-connected-users/use-cases/RemoveUserFromAgency.ts
back/src/domains/inclusion-connected-users/use-cases/RemoveUserFromAgency.unit.test.ts
front/src/app/components/agency/agencies-table/AgenciesTablesSection.tsx
front/src/app/components/agency/agencies-table/OnGoingAgencyRightsTable.tsx
front/src/app/components/agency/agencies-table/agency-line/AgencyLineRightsCTAs.tsx
front/src/app/components/agency/agency-dashboard/NoActiveAgencyRights.tsx
front/src/app/pages/agency-dashboard/AgencyDashboardPage.tsx
front/src/core-logic/domain/admin/fetchUser/fetchUser.slice.ts
front/src/core-logic/domain/admin/fetchUser/fetchUser.test.ts
front/src/core-logic/domain/feedback/feedback.slice.ts
front/src/core-logic/domain/inclusionConnected/inclusionConnected.slice.ts
front/src/core-logic/domain/inclusionConnected/inclusionConnected.test.ts
playwright/tests/dashboard/agencyWorkflow.spec.ts
shared/src/admin/admin.dto.ts
shared/src/domElementIds.ts

- Fix RejectIcUserRoleForAgencyParams
- allowed user in review to remove himself from agency (back) Co-authored-by: Celine Ung <celineung@users.noreply.github.com>
- add cancel registration button  in ongoing registrations table Co-authored-by: Celine Ung <celineung@users.noreply.github.com>
- remove agency rights in redux

#2773 - Annuler les demandes de rattachement à des agences

---

back/src/domains/core/events/subscribeToEvents.ts
back/src/domains/core/support/adapters/HttpCrispGateway.manual.test.ts
back/src/domains/core/support/adapters/HttpCrispGateway.ts
back/src/domains/core/support/ports/CrispGateway.ts
back/src/domains/core/support/use-cases/SendSupportTicketToCrisp.testData.ts
back/src/domains/core/support/use-cases/SendSupportTicketToCrisp.ts
back/src/domains/core/support/use-cases/SendSupportTicketToCrisp.unit.test.ts

TECH - reprise du n8n pour envoyer les tickets à crisp

---

back/src/domains/core/support/use-cases/SendSupportTicketToCrisp.testData.ts
back/src/domains/core/support/use-cases/SendSupportTicketToCrisp.ts
back/src/domains/core/support/use-cases/SendSupportTicketToCrisp.unit.test.ts
back/src/utils/logger.ts

- **skip ticket that were self resolved**
- **log support tickets, in order to get some stats**

TECH - Ne pas essayer d'envoyer à CRISP les tickets résolu par un article

---

front/src/app/components/forms/assessment/AssessmentForm.tsx

#3021 - Modification du wording dans le formulaire de bilan

---

back/src/domains/establishment/adapters/la-bonne-boite/HttpLaBonneBoiteGateway.ts

J'ai tenté sans succès le clusturing avec Redis...

TECH - ajustement de Bottleneck pour éviter les 429 chez LBB

---

back/src/adapters/primary/routers/technical/createTechnicalRouter.ts
back/src/config/bootstrap/inclusionConnectAuthMiddleware.ts
front/src/app/components/UploadFile.tsx
front/src/app/components/forms/agency/EditAgencyForm.tsx
front/src/app/pages/admin/technical-options-sections/UploadFileSection.tsx
front/src/core-logic/adapters/TechnicalGateway/HttpTechnicalGateway.ts
front/src/core-logic/ports/TechnicalGateway.ts

- Réparer l'upload de fichier qui ne marchait plus car il manquait le token d'authorisation
- Utiliser le même composant UploadFile pour l'upload de fichier en tant qu'admin et sur le formulaire d'édition d'agence

#3091 - Fix téléchargement de fichier

---

front/src/app/components/agency/UsersWithoutNameHint.tsx

Petite modification de wording

Fix - Petite modification de wording: renommer inclusion connect en pro connect

---

back/package.json
back/src/config/bootstrap/server.ts
back/src/domains/core/UseCase.ts
back/src/scripts/configureSentry.ts
back/src/scripts/handleCRONScript.ts
back/src/scripts/startServer.ts
back/src/scripts/triggerUpdateRomeData.ts
front/package.json
front/src/app/main.tsx
pnpm-lock.yaml

- **setup sentry.io for back**
- **setup sentry.io for front**
- **fix sentry.io setup to have tracing**
- **add tracing to front end, configured to work with backend (distributed tracing)**
- **configure CRON with sentry**

TECH - passage sur sentry.io

---

front/src/app/contents/forms/convention/formConvention.tsx
front/src/app/contents/forms/convention/textSetup.tsx
front/src/app/pages/convention/ConventionDocumentPage.tsx
libs/html-templates/src/components/email/footer.ts
libs/html-templates/src/components/email/header.ts
shared/src/email/defaultConventionFinalLegals.ts
shared/src/email/emailTemplatesByName.ts

- wording
- change email params internship kind type
- Wip

3067 etq utilisateur de demande de mini stage le formulaire de demande est adapté aux 3 chambres consulaires

---

back/src/adapters/primary/routers/agencies/agencies.e2e.test.ts
back/src/config/pg/kysely/model/database.ts
back/src/config/pg/migrations/1743433154716_add-phone-number-to-agencies.ts
back/src/domains/agency/adapters/InMemoryAgencyRepository.ts
back/src/domains/agency/adapters/PgAgencyRepository.ts
back/src/domains/agency/use-cases/AddAgency.unit.test.ts
front/src/app/components/forms/agency/AddAgencyForm.tsx
front/src/app/components/forms/agency/AgencyFormCommonFields.tsx
front/src/app/contents/forms/agency/formAgency.ts
playwright/utils/agency.ts
shared/src/agency/AgencyDtoBuilder.ts
shared/src/agency/agency.dto.ts
shared/src/agency/agency.schema.ts
shared/src/domElementIds.ts

Ajout du champ numéro de téléphone sur le formulaire agence:

#2948 - Ajouter le champ numéro de téléphone sur le formulaire agence

---

front/src/app/components/forms/establishment/BusinessContact.tsx
front/src/app/pages/establishment-dashboard/EstablishmentUsersList.tsx
shared/src/email/emailTemplatesByName.ts

- **establishment add / update / delete in establishment edition, without establishment edition refacto**
- **update EditFormEstablishment usecase to handle new notifications**
- **UI tweaks**
- **fix after review**
- **fix userRolesToDispay**
- **fix staging listing establishment users**

#2868 - Ajustements listing utilisateurs entreprise

---

front/src/app/pages/convention/AssessmentDocumentPage.tsx

Correction orthographe et majuscule immersion professionnelle

FIX - Typo sur le bilan

---

back/src/config/bootstrap/magicLinkUrl.ts
back/src/domains/establishment/use-cases/SuggestEditEstablishment.ts
back/src/domains/establishment/use-cases/SuggestEditEstablishment.unit.test.ts
libs/react-design-system/src/immersionFacile/components/rs-autocomplete/RSAutocomplete.scss
libs/react-design-system/src/immersionFacile/components/rs-autocomplete/RSAutocomplete.tsx
shared/src/domElementIds.ts
shared/src/routes/routes.ts

- mise à jour de lien
- fix d'une soucis de CI pour DBT
- fix d'une bricole CSS pour les autocomplete

#3245 - FIX du lien dans les mails pour mise à jour d'entreprise tous les 6 mois

---

.github/workflows/fullcheck.yml

- **cache playwright browser**
- **cache node_moduels**

TECH - amélioration de la CI (cache playwright browser et cache node_modules)

---

back/src/domains/establishment/adapters/InMemoryEstablishmentAggregateRepository.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts
back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts
back/src/domains/establishment/ports/EstablishmentAggregateRepository.ts
back/src/domains/establishment/use-cases/SearchImmersion.ts
back/src/domains/establishment/use-cases/SearchImmersion.unit.test.ts
front/src/app/pages/search/SearchPage.tsx
libs/react-design-system/src/immersionFacile/components/search-filter/SearchFilter.scss

…usted integration tests and use case tests

#3046 - Ajustements sur l'affichage des résultats de recherche

---

front/src/app/pages/immersion-assessment/AssessmentPage.tsx

- fix error when accessing assessment page with expired jwt

#3327 - Fix Renouvellement du lien magique lors de l'accès a la page de completion du bilan

---

.github/workflows/continous-delivery.yml

TECH - fix du déploiement de DBT

---

front/src/app/components/forms/autocomplete/AddressAutocomplete.tsx
front/src/app/components/forms/establishment/EstablishmentForm.tsx
front/src/core-logic/domain/appellation/appellation.slice.ts
front/src/core-logic/domain/appellation/appellation.test.ts
front/src/core-logic/domain/geocoding/geocoding.slice.ts
front/src/core-logic/domain/geocoding/geocoding.test.ts
front/src/core-logic/domain/geosearch/geosearch.slice.ts
front/src/core-logic/domain/geosearch/geosearch.test.ts

- **added clearLocatorDataRequested, populate locator's state with previous state data**
- **updated test on slice that have multiple locators**

#3358 - Ajustement des autocomplete sur la fiche entreprise

---

shared/src/schedule/ScheduleUtils.ts
shared/src/schedule/ScheduleUtils.unit.test.ts

L'emploi du temps n'est pas bien compris par les usagers qui vont alors modifier la convention ou l'annuler.
La modification proposée par les UX est de ne pas afficher les dates au-delà de la période d'immersion.

#3405 - Ne pas afficher la semaine complète sur l'emploi du temps

---

back/src/adapters/primary/routers/inclusionConnect/createInclusionConnectedAllowedRouter.ts
back/src/adapters/primary/routers/inclusionConnect/inclusionConnectedAllowed.e2e.test.ts
back/src/adapters/primary/routers/technical/createTechnicalRouter.ts
back/src/adapters/primary/routers/technical/technicalRouter.e2e.test.ts
back/src/config/bootstrap/createUseCases.ts
back/src/domains/establishment/use-cases/discussions/AddExchangeToDiscussion.ts
back/src/domains/establishment/use-cases/discussions/AddExchangeToDiscussion.unit.test.ts
back/src/domains/establishment/use-cases/discussions/discussion.utils.ts
back/src/domains/establishment/use-cases/discussions/discussion.utils.unit.test.ts
front/src/app/components/admin/establishments/DiscussionManageContent.tsx
front/src/app/pages/convention/AssessmentDocumentPage.tsx
front/src/app/utils/sanitize.ts
front/src/core-logic/adapters/InclusionConnected/HttpInclusionConnectedGateway.ts
front/src/core-logic/adapters/InclusionConnected/SimulatedInclusionConnectedGateway.ts
front/src/core-logic/adapters/InclusionConnected/TestInclusionConnectedGateway.ts
front/src/core-logic/domain/discussion/discussion.epics.ts
front/src/core-logic/domain/discussion/discussion.slice.ts
front/src/core-logic/domain/discussion/discussion.test.ts
front/src/core-logic/domain/feedback/feedback.content.ts
front/src/core-logic/ports/InclusionConnectedGateway.ts
libs/react-design-system/src/immersionFacile/components/button-with-submenu/ButtonWithSubMenu.scss
shared/src/discussion/discussion.dto.ts
shared/src/discussion/discussion.schema.ts
shared/src/domElementIds.ts
shared/src/errors/errors.ts
shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.routes.ts
shared/src/utils/string.ts

…sion is handling both inbound-parsing and dashboard source

#2801 - Envoi de mail directement depuis l'espace entreprise

---

back/src/config/pg/migrations/1749631565175_add-highlight-feature-flags.ts
back/src/domains/core/feature-flags/adapters/InMemoryFeatureFlagRepository.ts
back/src/domains/core/feature-flags/adapters/PgFeatureFlagRepository.integration.test.ts
back/src/domains/core/feature-flags/adapters/PgFeatureFlagRepository.ts
back/src/scripts/seed/featureFlagSeed.ts
front/src/app/components/agency/agency-dashboard/AgencyDashboard.tsx
front/src/app/components/establishment/establishment-dashboard/EstablishmentDashboardTabs.tsx
front/src/app/contents/forms/admin/technicalOptions.ts
front/src/app/pages/admin/technical-options-sections/FeatureFlagsSection.tsx
front/src/core-logic/domain/featureFlags/featureFlags.slice.ts
front/src/core-logic/domain/featureFlags/featureFlags.test.ts
front/src/core-logic/domain/testHelpers/test.helpers.ts
libs/react-design-system/src/immersionFacile/components/index.ts
libs/react-design-system/src/immersionFacile/components/section-highlight/SectionHighlight.scss
libs/react-design-system/src/immersionFacile/components/section-highlight/SectionHighlight.styles.ts
libs/react-design-system/src/immersionFacile/components/section-highlight/SectionHighlight.tsx
libs/react-design-system/src/immersionFacile/components/section-highlight/index.ts
shared/src/featureFlag/featureFlags.dto.ts
shared/src/featureFlag/featureFlags.schema.ts

- **added highlight feature flags, typecheck ok**
- **added migrations**
- **fixed schemas, added migrations, admin forms, dashboard UI updated**

#3446 - Ajout d'une section de mise en avant (tableaux de bord)

---

libs/react-design-system/src/immersionFacile/components/convention-summary/ConventionSummary.scss
libs/react-design-system/src/immersionFacile/components/convention-summary/ConventionSummary.styles.ts
libs/react-design-system/src/immersionFacile/components/convention-summary/ConventionSummary.tsx

…r item styles, and updating class names for better structure and responsiveness.

#3439 - Ajustement graphique sur la page de pilotage

---

back/src/adapters/primary/routers/apiKeyAuthRouter/conventionPublicV2.e2e.test.ts
back/src/adapters/primary/routers/inclusionConnect/createInclusionConnectedAllowedRouter.ts
back/src/config/bootstrap/createUseCases.ts
back/src/config/pg/kysely/model/database.ts
back/src/domains/establishment/adapters/InMemoryDiscussionRepository.ts
back/src/domains/establishment/adapters/PgDiscussionRepository.integration.test.ts
back/src/domains/establishment/adapters/PgDiscussionRepository.ts
back/src/domains/establishment/ports/DiscussionRepository.ts
back/src/domains/establishment/use-cases/discussions/AddExchangeToDiscussion.ts
back/src/domains/establishment/use-cases/discussions/GetDiscussionsForUser.ts
back/src/domains/establishment/use-cases/discussions/GetDiscussionsForUser.unit.test.ts
shared/src/discussion/DiscussionBuilder.ts
shared/src/discussion/discussion.dto.ts
shared/src/discussion/discussion.helpers.ts
shared/src/discussion/discussion.schema.ts
shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.routes.ts

Ticket parent : https://github.com/gip-inclusion/immersion-facile/issues/3384

TECH - partie back du listing de discussion paginé, en vue de l'intégration dans le code du listing de discussions

---

front/src/app/contents/forms/convention/formConvention.tsx

Modif de texte demandée dans le kanban amelio : https://www.notion.so/gip-inclusion/Modif-Wording-CMA-2185f321b6048033875bebde66843755

Modification wording CMA demandée par bizdev

---

front/src/app/components/forms/convention/manage-actions/modals/EditCounsellorNameModalContent.tsx

#3617 - Ajout d'un message d'information dans la modale de modification du nom du conseiller

---

front/src/app/components/layout/StandardLayout.tsx
front/src/app/contents/standard/accessibilite.ts
front/src/app/contents/standard/budget.ts
front/src/app/contents/standard/cgu.ts
front/src/app/contents/standard/mentions-legales.ts
front/src/app/contents/standard/obligations-des-parties.ts
front/src/app/contents/standard/politique-de-confidentialite.ts
front/src/app/contents/standard/siteMap.ts
front/src/app/contents/standard/textSetup.ts
front/src/app/routes/routes.ts

- **make standard page support versions**
- **update cgu versions, to include older ones**

#3527 - rendre accessibles les différentes versions des cgu

---

front/src/app/components/agency/agency-dashboard/AgencyDashboard.tsx

En attente du retour de Sylvie sur les filtres nécessaires

#3581 - Réordonner les onglets du TDB Metabase pour les prescripteurs

---

front/src/app/components/establishment/establishment-dashboard/DiscussionList.tsx
front/src/app/components/establishment/establishment-dashboard/DiscussionStatusBadge.tsx
front/src/app/components/forms/convention/ConventionFormWrapper.tsx
libs/react-design-system/src/immersionFacile/components/rich-table/RichTable.scss
libs/react-design-system/src/immersionFacile/components/rich-table/RichTable.tsx
shared/src/email/emailTemplatesByName.ts

- **ui adjustments on edit convention buttons / margins**
- **fixed discussion list badge and date cell size**

Fix / Ajustements UI divers

---

front/src/app/components/forms/convention/ConventionFormWrapper.tsx

En target blank pour éviter de refaire la convention

#3584 - Ajouter un lien d'accès aux conventions en doublon si connecté

---

back/src/adapters/primary/routers/admin/createAdminRouter.ts
back/src/adapters/primary/routers/agencies/createAgenciesRouter.ts
back/src/adapters/primary/routers/auth/createAuthRouter.ts
back/src/config/bootstrap/createUseCases.ts
back/src/domains/agency/use-cases/AddAgency.ts
back/src/domains/agency/use-cases/AddAgency.unit.test.ts
back/src/domains/agency/use-cases/ListAgenciesByFilter.ts
back/src/domains/agency/use-cases/ListAgenciesByFilter.unit.test.ts
back/src/domains/agency/use-cases/PrivateListAgencies.ts
back/src/domains/agency/use-cases/PrivateListAgencies.unit.test.ts
back/src/domains/agency/use-cases/RegisterAgencyToConnectedUser.ts
back/src/domains/agency/use-cases/RegisterAgencyToConnectedUser.unit.test.ts
back/src/domains/agency/use-cases/UpdateAgency.ts
back/src/domains/agency/use-cases/UpdateAgency.unit.test.ts
back/src/domains/agency/use-cases/UpdateAgencyReferringToUpdatedAgency.ts
back/src/domains/agency/use-cases/UpdateAgencyReferringToUpdatedAgency.unit.test.ts
back/src/domains/agency/use-cases/UpdateAgencyStatus.ts
back/src/domains/agency/use-cases/UpdateAgencyStatus.unit.test.ts
back/src/domains/connected-users/use-cases/GetConnectedUser.ts
back/src/domains/connected-users/use-cases/GetConnectedUser.unit.test.ts
back/src/domains/connected-users/use-cases/GetConnectedUsers.ts
back/src/domains/connected-users/use-cases/GetConnectedUsers.unit.test.ts
back/src/domains/connected-users/use-cases/LinkFranceTravailUsersToTheirAgencies.ts
back/src/domains/connected-users/use-cases/LinkFranceTravailUsersToTheirAgencies.unit.test.ts
back/src/domains/connected-users/use-cases/RejectUserForAgency.ts
back/src/domains/connected-users/use-cases/RejectUserForAgency.unit.test.ts
back/src/domains/connected-users/use-cases/UpdateUserForAgency.ts
back/src/domains/connected-users/use-cases/UpdateUserForAgency.unit.test.ts
back/src/domains/core/authentication/connected-user/entities/user.helper.ts

- **use usecase builder in Agency domain**
- **use usecase builder in Users domain**

TECH - utilisation de useCaseBuilder au lieu de TransactionnalUseCase (pour les domaines Agency et Users)

---

front/src/app/components/agency/agency-dashboard/AgencyDashboard.tsx
front/src/app/pages/auth/ConnectedPrivateRoute.tsx
front/src/app/routes/Router.tsx
front/src/app/routes/routes.ts

Regrouper les tableaux des onglets "Détails par établissement" et "Conventions par établissement" en un seul onglet "Activités par établissement"

#3581 - Retour sur les onglets Metabase

---

front/src/app/components/establishment/establishment-dashboard/DiscussionList.tsx
front/src/app/components/establishment/establishment-dashboard/EstablishmentDashboardTabs.tsx

- **fix wording**
- **only show discussions tab if user has initial discussions**

#3458 - Réglage de l'affichage de l'onglet de candidatures

---

front/src/app/components/forms/autocomplete/AddressAutocomplete.tsx
front/src/app/components/forms/establishment/sections/OffersSettingsSection.tsx
front/src/app/hooks/formContents.hooks.ts

- **handle root key in zod 4 issues on array**
- **fixed form establishment UI**

#3777 - Ajustements sur la fiche entreprise

---

front/src/app/components/admin/technical-options/ApiConsumerForm.tsx
front/src/app/components/forms/agency/AddAgencyForm.tsx
front/src/app/components/forms/agency/AgencyFormCommonFields.tsx
front/src/app/components/forms/agency/agencyKindToLabel.ts
front/src/app/pages/agency/AddAgencyPage.tsx
shared/src/agency/agency.dto.ts

- **fix ordering of agency kind in AddAgencyForm**
- **WIP debugging**

#3695 - Ajustements sur l'ajout des collectivités territoriales

---

back/src/domains/convention/adapters/InMemoryConventionQueries.ts
back/src/domains/convention/adapters/PgConventionQueries.integration.test.ts
back/src/domains/convention/adapters/PgConventionQueries.ts
back/src/domains/convention/ports/ConventionQueries.ts
back/src/domains/marketing/use-cases/UpdateMarketingEstablishmentContactsList.ts

- Implement getConventionsMarketingData method in ConventionQueries and its integration tests.
- Refactor UpdateMarketingEstablishmentContactsList to use ConventionMarketingData for validated conventions

#3772 - Fix des erreurs lors de la mise a jour de la liste des établissements prospect dans brevo

---

front/src/app/components/agency/agency-dashboard/AgencyTasks.tsx

FIX - suppression du 0 lorsqu'il n'y a aucune tache restante pour le prescripteur

---

front/src/app/App.tsx
front/src/app/components/ConsentManager.tsx
front/src/app/components/MetabaseView.tsx
playwright/data/storageState.json

- **added subfinalities on cookie consent manager**
- **added subfinalities on cookie consent manager**

#3528 - Ajout des infos concernant les cookies
