.github/workflows/front-ci.yml, front/package.json
- todo list exemple project
- add front and back github actions workflows
- [back] add typecheck script and use it in CI
- fix broken test in JsonTodoRepository.integration.test
- better error message + fix date creation
- [back] remove test data from versionning
- Update back/src/domain/todos/entities/TodoEntity.ts
- add symlink to make front tests pass
=> Add back/src/shared -> front/src symlink to npm scripts

back/src/adapters/primary/config/createUseCases.ts, back/src/adapters/primary/routers/agencies/agencies.e2e.test.ts, back/src/adapters/primary/routers/technical/renewMagicLink.e2e.test.ts, back/src/domain/convention/useCases/RenewConventionMagicLink.ts, back/src/domain/convention/useCases/SendEmailWhenAgencyIsActivated.ts, back/src/domain/convention/useCases/SendEmailWhenAgencyIsActivated.unit.test.ts, back/src/domain/convention/useCases/ShareApplicationLinkByEmail.ts, back/src/domain/convention/useCases/notifications/ConfirmToSignatoriesThatApplicationCorrectlySubmittedRequestSignature.unit.test.ts, back/src/domain/convention/useCases/notifications/DeliverRenewedMagicLink.ts, back/src/domain/convention/useCases/notifications/NotifyAllActorsOfFinalConventionValidation.unit.test.ts, back/src/domain/convention/useCases/notifications/NotifyAllActorsThatConventionIsDeprecated.unit.test.ts, back/src/domain/convention/useCases/notifications/NotifyBeneficiaryAndEnterpriseThatApplicationIsRejected.unit.test.ts, back/src/domain/convention/useCases/notifications/NotifyBeneficiaryAndEnterpriseThatApplicationNeedsModification.unit.test.ts, back/src/domain/convention/useCases/notifications/NotifyConventionReminder.unit.test.ts, back/src/domain/convention/useCases/notifications/NotifyIcUserAgencyRightChanged.ts, back/src/domain/convention/useCases/notifications/NotifyIcUserAgencyRightChanged.unit.test.ts, back/src/domain/convention/useCases/notifications/NotifyLastSigneeThatConventionHasBeenSigned.unit.test.ts, back/src/domain/convention/useCases/notifications/NotifyNewApplicationNeedsReview.unit.test.ts, back/src/domain/convention/useCases/notifications/NotifyToAgencyApplicationSubmitted.unit.test.ts, back/src/domain/generic/notifications/entities/Notification.ts, back/src/domain/immersionOffer/useCases/RequestEditFormEstablishment.ts, back/src/domain/immersionOffer/useCases/RequestEditFormEstablishment.unit.test.ts, back/src/domain/immersionOffer/useCases/notifications/NotifyConfirmationEstablishmentCreated.unit.test.ts, back/src/domain/immersionOffer/useCases/notifications/NotifyContactRequest.unit.test.ts, back/src/domain/peConnect/useCases/NotifyPoleEmploiUserAdvisorOnConventionFullySigned.unit.test.ts, back/src/utils/notifyDiscord.manual.test.ts
- tranform last notification usecases to save notifications
- simplify makeSaveNotificationAndRelatedEvent function
=> save notifications last ones

.github/workflows/continous-delivery.yml, .github/workflows/fullcheck.yml
- use main branch instead of dev for continus deployment
=> use main instead of dev

back/src/_testBuilders/ImmersionOfferEntityV2Builder.ts, back/src/adapters/primary/routers/DtoAndSchemas/v1/input/ContactEstablishmentPublicV1.dto.ts, back/src/adapters/primary/routers/DtoAndSchemas/v1/input/ContactEstablishmentPublicV1.schema.ts, back/src/adapters/primary/routers/DtoAndSchemas/v2/input/ContactEstablishmentPublicV2.dto.ts, back/src/adapters/primary/routers/DtoAndSchemas/v2/input/ContactEstablishmentPublicV2.schema.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/contactEstablishmentPublicV2.e2e.test.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/createApiKeyAuthRouter.v2.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/searchImmersionApi.e2e.test.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/searchImmersionApiPublicV1.e2e.test.ts, back/src/adapters/primary/routers/createEstablishment/contactEstablishment.e2e.test.ts, back/src/adapters/primary/server.ts, back/src/adapters/secondary/pg/PgEstablishmentAggregateRepository.integration.test.ts, back/src/domain/immersionOffer/entities/ImmersionOfferEntity.ts, back/src/domain/immersionOffer/useCases/ContactEstablishment.unit.test.ts, back/src/domain/immersionOffer/useCases/InsertDiscussionAggregateFromContactRequest.ts, back/src/domain/immersionOffer/useCases/InsertDiscussionAggregateFromContactRequest.unit.test.ts, back/src/domain/immersionOffer/useCases/notifications/NotifyContactRequest.ts, back/src/domain/immersionOffer/useCases/notifications/NotifyContactRequest.unit.test.ts, back/src/domain/immersionOffer/valueObjects/LaBonneBoiteCompanyVO.ts, back/src/utils/makeFormEstablishmentToEstablishmentAggregate.ts, doc/api/search/contactEstablishmentV2.md, front/src/app/components/search/ContactByEmail.tsx, front/src/app/components/search/ContactByPhone.tsx, front/src/app/components/search/ContactInPerson.tsx, front/src/app/components/search/ContactModalContent.tsx, front/src/app/components/search/SearchListResults.tsx, front/src/app/pages/group/GroupListResults.tsx, shared/src/contactEstablishmentRequest/contactEstablishmentRequest.dto.ts, shared/src/contactEstablishmentRequest/contactEstablishmentRequest.schema.ts
create contact establishment api v2 and make appelation code and appellation label mandatory in immersion offer entity v2
=> create contact establishment api v2 

.github/workflows/cypress-run.yml, cypress/package.json
- fixed apos on curl command
- removed --parallel arg to cypress run-e2e
=> use local cypress in ci

back/src/adapters/secondary/pg/PgConventionsToSyncRepository.integration.test.ts, back/src/adapters/secondary/pg/PgConventionsToSyncRepository.ts
L'appel à `PgConventionsToSyncRepository.save()` ne fait qu'un `INSERT` en DB.  
Or on voudrait aussi pouvoir mettre à jour une convention.
=> Insert ou update lors du PgConventionsToSyncRepository.save

front/src/app/components/search/ContactByEmail.tsx, shared/src/email/emailTemplatesByName.ts
Retours sur les mails:
**Le nom de l'entreprise est pas le bon** --> dans l'exemple "Plateforme de l'inclusion" est celui renseigné dans le champ `name` et "Les services publics numériques de l'inclusion et de l'emploi" est celui renseigné dans le champ `customized_name` de la table `establishments` 
--> prévenir Arnaud
=> typo dans des mails remonté par arnaud

back/src/adapters/primary/scripts/triggerResyncOldConventionsToPe.ts
Corriger l'erreur de calcul sur le total des conventions à synchroniser dans le rapport de synchronisation des conventions avec PE.
=> fix rapport de synchronisation des conventions avec pe

front/src/app/components/search/ContactByEmail.tsx, front/src/app/components/search/ContactByPhone.tsx, front/src/app/components/search/ContactInPerson.tsx, front/src/app/components/search/usePotentialBeneficiaryValues.ts
Bug constaté sur une page de recherche d'entreprise:
1. On fait une première demande de contact d'entreprise
2. La requête API se passe bien: on reçoit une 200
3. Sur une autre entreprise on fait aussi une demande de contact
4. Erreur API: on reçoit une 409
Lors du deuxième appel API, le `siret` envoyé est resté celui de la première entreprise.
=> fix 400 when submit contact establishment again

front/scalingo/nginx.conf.erb
- les CSP indiquent les provenances possibles des choses (images, font, script, etc) qu'on utilise sur le site
- X-Content-Type-Options indique qu'on ne souhaite pas changer le mimetype des ressources utilisées par le site
- X-XSS-Protection c'est un vieil header permettant de bloquer une page si une attaque XSS est détectée par le navigateur (IE, Chrome, Safari)
=> added security headers in nginx conf

back/src/adapters/primary/scripts/seed.ts, shared/src/convention/ConventionDto.unit.test.ts, shared/src/convention/convention.dto.ts, shared/src/convention/convention.schema.ts
Mettre un place un minimum d'âge pour faire une demande mini-stage.
Cette PR inclut aussi:
- modification des seeds d'agence (pour pouvoir créer une demande mini-stage depuis l'interface web) 
- modification des tests du schema de convention pour rendre explicites pourquoi les conventions invalides le sont
=> 375 mettre un minimum dâge pour la demande de mini stage cci

back/src/adapters/primary/authMiddleware.ts, back/src/adapters/primary/config/createAppDependencies.ts, back/src/adapters/primary/helpers/handleHttpJsonResponseError.ts, back/src/adapters/primary/helpers/httpErrors.schema.ts, back/src/adapters/primary/helpers/sendHttpResponse.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/contactEstablishmentPublicV2.e2e.test.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/createApiKeyAuthRouter.v1.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/createApiKeyAuthRouter.v2.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/getImmersionOfferBySiretAndAppellationCode.e2e.test.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/publicApiV2.routes.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/searchImmersionApiPublicV2.e2e.test.ts, back/src/domain/core/UseCase.ts, shared/src/httpClient/errors/httpErrors.schema.ts, shared/src/index.ts, shared/src/searchImmersion/searchImmersion.routes.ts
Les erreurs renvoyées par notre api V2 ont des formats différents: parfois avec une propriété `errors`, parfois avec `error`, parfois contenant une tableau `issues`, etc.
Cette PR permet de mettre en place un format fixe.
=> Uniformiser les formats d'erreurs renvoyé depuis nos routes api V2

back/src/adapters/secondary/addressGateway/HttpAddressGateway.manual.test.ts, shared/src/address/address.schema.ts
Bête et méchant mais ça fait le boulot.
=> lookupStreetAddressSpecialCharsRegex now catches pattern '{d}\s,' in schema and provide validation error

front/src/app/components/forms/commons/SchedulePicker/RegularSchedulePicker.tsx, front/src/app/components/forms/commons/SchedulePicker/SchedulePicker.tsx, front/src/app/components/forms/commons/SchedulePicker/WeekdayPicker.tsx, front/src/app/components/forms/convention/sections/hour-location/ImmersionHourLocationSection.tsx, front/src/app/routes/routeParams/convention.ts, shared/src/convention/ConventionDto.unit.test.ts, shared/src/convention/ConventionDtoBuilder.ts, shared/src/convention/convention.schema.ts, shared/src/schedule/ScheduleUtils.ts, shared/src/schedule/ScheduleUtils.unit.test.ts
Pour les mini-stage, il ne doit pas être possible de travailler le dimanche.
- modification des schemas
- bloquer la sélection du dimanche dans le formulaire de création de convention mini-stage
Il n'est pas possible de désactiver une date en particulier sur le datepicker natif html.  
Par contre, si un dimanche est sélectionné en date de début/fin, les dropdowns de sélection de jour de semaine indiquent bien que le dimanche n'est pas inclus (voir screenshot ci-dessous, où 29 juillet est un samedi et 30 juillet est un dimanche).
=> ne pas autoriser le dimanche pour les mini stage

back/src/adapters/primary/config/createUseCases.ts, back/src/adapters/primary/routers/convention/convention.e2e.test.ts, back/src/domain/convention/useCases/ShareApplicationLinkByEmail.ts, back/src/domain/core/ShortLink.ts
Lorsqu'un utilisateur choisit de partager sa convention par mail depuis le formulaire de création de convention
Dans le mail reçu de partage de convention, le lien vers le formulaire de convention est tronqué car il est trop long.
Lorsqu'une demande de partage de convention par mail est reçue, un lien court est créé. C'est ce lien qui est ensuite partagé par mail.
=> Utiliser le système de lien court pour le partage de convention par email

shared/src/convention/ConventionDto.unit.test.ts, shared/src/schedule/ScheduleUtils.ts
Un mini-stage ne peut pas se dérouler un dimanche.  
Or, pour savoir si le dimanche est inclus, il faut aussi vérifier si des heures y sont précisés (et non pas se baser uniquement sur le jour).
=> fix: bloquer la création de convention mini-stage se déroulant un dimanche

front/src/app/components/forms/agency/AgencyFormCommonFields.tsx, front/src/app/components/forms/agency/agencyKindToLabel.ts
Les agences Pôle emploi sont déjà référencées, elles n'ont pas besoin de le faire à nouveau.
Afficher un message sur le formulaire d'ajout de prescripteur lorsque le type est "pole-emploi".  
Il s'agit d'un message indicatif et non bloquant pour la soumission du formulaire.
=> afficher un message d'erreur lorsque le type de prescripteur dans le formulaire est "pole-emploi"

front/scalingo/nginx.conf.erb
When redirecting short link, location header is too long
=> Increase nginx buffer size

back/src/_testBuilders/emailAssertions.ts, back/src/domain/convention/useCases/notifications/NotifyAllActorsOfFinalConventionValidation.ts, back/src/domain/offer/useCases/SendEmailsWithAssessmentCreationLink.ts, back/src/domain/offer/useCases/SendEmailsWithAssessmentCreationLink.unit.test.ts, front/src/app/pages/admin/EmailPreviewTab.tsx, shared/src/agency/AgencyDtoBuilder.ts, shared/src/email/EmailParamsByEmailType.ts, shared/src/email/emailTemplatesByName.ts, shared/src/utils.ts
Dans les mails de validation et de création de bilan, le lien du bilan est toujours celui par défaut.  
Celui renseigné par le prescripteur n'est pas communiqué dans les mails.
=> Envoyer le lien de bilan de l'agence, si présent, dans les mails

back/src/adapters/secondary/pg/migrations/1694089930949_update-api-consumers-rights.ts
La colonne rights de la table api_consumers ne peut désormais contenir qu'un seul propriété: soit `searchEstablishment` soit `convention` mais pas les deux en même temps (cf le type ApiConsumer).
Cette PR met à jour les informations déjà existantes en DB.
On met à jour toutes les lignes en DB: elle n'ont actuellement que les droits `READ` en `searchEstablishment`, d'où le fait que notre requête d'update ne contient pas de clause `where`.
=> ajout fichier de migration pour mettre à jour la colonne rights de api_consumers

front/src/app/components/admin/conventions/ConventionManageActions.tsx, front/src/app/pages/convention/ConventionDocumentPage.tsx, front/src/app/routes/routes.ts
Dans le backoffice, lorsque l'on clique sur "voir la convention" depuis une page de convention, on a une erreur: la convention  ne s'affiche pas sur la page `/convention-immersion`.
1. L'appel à l'api pour récupérer la convention est `/api/auth/demandes-immersion/undefined`. L'id de la convention est manquante
2. En remontant la trace jusque `ConventionDocumentPage.tsx`, on récupère `applicationId` à partir du jwt. Or avec le jwt de backoffice, `applicationId` est undefined.
Lorsque l'accès à la page `/convention-immersion` se fait depuis le backoffice, alors on communique aussi l'id de la convention en param de la route
=> Fix voir la convention

front/src/app/components/forms/agency/AgencyFormCommonFields.tsx, front/src/app/pages/convention/ConventionDocumentPage.tsx
Des conseillers nous parlent de leur document de convention.
Mais ces documents ne contiennent pas d'id de convention. Donc il est difficile de chercher la convention concernée.
Ajout l'id de la convention pour faciliter la communication.
=> Afficher l'id de la convention 

back/package.json, back/src/adapters/secondary/pg/migrations/1695885238870_add-department-shape.ts, back/tsconfig.json
Actuellement lorsqu'on souhaite associer le département sur lequel porte une recherche, on utilise le champ `address` de la table `searches_mades` qui malheureusement a un format très diverse. Pour ce faire, on utilise un regexp pour extraire le nom du département mais cela est assez fragile et permet de résoudre seulement 50% des recherches
On ajoute dans la table `public_department_region` un champ geometry (postgis) qui va contenir la forme du departement. Pour cela on s'appuie sur https://github.com/gregoiredavid/france-geojson/ qui met à disposition des cartes des régions / département / ville au format geojson.
N'etant pas disponible sur npm, le fichier à été coller dans le dépot. Pour le charger, il a fallu aussi modifier des option du compilateur TS pour charger des fichiers json. …
=> feat: add department shape in public_departement_region

back/transpile-back-and-prepare-for-prod.js
Nous rencontrons des problèmes sur [la pipeline](https://github.com/gip-inclusion/immersion-facile/actions/runs/6348539741): le paramètre `compilerOptions` n'est pas compris.
Ce paramètre est utilisé pour importer un fichier `json` depuis notre fichier de migration typescript.
Le paramètre `compilerOptions` n'est plus nécessaire une fois le back buildé.
Cette PR propose de le supprimer depuis le `transpile-back-and-prepare-for-prod.js`.
=> fix pipeline: supprimer le --compilerOptions du package.json

back/src/adapters/primary/config/createUseCases.ts, back/src/adapters/primary/routers/inclusionConnect/createInclusionConnectedAllowedRouter.ts, back/src/adapters/primary/routers/inclusionConnect/inclusionConnectedAllowed.e2e.test.ts, back/src/adapters/primary/subscribeToEvents.ts, back/src/adapters/secondary/core/InMemoryErrorRepository.ts, back/src/adapters/secondary/pg/kysely/model/database.ts, back/src/adapters/secondary/pg/repositories/PgErrorRepository.integration.test.ts, back/src/adapters/secondary/pg/repositories/PgErrorRepository.ts, back/src/domain/convention/useCases/broadcast/BroadcastToPoleEmploiOnConventionUpdates.ts, back/src/domain/convention/useCases/broadcast/BroadcastToPoleEmploiOnConventionUpdates.unit.test.ts, back/src/domain/convention/useCases/partnersErroredConvention/MarkPartnersErroredConventionAsHandled.ts, back/src/domain/convention/useCases/partnersErroredConvention/MarkPartnersErroredConventionAsHandled.unit.test.ts, back/src/domain/core/eventBus/events.ts, back/src/domain/core/ports/ErrorRepository.ts, front/src/app/pages/agencyDashboard/AgencyDashboardPage.tsx, front/src/app/pages/agencyDashboard/MarkPartnersErroredConventionAsHandledFormSection.tsx, front/src/app/pages/convention/ConventionManageAdminPage.tsx, front/src/app/routes/Router.tsx, front/src/core-logic/adapters/InclusionConnected/HttpInclusionConnectedGateway.ts, front/src/core-logic/adapters/InclusionConnected/SimulatedInclusionConnectedGateway.ts, front/src/core-logic/adapters/InclusionConnected/TestInclusionConnectedGateway.ts, front/src/core-logic/domain/partnersErroredConvention/partnersErroredConvention.epics.ts, front/src/core-logic/domain/partnersErroredConvention/partnersErroredConvention.selector.ts, front/src/core-logic/domain/partnersErroredConvention/partnersErroredConvention.slice.ts, front/src/core-logic/domain/partnersErroredConvention/partnersErroredConvention.test.ts, front/src/core-logic/ports/InclusionConnectedGateway.ts, front/src/core-logic/storeConfig/store.ts, shared/src/convention/convention.dto.ts, shared/src/convention/convention.schema.ts, shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.routes.ts
- add input in errored convention dashboard to mark a convention as handled front part
-  mark partners errored convention as handled
=> 678 gestion des conventions à saisir depuis le tableau de bord prévoir de quoi cocher les conventions quils régularisent dans leurs applicatifs

back/src/adapters/secondary/pg/migrations/1698922693705_add-index-on-outbox-created-at.ts
Amélioration de query sur l'outbox qui utilise un filtre ou un tri sur `occured_at`.
La query suivante passe de + de 20 secondes à 250ms :
```sql
SELECT *
FROM "outbox"
ORDER BY "occurred_at" DESC
LIMIT 50
```
=> improve performance on outbox using index on occured_at

libs/react-design-system/src/immersionFacile/components/index.ts, libs/react-design-system/src/immersionFacile/components/simple-section/SimpleSection.scss, libs/react-design-system/src/immersionFacile/components/simple-section/SimpleSection.stories.tsx, libs/react-design-system/src/immersionFacile/components/simple-section/SimpleSection.tsx, libs/react-design-system/src/immersionFacile/components/simple-section/index.ts
Nous souhaitons créer un nouveau type de section qui ressemblerait à:
Pour permettre de rendre ce format réutilisable, je propose d'inclure ce template dans notre design-system: textes, image, boutons et liens sont ainsi customisables. Voici le rendu depuis la story:
Je n'ai pas réussi à ajouter les flèches dans les boutons/liens. J'ai bien testé avec la classe `fr-link--icon-right` mais ça n'a pas fonctionné, si quelqu'un a une piste... sinon je verrai avec @enguerranws à son retour.
=> Ajout d'un composant simple-section dans notre DS

back/transpile-back-and-prepare-for-prod.js
La pipeline sur `main` est cassée car on fait référence à `http-client` dans notre script `transpile-back-and-prepare-for-prod.js`.
Supprimer les références à `http-client`.
=> Fix: supprimer l'usage de http-client

front/src/app/components/forms/convention/ConventionForm.tsx, front/src/core-logic/adapters/Convention/HttpConventionGateway.ts, front/src/core-logic/adapters/Convention/InMemoryConventionGateway.ts, front/src/core-logic/domain/convention/convention.epics.ts, front/src/core-logic/domain/convention/convention.selectors.ts, front/src/core-logic/domain/convention/convention.slice.ts, front/src/core-logic/domain/convention/convention.test.ts, front/src/core-logic/ports/ConventionGateway.ts, shared/src/convention/convention.schema.ts
On souhaite éviter la création de convention en doublon.  
Pour cela:
1. on affiche un message sur la page de récapitulatif de convention à créer
2. lorsque l'on clique sur "Envoyer la convention", une modale demande la confirmation de création de ce possible doublon
=> Eviter les conventions en doublon front

back/src/_testBuilders/emailAssertions.ts, back/src/domain/convention/useCases/notifications/NotifyAllActorsOfFinalConventionValidation.ts, front/src/app/pages/admin/EmailPreviewTab.tsx, shared/src/email/EmailParamsByEmailType.ts, shared/src/email/emailTemplatesByName.ts
Certains stagiaires renvoient le bilan à l'équipe IF.  
Pour éviter cela, nous souhaitons préciser dans le mail de "Convention finale validée" d'envoyer le bilan au valideur de la convention.
Dans le mail de "Lien de creation du bilan", il est déjà précisé d'envoyer le bilan au valideur de la convention avec son adresse mail.
=> Préciser à quelle adresse mail envoyer le bilan dans le mail de "Convention finale validée"

back/src/adapters/primary/authMiddleware.ts, back/src/adapters/primary/config/createUseCases.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/createApiKeyAuthRouter.v2.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/createOpenApiV2.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/publicApiV2.routes.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/webhookPublicV2.e2e.test.ts, back/src/domain/broadcast/useCases/DeleteSubscription.ts, back/src/domain/broadcast/useCases/DeleteSubscription.unit.test.ts, shared/src/apiConsumer/ApiConsumer.ts
On pouvait créer et lister les souscriptions webhooks d'un apiConsumer.  
Cette PR permet d'en supprimer une.
```bash
curl --request DELETE 'http://localhost:3000/api/v2/webhooks/1be3d916-7030-4bc3-8755-8a6cf5b78bbc' --header 'authorization:  {your token}'
```
=> Ajout route de suppression d'un webhook

back/src/adapters/secondary/pg/migrations/1701091120541_modify-view-agencies-created-at-as-date.ts
Sur Metabase, la question "Répartition géographique des prescripteurs référencés" de [la page de statistiques](https://immersion-facile.beta.gouv.fr/stats) tombe en erreur lorsque des filtres de dates sont appliqués: le filtre de date manipule le champ "created_at" de la table "view_agencies" comme une date, alors qu'il s'agit d'un champ texte. La requête tombe alors en erreur.
Mise à jour du type de "created_at" de la vue "view_agencies" de `text` à `timestamp`.
- Possible de casser d'autres questions Metabase --> à surveiller
- La vue "view_conventions" a aussi dûe être drop/create car il y a une dépendance avec la vue "view_agencies"
=> Mise à jour du type de "created_at" de la vue "view_agencies"

back/src/_testBuilders/buildTestApp.ts, back/src/adapters/primary/authMiddleware.ts, back/src/adapters/primary/config/appConfig.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/createOpenApiV2.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/publicApiV2.routes.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/publicApiV2Bottleneck.e2e.test.ts
Pour éviter que nos consommateurs surcharge nos serveurs avec leurs appels à nos api publiques, nous souhaitons mettre en place une limite.
Nous utilisons la librairie Bottleneck pour mettre en place ce mécanisme.
Le nom maximal d'appels api concurrents pour un même consommateur est défini par la variable d'environnement `MAX_API_CONSUMER_CALLS_PER_SECOND`. Au-delà, l'appel api est rejeté en HTTP 429.
=> Bottleneck sur l'api V2

.github/workflows/review-app-deploy.yml
- désactiver le déploiement automatique de la review-app par Scalingo
Nous déployons déjà depuis le Scalingo CLI via github actions. Ce déploiement finit en succès. Or avec le déploiement automatique de Scalingo d'activé, un deuxième déploiement est déclenché, ce déploiement échoue car il utilise npm et non pnpm. Pour éviter d'avoir un deuxième déploiement - qui échoue en plus, des jobs de désactivation de déploiements automatiques ont été ajoutés dans notre processus.
- nous avions une limite sur le nombre limite d'applications maximum, ce qui entrainait dernièrement un échec de création de review app. Pour corriger ce problème, Scalingo a augmenté notre nombre limite max d'applications (sans impact sur la facturation)
A tester sur une autre PR:
Puisque nous désactivons les déploiements …
=> Fix review app

back/scalingo/cron.json
Certains utilisateurs ont été réveillés par des sms tôt le matin et nous ont manifesté leurs mécontentements.  
Cette PR propose de suspendre l'envoi des sms entre 21h et 8h.
Dans le crawler qui récupère les notification mail et sms à envoyer: ne pas récupérer ceux qui concerne les sms si l'on se situe dans ce créneau horaire 20h et 8h.
Puisque ces évènements dans la table outbox restent toujours à "never-published", ils seront re-considéré au prochain passage du crawler.
=> Suspendre l'envoi de sms la nuit

back/src/adapters/primary/routers/convention/convention.e2e.test.ts, back/src/adapters/primary/routers/convention/createConventionRouter.ts, back/src/adapters/primary/routers/technical/createTechnicalRouter.ts, back/src/adapters/primary/routers/technical/technicalRouter.e2e.test.ts, back/src/domain/convention/useCases/notifications/NotifyActorThatConventionNeedsModifications.ts, back/src/domain/convention/useCases/notifications/NotifyActorThatConventionNeedsModifications.unit.test.ts, shared/src/routes/technicalRoutes.ts
Lorsque l'on demande un renouvellement de lien magique, on transmet dans le token le role du demandeur + hash du receveur. Cela pose problème lorsque l'on reçoit la demande de renouvellement dans l'api car
=> Fix renouvellement de lien magique

back/src/adapters/primary/routers/agencies/agencies.e2e.test.ts, back/src/adapters/secondary/InMemoryAgencyRepository.ts, back/src/adapters/secondary/pg/repositories/PgAgencyRepository.integration.test.ts, back/src/adapters/secondary/pg/repositories/PgAgencyRepository.ts, back/src/adapters/secondary/pg/repositories/PgConventionQueries.integration.test.ts, back/src/adapters/secondary/pg/repositories/PgInclusionConnectedUserRepository.integration.test.ts, back/src/domain/convention/entities/Agency.ts, back/src/domain/convention/ports/AgencyRepository.ts, back/src/domain/convention/useCases/agencies/AddAgency.ts, back/src/domain/convention/useCases/agencies/AddAgency.unit.test.ts, back/src/domain/convention/useCases/agencies/UpdateAgency.ts, back/src/domain/convention/useCases/agencies/UpdateAgency.unit.test.ts, back/src/domain/convention/useCases/agencies/UpdateAgencyStatus.ts, back/src/domain/convention/useCases/agencies/UpdateAgencyStatus.unit.test.ts, front/src/app/components/forms/agency/AddAgencyForm.tsx, front/src/core-logic/adapters/AgencyGateway/HttpAgencyGateway.ts, shared/src/routes/agencyRoutes.ts
Refuser la création ou mise à jour d'une agence qui aurait le **même type + adresse** qu'une agence **active** déjà existante en DB.
Sur la page de création d'agence /ajouter-prescripteur:
1. créer une agence ayant le même type + même adresse qu'une agence active existante en DB
2. constater que la création d'agence est refusée
Sur la page de modification d'agence /admin/agencies:
1. modifier une agence en reprenant le type + adresse d'une autre agence active existante en DB
2. constater que la création d'agence est refusée
=> Empêcher la création/mise à jour de doublon d'agences

.github/workflows/review-app-creation.yml, .github/workflows/review-app-deploy.yml, .github/workflows/review-app-destroy.yml
Cette PR permet de:
- trigger la pipeline lorsque le status de la PR change à "Ready for review" (plus besoin de la trigger manuellement)
- supprimer les review app front + back liés à PR lors de la clôture de celle-ci
Vérifier après merge de cette PR que le job de suppression des RA est bien déclenché.
=> Supprimer les review apps à sa fermeture/merge

back/src/adapters/secondary/InMemoryConventionPoleEmploiAdvisorRepository.ts, back/src/adapters/secondary/PeConnectGateway/peConnectApi.error.ts, back/src/adapters/secondary/PeConnectGateway/peConnectApi.schema.ts, back/src/adapters/secondary/notificationGateway/BrevoNotificationGateway.unit.test.ts, back/src/domain/peConnect/useCases/NotifyPoleEmploiUserAdvisorOnConventionFullySigned.unit.test.ts, front/src/app/components/InitiateConventionSection.tsx, front/src/app/components/forms/agency/AgencyFormCommonFields.tsx, front/src/app/components/forms/commons/AgencySelector.tsx, front/src/app/contents/error/textSetup.tsx, front/src/app/contents/home/content.ts, front/src/app/contents/standard/politique-de-confidentialite.ts, front/src/app/pages/agencyDashboard/MarkPartnersErroredConventionAsHandledFormSection.tsx, front/src/app/pages/convention/ConventionDocumentPage.tsx, front/src/app/pages/search/SearchResultPage.tsx, libs/html-templates/src/components/email/footer.ts, libs/react-design-system/src/immersionFacile/components/pe-connect-button/PeConnectButton.tsx, libs/react-design-system/src/immersionFacile/components/section-accordion/SectionAccordion.tsx, libs/react-design-system/src/immersionFacile/components/section-text-embed/SectionTextEmbed.tsx, shared/src/agency/agency.dto.ts, shared/src/email/emailTemplatesByName.ts
- Pôle Emploi Connect a gardé le même nom
=> Renommer Pôle emploi par France Travail

back/scalingo/cron.json
Actuellement on souhaite envoyer des relances bénéficiaires 1 jour avant la fin des conventions et aux entreprise 1 jour après la fin des convention.
Or, lorsque le cron démarre sa tâche à 23h49, il peut l'avoir finit à 23h57 hier et 00:02 aujourd'hui.
Mais l'heure de fin des conventions étant à 00:00, et se trouvant entre 23h57 et 00:02, elles ne seront pas traitées.
=> Mis à jour heure de lancement des crons

back/src/adapters/primary/config/createUseCases.ts, back/src/adapters/primary/routers/establishment/createEstablishmentRouter.ts, back/src/adapters/primary/routers/establishment/unregisterEstablishmentLead.e2e.test.ts, back/src/domain/offer/useCases/MarkEstablishmentLeadAsRegistrationRejected.ts, back/src/domain/offer/useCases/MarkEstablishmentLeadAsRegistrationRejected.unit.test.ts, shared/src/routes/establishementRoutes.ts
Ajout d'une route `/establishment-lead/unregister` pour se désabonner des mails de relance pour devenir entreprise accueillante.
=> Désabonnement relance entreprise pour devenir accueillante (partie 3)

.github/workflows/review-app-deploy.yml
Le premier déploiement des review-apps est systématiquement en erreur car on récupère la variable `$SCALINGO_POSTGRESQL_URL` depuis Scalingo.
Or cette variable n'existe que lorsque Postgresql est prêt.
Puisque le premier run de la pipeline créé la review app et son environnement, Postgresql n'est pas prêt à ce moment.
Cette PR évite de toujours avoir une ❌ au premier run de la pipeline 🥳 
Vu que le déploiement de la review-app n'est pas requis pour merger la PR, j'ai mis un temps d'attente un peu long de 60s (peut-être à réajuster).
=> review app: ajouter un temps d'attente dans la pipeline avant de trigger le déploiements des review app

back/src/adapters/secondary/pg/repositories/PgSearchMadeRepository.integration.test.ts, back/src/adapters/secondary/pg/repositories/PgSearchMadeRepository.ts
Nous avons beaucoup eu l'erreur "searches_made__appellation_code_unicity" aujourd'hui.
Cela est dû au paramètres `appellationCodes` fournit en entrée de la route qui contient des doublons.
La solution proposée ici est de filtrer ces doublons avant l'insertion pour ne plus enfreindre la contrainte db `searches_made__appellation_code_unicity`.
Closes #1266
=> Fix erreur en prod searches_made__appellation_code_unicity

.github/workflows/review-app-deploy.yml, .github/workflows/review-app-destroy.yml, .github/workflows/review-app.yml
Nos review apps ne sont pas supprimés à la cloture de la PR. Elles s'accumulent et on atteint le nombre maximum d'applications sur Scalingo pour le compte du gip, empêchant aussi la création de nouvelles review-app pour les autres équipes.
Les étapes pour reproduire le bug:
- mise à jour de la PR: cela va trigger du workflow de création de review-app 
- sans attendre la fin du workflow de création de review-app, merger/fermer la PR: cela va trigger le workflow de suppression de review-app
- résultat: le workflow de suppression de review-app terminera avant le workflow de création de review-app
Utiliser la fonctionnalité de `concurrency` pour interrompre le workflow de création de review-app s'il a été précédemment déclenché.
=> Fix suppression des review-app

back/scalingo/cron.json, back/src/domains/convention/adapters/pole-emploi-gateway/PoleEmploiRoutes.ts
Le POST à l'api PE peut nous renvoyer une 201: cette PR ajoute cette possibilité dans le schéma attendu.
Lors d'un échec d'envoi PE, il n'y a pas d'ajout à la table `conventions_to_sync_with_pe`.  
Or si l'échec était ajouté à cette table, le cron `trigger-resync-old-conventions-to-pe` aurait quotidiennement tenté de rejouer l'envoi à PE.
Est-ce que l'on voudrait avoir ce comportement ?
Si oui, il nous suffirait de supprimer l'usage de la variable `resyncMode` dans le usecase `BroadcastToPoleEmploiOnConventionUpdates`.
=> Accepter les HTTP 201 de Pole emploi

back/src/config/pg/kysely/model/database.ts, back/src/domains/core/events/adapters/EventCrawlerImplementations.ts, back/src/domains/core/events/adapters/InMemoryOutboxQueries.ts, back/src/domains/core/events/adapters/InMemoryOutboxRepository.ts, back/src/domains/core/events/adapters/PgOutboxQueries.crawling.integration.test.ts, back/src/domains/core/events/adapters/PgOutboxQueries.ts, back/src/domains/core/events/adapters/PgOutboxRepository.integration.test.ts, back/src/domains/core/events/adapters/PgOutboxRepository.ts, back/src/domains/core/events/ports/OutboxQueries.ts, back/src/domains/core/events/ports/OutboxRepository.ts
Il arrive que notre crawler d'évènements "freeze" et s'arrête de traiter les évènements.
La cause est toujours en cours d'investigation.
Lorsque le crawler freeze, le fix actuel est de manuellement le container depuis Scalingo et le crawler repart.
Nous aimerions être notifier dès que le crawler freeze, c'est-à-dire quand le jombre d'éléments dans la table outbox dépasse 1500.
=> Notifier Discord si plus de 1500 outbox never-published

back/src/config/pg/kysely/model/database.ts, back/src/domains/core/events/adapters/EventCrawlerImplementations.ts, back/src/domains/core/events/adapters/InMemoryOutboxRepository.ts, back/src/domains/core/events/adapters/PgOutboxRepository.integration.test.ts, back/src/domains/core/events/adapters/PgOutboxRepository.ts, back/src/domains/core/events/ports/OutboxRepository.ts
Il arrive que notre crawler d'évènements "freeze" et s'arrête de traiter les évènements.
La cause est toujours en cours d'investigation.
Lorsque le crawler freeze, les outbox qui étaient en cours de traitement sont au status `in-process` et leur nombre devrait augmenter et $etre plus grand que la taille de batch traité (300).
A ce moment, nous voudrions être notifier de cet état anormal sur Discord.
Cette PR fait suite à https://github.com/gip-inclusion/immersion-facile/pull/1334
=> Notifier Discord si trop d'outbox en in-process

.github/workflows/review-app-destroy.yml, .github/workflows/review-app.yml
Nous avons deux PR: 
- la PR A où la pipeline de CI est en cours
- la PR B qui vient d'être mise à jour et la CI va démarrer
- la PR A voit sa pipeline s'annuler car la PR B a une priorité plus importante
=> Fix annulation de la pipeline d'une autre PR

.github/workflows/deploy-to-scalingo.yml, back/src/config/pg/migrations/1709888015455_update-establishment-view-naf-code.ts
Discussion Discord: https://discord.com/channels/864451835553513474/1214229953407615026/1215434349327941673
Dans cette PR on remplace dans la création de la view_establishments:
```
e.naf_code::text, '(dd)(dd)(w)'::text, '\1.\2'::text 
```
par 
```
e.naf_code::text, '(\d{2})(\d{2}).*'::text, '\1.\2'::text 
```
Pour modifier la vue view_establishments, il faut drop et recréer `view_establishments_with_aggregated_offers` et `view_establishments_with_flatten_offers`car elles dépendent de `view_establishments`.
=> Mise à jour de la vue DB view_establishments

back/src/scripts/triggerEstablishmentLeadReminders.ts
Nos logs de cron sur les relance d'entreprises accueillantes s'affichent une lettre par ligne.
Par exemple:
```
First reminder:
T
o
t
a
l
o
f
[...]
```
=> Fix affichage des logs de cron

back/src/domains/convention/adapters/pole-emploi-gateway/HttpPoleEmploiGateway.ts
Nous envoyons des conventions à PE.
Lorsque des erreurs surviennent dans ce process, nous les loggons dans une table: `saved_errors`.
Problème: certains échecs d'envoi n'y sont pas et nous n'avons pas d'autres moyens d'identifier les conventions qui n'ont pas pu être envoyées à PE
Plus d'infos: https://discord.com/channels/864451835553513474/1216699975476707379
Ajouter toutes les erreurs qui peuvent survenir durant le process d'envoi à PE dans la table `saved_errors`.
=> Fix: garder une trace de tous les échecs d'envoi de conventions à PE

back/src/domains/convention/adapters/pole-emploi-gateway/HttpPoleEmploiGateway.manual.test.ts, back/src/domains/convention/adapters/pole-emploi-gateway/HttpPoleEmploiGateway.ts, back/src/domains/convention/adapters/pole-emploi-gateway/InMemoryPoleEmploiGateway.ts, back/src/domains/convention/use-cases/broadcast/BroadcastToPoleEmploiOnConventionUpdates.unit.test.ts
Lié à https://github.com/gip-inclusion/immersion-facile/issues/1387
Nous avons des tiemout axios lors de nos envois de convention à PE.
Dans ce cas, le usecase devrait se rejouer car il tomberait en erreur, ce que prouve notre test unitaire et intégration dans cette PR, mais ce n'est pas le cas en réalité.
Pour le moment nous mettons en place des notifications pour investigations DB aux prochaines occurences.
=> Ajouts de notifications Discord si timeout axios lors de l'envoi des conventions à PE

back/src/domains/convention/use-cases/UpdateConventionStatus.testHelpers.ts, back/src/domains/core/events/adapters/EventCrawlerImplementations.ts, back/src/domains/core/events/adapters/InMemoryOutboxQueries.ts, back/src/domains/core/events/adapters/PgOutboxQueries.crawling.integration.test.ts, back/src/domains/core/events/adapters/PgOutboxQueries.ts, back/src/domains/core/events/ports/OutboxQueries.ts
Actuellement, lorsque le crawler récupère tous les outbox à publier, il fait une jointure entre la table outbox et la table outbox_publications ordonné par publishedAt.
Le champ publishedAt que pour les outbox to-republished, ce qui fait que le crawler traitera en priorité les events à "re-published".
Ensuite il n'y a pas d'ordre défini pour traiter les never-published.
On suppose que ce sont toujours les derniers arrivés dans la table qui sont alors traités.
Pour corriger cela, on utilise le orderBy sur occurredAt plutôt que publishedAt.
=> TECH récupérer les évènements outbox triés par occurredAt plutôt que publishedAt

.github/workflows/deploy-to-scalingo.yml
L'envoi des notifications de déploiement à Discord échoue lorsque le contenu contient des backticks et des double quotes
Remplacer les backticks, quotes et double quotes par des apostrophes.
=> TECH Fix envoi des notifications sur discord

back/src/config/pg/migrations/1712236423427_update-form-establishments-business-contact.ts, back/src/config/pg/migrations/1712238124292_update-form-establishments-profession.ts
Dans la table form_establishments, nous avons des données qui ne sont pas uniformes pour les colonnes professions et businessContact.
Cette différence casse nos schémas Zod lorsque nous requêtons la table form_establishments.
| Colonne | Ancien schéma      | Nouveau schéma |
| ----------- | ----------- | ----------- |
| professions | [{"description": "Jardinier / Jardinière", "romeCodeMetier": "A1203", "romeCodeAppellation": "16067"}]      | [{"romeCode": "G1601", "romeLabel": "Management du personnel de cuisine", "appellationCode": "12110", "appellationLabel": "Chef de cuisine"}] |
| businessContact | {"job": "testeur", "email": "nathaliereyre@aol.com", "phone": "5656767", "lastName": "Reyre", "firstName": "Nath",  "contactMethod": "EMAIL"}   | {"job": "testeur", "email": …
=> TECH Aligner le schéma DB des colonnes businessContact et professions de la table formEstablishments

back/src/domains/convention/use-cases/GetConvention.ts, back/src/domains/convention/use-cases/GetConvention.unit.test.ts, back/src/domains/convention/use-cases/RenewConventionMagicLink.ts, back/src/utils/convention.ts
Lorsque qu'un utilisateur demande à changer le statut d'une convention, actuellement nous ne nous basons que sur le `role` fournit dans le token jwt.
Ce rôle peut ne plus être d'actualité (si le mail de l'agence rattachée à la convention a changé par exemple).
Vérifier que le mail a toujours ce role
Closes #1471
=> #1471 - Vérifier que le mail utilisé lors d'une requete de convention a toujours les droits valides

shared/src/convention/convention.dto.ts
Impossible de valider une convention: pas d'appel api après clic sur le bouton "valider" d'un lien magique
1. Avoir une agence à double validation
2. Créer une convention liée à cette agence
3. Aller jusqu'à la validation valideur et essayer de valider
4. Constater que rien ne se passe
=> Fix pouvoir valider une convention

back/src/domains/convention/use-cases/GetConvention.ts, back/src/domains/convention/use-cases/GetConvention.unit.test.ts, back/src/domains/convention/use-cases/RenewConventionMagicLink.ts, back/src/domains/core/authentication/inclusion-connect/adapters/InMemoryInclusionConnectedUserRepository.ts, back/src/domains/core/authentication/inclusion-connect/adapters/PgInclusionConnectedUserRepository.integration.test.ts, back/src/domains/core/authentication/inclusion-connect/adapters/PgInclusionConnectedUserRepository.ts, back/src/domains/core/dashboard/port/InclusionConnectedUserRepository.ts, back/src/utils/convention.ts
Un utilisateur qui a un compte inclusion connect mais clique sur un lien magique avec un token ConventionDomainPayload n'arrive plus à accéder à la convention
Dans la PR #1489 on vérifie que le hash de l'email de l'agence dans le token du lien magique correspond bien à un hash de mail toujours utilisé chez nous.
Or pour un conseiller ou validateur, les mails utilisés pour la vérification sont ceux renseignés dans la table agencies.
Nous n'avons pas tenu compte qu'un utilisateur peux aussi accéder à une convention via token ConventionDomainPayload mais avec son email d'utilisateur inclusion connecté.
Dans cette PR, on vérifie que si l'utilisateur est un conseiller ou valideur, alors il faut aussi vérifier s'il a un rôle IC conseiller ou valideur pour l'agence de cette convention.
=> FIX - accès à une convention via lien magique si l'utilisateur a aussi un compte inclusion connect

back/src/config/pg/migrations/1713182188376_remove-duplicated-contact-in-establishments-contact.ts, back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts, back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts, back/src/domains/establishment/helpers/EstablishmentBuilders.ts
- stop to update creation date when updating establishment aggregate
- add migration to remove duplicated contacts in establishments contact
=> #1502 - Fix suppression des contacts en doublon pour un établissement

back/src/domains/convention/use-cases/UpdateConventionStatus.testHelpers.ts, back/src/domains/convention/use-cases/UpdateConventionStatus.unit.test.ts
Cette PR est une proposition de refacto du fichier updateConventionStatus.testHelpers.ts, avec les modifications suivantes:
=> TECH refacto updateConventionStatus.testHelpers.ts

front/src/app/components/forms/convention/sections/establishment/EstablishmentBusinessFields.tsx
- Ajouter un lien vers l'annuaire des entreprises sur le champ siret du form de convention
- Fix ne pas afficher d'erreur sur le siret manquant si on vient d'arriver sur le formulaire
=> #1579 - Ajouter un lien vers l'annuaire des entreprises sur le champ siret du form de convention

shared/src/convention/ConventionDto.unit.test.ts, shared/src/convention/convention.dto.ts, shared/src/convention/convention.schema.ts
Sur le formulaire deb convention, l'utilisateur peut affecter une date de naissance incohérente au bénéficiaire. On constate en prod de dates de naissance "1674-06-18", "1881-01-01", "0075-09-28", etc.
Bloquer les soumissions de bénéficiaire ayant plus de 120 ans:
En prod, nous avons actuellement 17 conventions à venir avec des bénéficiaires à année de naissance < 1900.
```sql
SELECT conventions.status, actors.extra_fields, conventions.created_at, conventions.date_start FROM conventions
LEFT JOIN actors on conventions.beneficiary_id = actors.id
WHERE (actors.extra_fields ->> 'birthdate')::date < '1904-04-26' and conventions.date_start > '2024-04-26' and conventions.status != 'REJECTED';
```
Certaines de ces conventions sont même validées au statut "ACCEPTED_BY_VALIDATOR".
Qu'en fait-on ?
=> #1388 - Bloquer les créations de conventions avec des dates de naissances qui font des ages > 120 ans

back/src/domains/convention/adapters/PgConventionRepository.integration.test.ts, back/src/domains/convention/use-cases/UpdateConventionStatus.ts, front/src/app/pages/convention/ConventionDocumentPage.tsx, shared/src/convention/ConventionDtoBuilder.ts
Actuellement en prod sans la présente PR, on retrouve déjà le conseiller en DB. Les précédents dev ont fait le taf pour conserver le conseiller.
=> #1472 conserver le nom du conseiller

front/scalingo/nginx.conf.erb
Actuellement l'url du helpdesk est https://aide.immersion-facile.beta.gouv.fr/fr/ 
On voudrait: https://immersion-facile.beta.gouv.fr/aide/ 
Si cette PR fonctionne, next steps:
- changer toutes les URL redirigeant vers le helpdesk
- supprimer le vieux dossier /nginx ?
=> #1480 - Être redirigé sur le helpdesk sur /aide

back/src/domains/core/events/adapters/InMemoryEventBus.ts, back/src/domains/core/events/adapters/InMemoryEventBus.unit.test.ts
actuellement, quand on passe à to-republish, on ne reexcute que les suscriptions qui ont fail. Ce qui n'est pas ce qui est voulu. Cette PR fait en sorte de tout rejouer quand on met le status de l'event à to-republish
=> TECH les events to-republish relance bien toutes les souscriptions à l'evenement lié

back/src/domains/core/email-validation/adapters/EmailableEmailValidationGateway.manual.test.ts, back/src/domains/core/email-validation/adapters/EmailableEmailValidationGateway.ts, back/src/domains/core/email-validation/adapters/InMemoryEmailValidationGateway.ts, front/src/app/components/forms/commons/EmailValidationInput.tsx, front/src/app/components/forms/convention/ConventionFormFields.tsx, front/src/app/components/forms/convention/sections/beneficiary/BeneficiaryCurrentEmployerFields.tsx, front/src/app/components/forms/convention/sections/beneficiary/BeneficiaryFormSection.tsx, front/src/app/components/forms/convention/sections/beneficiary/BeneficiaryRepresentativeFields.tsx, front/src/app/components/forms/convention/sections/establishment/EstablishementTutorFields.tsx, front/src/app/components/forms/convention/sections/establishment/EstablishmentFormSection.tsx, front/src/app/components/forms/convention/sections/establishment/EstablishmentRepresentativeFields.tsx, front/src/app/components/forms/establishment/BusinessContact.tsx, front/src/app/components/forms/establishment/EstablishmentForm.tsx, front/src/app/components/forms/establishment/sections/BusinessContactSection.tsx, front/src/app/components/forms/establishment/sections/DetailsSection.tsx, front/src/app/components/immersion-offer/ContactByEmail.tsx, shared/src/email/validateEmail.dto.ts, shared/src/email/validateEmail.schema.ts
- Formulaire convention
- Formulaire entreprise
- Formulaire Mise en Relation par email
Le bouton d'envoi du form est désactivé avec un message sur les champs email comme avant mais aussi un message de rappel au niveau du bouton
Si il y a un problème pour vérifier l'email, on indique le feedback sur le champ MAIS on ne bloque pas le formulaire
=> #1542 blocker les formulaire quand emailable indique que le mail n'est pas valide

back/src/domains/convention/adapters/pole-emploi-gateway/HttpPoleEmploiGateway.ts
Lors d'un erreur d'envoi de convention à PE de type "noResponseInAxiosError", l'erreur est seulement visible dans les logs.
Pour savoir que cette convention n'a pas été envoyée à PE, il faut parser les logs 😬 
Pour éviter de parser les log, ajouter cette erreur dans la table saved_erros.
=> TECH - ajouter toutes les erreurs de synchro de conventions PE dans la table saved_errors

back/src/domains/convention/adapters/pole-emploi-gateway/HttpPoleEmploiGateway.manual.test.ts, back/src/domains/convention/adapters/pole-emploi-gateway/HttpPoleEmploiGateway.ts, back/src/domains/core/api-consumer/adapters/HttpSubscribersGateway.ts, back/src/domains/core/api-consumer/ports/SubscribersGateway.ts, back/src/domains/core/saved-errors/adapters/PgSavedErrorRepository.integration.test.ts, back/src/domains/core/saved-errors/adapters/PgSavedErrorRepository.ts
Il manque le renommage de la prop `response` par `error` dans le JSONB de la table savedError en base pour les records existants mais c'est pas indispensable pour le pilotage des erreurs de synchro et les tableaux de pilotage
=> FIX sauvegarder les erreurs au lieu des AxiosError ou AxiosResponse dans savedError afin d'éviter les erreurs circulaires

back/src/config/pg/migrations/1717072048544_rename-saved-errors-message-prop.ts, back/src/domains/core/saved-errors/adapters/PgSavedErrorRepository.ts, back/src/scripts/seed.ts
L'ancienne sérialisation quand on avait une Error stockait `{}` dans la base au lieu d'indiquer le détail.
Les AxiosError ne sont pas impacté car AxiosError a sa propre fonction de sérialisation.
=> Tech: renommer la propriété response en error dans saved errors et fix de la serialization error dans le repo

front/src/app/pages/convention/ConventionDocumentPage.tsx
Le générateur PDF nous renvoie une timeout (après 2,5 secondes) sans avoir reçu d'événement load de son instance Puppeteer. L'idée est d'alléger les ressources inutiles, tout en conservant le rendu, pour qu'il évite de tomber en timeout. 
Donc déjà, supprimer les balises script, qui ne sont pas très utiles dans un pdf.
=> #1766 - suppression des balises script du contenu html envoyé au générateur pdf

front/src/app/components/forms/convention/sections/establishment/EstablishmentBusinessFields.tsx
C'est vraiment en mode hotfix : on réalimente le siret dans redux (vu que le form peut utiliser cette donnée dans certains cas). En faisant ça, je ne reproduis plus le souci rencontré (et ça fonctionne bien pour le partage).
=> #1780 - Fix l'update du siret (convention form)

back/src/domains/core/sirene/adapters/AnnuaireDesEntreprisesSiretGateway.ts, back/src/domains/core/sirene/adapters/AnnuaireDesEntreprisesSiretGateway.unit.test.ts
Sur le formulaire de création de convention, la dénomination sociale ne se rempli pas pour ce siret 57578002800016.
Cela est dû au fait que l'annuaire retourne une string " " pour le nom_commercial.
1. Aller sur "remplir une demande de convention"
2. Dans la partie "3. Coordonnées de l'entreprise", saisir le siret: 57578002800016
3. Constater que la raison sociale de l'établissement ne se pré rempli pas.
=> TECH - fix autocompletion de la raison sociale sur le formualire de création d'une convention

back/src/domains/convention/use-cases/UpdateConventionStatus.testHelpers.ts, back/src/domains/convention/use-cases/UpdateConventionStatus.ts, back/src/domains/convention/use-cases/UpdateConventionStatus.unit.test.ts
Sur la page de convention, il y a bien un bouton pour valider la convention mais une erreur survient au clic:
=> Fix - Valider une convention en étant admin mais aussi validator

back/src/config/bootstrap/createUseCases.ts, back/src/domains/convention/use-cases/CreateAssessment.ts, back/src/domains/convention/use-cases/CreateAssessment.unit.test.ts, back/src/domains/core/UseCase.ts, back/src/domains/core/api-consumer/use-cases/ListActiveSubscriptions.ts, back/src/domains/core/api-consumer/use-cases/ListActiveSubscriptions.unit.test.ts
Voilà un POC de proposition d'une fonction `createTransactionalUseCase`, qui pourrait remplacer (mais aussi cohabiter) la classe `TransactionnalUseCase`. Elle présente les aventantages suivant :
- pas besoin de retyper les paramêtres de la methode `execute` , qui dans le cas de la classe sont fournis 2 fois (une fois en générique de la classe, et une fois dans la methode execute).
- pas besoin d'explicitement écrire une methode execute :  on écrit un call back directement.
- le type du JwtPayload (nommé UserIdentity dans ce cas), est strict au niveau typage : on ne peut pas oublier de le fournir s'il est défini dans la fonction.
Je suis preneur de vos avis. J'ai fait 2 use cases d'exemple pour qu'on se rende compte de l'intérêt
=> TECH POC création d'un helper de creation de use case : `createTransactionnalUseCase` 

front/src/app/components/forms/convention/ConventionFormWrapper.tsx
Problème: Lorsque le lien magique est périmé, la page de formulaire de convention s'affiche quand même alors que l'on doit demander à l'utilisateur de renouveler son lien magique.
=> #1822 - fix demande de renouvellement de modification de convention

front/public/.well-known/security.txt
I added `security.txt` file according to RFC9116 and linked directly to the PDI security policy.
It should server the file at `/.well-known/security.txt`
=> doc: added security.txt

back/src/domains/core/dashboard/port/InclusionConnectedUserRepository.ts, back/src/domains/inclusion-connected-users/use-cases/GetInclusionConnectedUsers.ts, back/src/domains/inclusion-connected-users/use-cases/GetInclusionConnectedUsers.unit.test.ts, front/src/app/components/agency/AgencyAdminAutocomplete.tsx, front/src/app/components/agency/AgencyUsers.tsx, front/src/app/components/agency/EditAgency.tsx, front/src/app/components/agency/RegisterUsersToAgencies.tsx, front/src/app/components/forms/agency/EditAgencyForm.tsx, front/src/core-logic/adapters/AdminGateway/HttpAdminGateway.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.epics.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.selectors.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.slice.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.test.ts, front/src/core-logic/ports/AdminGateway.ts, shared/src/admin/admin.dto.ts, shared/src/admin/admin.routes.ts, shared/src/admin/admin.schema.ts, shared/src/domElementIds.ts, shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.dto.ts, shared/src/inclusionConnectedAllowed/inclusionConnectedAllowed.schema.ts, shared/src/zodUtils.ts
Ajout de la liste des utilisateurs liés à une agence:
A faire dans d'autres PR:
- ~~renommer la route /admin/inclusion-connected/users car elle peut retourner des utilisateurs non inclusion connecté~~
- quand l'utilisateur n'a pas de compte inclusion connect, il n'a pas de firstname lastname: mais actuellement on sauvegarde une string vide --> changer pour un null ?
- utiliser le nouveau tableau du DSFR
=> #1797 - afficher le tableau des utilisateurs rattachés à une agence depuis la page admin

front/src/app/components/agency/AgencyAdminAutocomplete.tsx, front/src/app/components/agency/EditAgency.tsx, front/src/app/components/forms/agency/EditAgencyForm.tsx, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.epics.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.selectors.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.slice.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.test.ts
On ne peut pas accéder au formulaire d'édition d'une agence depuis la vue admin. Ce problème est aléatoire.
Ceci est dû au fait que nous utilisons le même state pour récupérer:
- les utilisateurs "toReview"
- et les utilisateurs d'une agence
Du coup, lorsque l'on veut accéder à ceux d'une agence, il se peut que l'on ne pas trouve de droits sur les utilisateurs  car on se base sur les utilisateurs "toReview" au lieu les utilisateurs d'une agence. L'accès aux "roles" d'un agencyRight null fait planter l'affichage du formulaire utilisateur.
=> TECH - fix accéder au formulaire d'édition d'une agence

front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.selectors.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.slice.ts
1. Sur la page admin > onglet agences > accéder au formulaire d'édition d'une agence
2. Accéder ensuite au formulaire d'édition d'une autre agence qui n'est pas rattaché aux mêmes utilisateurs inclusion-connecté
3. Constater cette erreur en screenshot:
=> FIX - accéder à au formulaire d'édition d'agence

back/src/domains/convention/adapters/InMemoryConventionQueries.ts, back/src/domains/convention/adapters/PgConventionQueries.integration.test.ts, back/src/domains/convention/adapters/PgConventionQueries.ts, back/src/domains/convention/ports/ConventionQueries.ts, back/src/domains/establishment/use-cases/SendBeneficiariesPdfAssessmentsEmails.ts, back/src/domains/establishment/use-cases/SendEmailsWithAssessmentCreationLink.ts
1. modification de ConventionQueries.getAllConventionsForThoseEndingThatDidntGoThrough pour filtrer sur les dates de fin de conventions
2. dans la requête qui récupère les conventions pour lesquels envoyer les demandes de bilan: ne plus tenir compte de l'heure dans la comparaison de conventions.date_end (car le script d'envoi des bilans n'est pas exécuté tous les jours à la même heure et en faisant des comparaisons en tenant compte de l'heure, on risquerait de rater des conventions)
=> TECH - préciser les dates de fin de conventions pour lesquels envoyer des bilans 

back/src/adapters/primary/routers/admin/adminRouter.e2e.test.ts, back/src/domains/inclusion-connected-users/use-cases/UpdateIcUserRoleForAgency.ts, back/src/domains/inclusion-connected-users/use-cases/UpdateIcUserRoleForAgency.unit.test.ts, front/src/core-logic/adapters/AdminGateway/HttpAdminGateway.ts, shared/src/admin/admin.routes.ts, shared/src/errors/errors.ts
Le back throw une erreur si on essaie de modifier le rôle d'un utilisateur et qu'il n'y a plus de validateur dans l'agence :
=> Fix - erreur lors de la modification du rôle d'un utilisateur dans une agence

back/src/domains/core/authentication/inclusion-connect/adapters/PgInclusionConnectedUserRepository.ts, front/src/app/components/forms/agency/EditAgencyForm.tsx, front/src/core-logic/domain/admin/agenciesAdmin/agencyAdmin.epics.ts, front/src/core-logic/domain/admin/agenciesAdmin/agencyAdmin.test.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.epics.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.slice.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.test.ts
- **quick fix to eliminate duplicates in agencyRight and establishment when fetching users**
- **refetch users on success on update agency in admin**
=> FIX - Eliminer les doublons d'agences quand on fetch les utilisateurs dans l'onglet agences page admin

back/src/domains/convention/adapters/PgConventionQueries.integration.test.ts, back/src/domains/convention/adapters/PgConventionQueries.ts
conventionQueries.getAllConventionsForThoseEndingThatDidntGoThrough met beaucoup de temps à récupérer les conventions sur lesquels envoyer les bilans de **tout le mois de juillet** (période où on a eu des loupé d'envoi de bilans).
Utiliser l'index sur notifications_email.created_at pour filtrer dessus car on sait que les mails de bilans sont envoyés à plus et moins 1 jour de la date de fin de la convention.
La nouvelle requête met ~11s à s'exécuter sur la réplica alors qu'elle mettait plus de 10 minutes quand je l'ai joué hier.
=> TECH: amélioration des perfs de la requête de récupération des conventions sur lesquels envoyer les bilans

back/src/config/pg/migrations/1722954848190_fix-notifications-and-discussions-emails.ts
La PR https://github.com/gip-inclusion/immersion-facile/pull/2027/files a introduit des backslash et des double quotes dans les mails à cause du cast `::value` dans le script de migration.
Corriger ces emails + mettre was_quarantined=false dans l'outbox
=> TECH - fix format des emails dans les tables notifications_email_recipients et discussions

shared/src/address/address.dto.ts
Il n'est pas possible de référencer une entreprise sur Saint-Barthélemy:
Ajouter Saint-Barthélemy à la liste des départements gérés dans address.dto.
J'ai changé le code département de Saint-Martin 971 -> 978
=> #2060 - pouvoir saisir une adresse sur Saint Barthélemy

back/src/domains/convention/adapters/PgConventionQueries.ts, back/src/domains/convention/adapters/pgConventionSql.ts
La requête SQL de récupération de conventions sur lesquels envoyer les bilans est trop longue (> 30s), donc elle tombe en timeout.
=> TECH - amélioration performance requête sql pour envoi de bilans

back/src/config/pg/migrations/1724233123941_add-index-on-establishment-update-date.ts, back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts
La requête qui récupère les établissements à qui envoyer un mail de demande de mise à jour de leur infos tombe en timeout.
Ajout d'un index + ajout d'un `limit 1`
=> TECH - amélioration performance de la requête sql getSiretOfEstablishmentsToSuggestUpdate

back/src/config/pg/migrations/1724854197570_delete-invalid-form-establishments.ts
L'entreprise au siret 13000548125405 a fait une demande de référencement chez nous en février mais n'est toujours pas devenue entreprise accueillante.
Une fois la demande de référencement effectuée, l'entreprise est enregistrée dans la table form_establishments.
Puis si les informations sont correctes, elle est ensuite ajoutée à la table establishments --> c'est cette étape là qui manque.
En février 2024, on a ajouté la possibilité aux enterprises de se référencer avec plusieurs adresses.
Nous avons alors fait une modification des demandes de référencement existantes (table DB form_establishments) en les liant à des adresses (dans la table establishments_locations) avec un id fictif car pas encore existant.
L'id étant fictif, on ne la trouve pas (dans la table establishments_locations), …
=> #2129 - Supprimer les demande de référencement entreprises invalides

front/src/app/components/admin/conventions/BroadcastAgainButton.tsx
Un utilisateur peut cliquer plusieurs fois d'affilé sur le bouton "Rediffuser".
Il y a bien un blocage api lorsqu'une synchronisation a été faite il y a moins de 4h, mais lorsque l'utilisateur clique plusieurs fois dans la même seconde sur le bouton "Rediffuser", les synchronisations n'ayant pas encore eu lieue (crawler) et il n'y a pas de blocage.
- fermer la modale après demande de synchro
- mettre un state sur le bouton qui le désactive après un premier clic
=> #2118 - éviter de synchroniser plusieurs conventions d'affilé

back/src/domains/establishment/use-cases/ContactEstablishment.ts, back/src/domains/establishment/use-cases/notifications/NotifyContactRequest.ts, back/src/domains/establishment/use-cases/notifications/NotifyContactRequest.unit.test.ts, front/src/app/pages/admin/EmailPreviewTab.tsx, front/src/app/pages/establishment-dashboard/EstablishmentDashboardPage.tsx, front/src/app/pages/establishment-dashboard/ManageDiscussionFormSection.tsx, front/src/app/routes/routes.ts, shared/src/email/EmailParamsByEmailType.ts, shared/src/email/emailTemplatesByName.ts
On pourra accéder directement à une discussion avec sur /tableau-de-bord-etablissement/discussions?discussionId=347a7608-eb13-424b-a06e-b99e725bd926. Si la personne n'est pas connectée, il tombera sur la solution d'authentification. 
Par contre, après connexion, on ne redirige pas vers l'url que l'utilisateur a cherché à atteindre, on redirige quoiqu'il arrive sur l'onglet conventions
=> Feature - Lien direct vers une discussion depuis le mail de MER

front/src/app/pages/convention/ConventionImmersionPage.tsx, front/src/app/routes/routeParams/convention.ts
Lorsque je clique sur un lien de partage de convention depuis un mail, je n'ai pas le bon nom et prénom affiché.
Un utilisateur au support a rencontré ce problème lorsqu'il clique sur le lien magique depuis le mail reçu (on reproduit aussi sur Brevo), mais ni l'utilisateur ni nous ne reproduisons lorsque l'on accède au lien magique depuis un navigateur.
=> #2187 - Fix ne pas utiliser les informations d'un utilisateur précédemment peConnecté

back/src/adapters/primary/routers/admin/createAdminRouter.ts, back/src/config/bootstrap/createUseCases.ts, back/src/domains/inclusion-connected-users/helpers/throwIfAgencyWontHaveEnoughCounsellorsOrValidators.ts, back/src/domains/inclusion-connected-users/use-cases/RemoveUserFromAgency.ts, back/src/domains/inclusion-connected-users/use-cases/RemoveUserFromAgency.unit.test.ts, back/src/domains/inclusion-connected-users/use-cases/UpdateUserForAgency.ts, front/src/app/components/agency/AgencyUsers.tsx, front/src/core-logic/adapters/AdminGateway/HttpAdminGateway.ts, front/src/core-logic/adapters/AdminGateway/SimulatedAdminGateway.ts, front/src/core-logic/adapters/AdminGateway/TestAdminGateway.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.epics.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.slice.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.test.ts, front/src/core-logic/domain/feedback/feedback.slice.ts, front/src/core-logic/ports/AdminGateway.ts, shared/src/admin/admin.dto.ts, shared/src/admin/admin.routes.ts, shared/src/admin/admin.schema.ts, shared/src/domElementIds.ts, shared/src/errors/errors.ts
En tant qu'admin, pouvoir supprimer un utilisateur d'une agence.
=> #1811 - ETQ admin, suppression d'un rattachement d'utilisateur sur une agence

back/src/domains/convention/adapters/PgConventionRepository.ts, back/src/domains/convention/adapters/pgConventionSql.ts, front/src/app/components/forms/convention/ConventionForm.tsx, front/src/app/components/forms/convention/ConventionFormWrapper.tsx, front/src/app/components/forms/convention/ConventionSummarySection.tsx, front/src/app/components/forms/convention/sections/beneficiary/BeneficiaryFormSection.tsx, front/src/app/contents/admin/conventionValidation.tsx, front/src/app/contents/forms/convention/formConvention.tsx, front/src/app/pages/convention/ConventionDocumentPage.tsx, front/src/app/routes/routeParams/convention.ts, shared/src/convention/ConventionDtoBuilder.ts, shared/src/convention/convention.dto.ts, shared/src/convention/convention.schema.ts, shared/src/convention/conventionRefinements.ts, shared/src/domElementIds.ts, shared/src/zodUtils.ts
Ce champ sera obligatoire à partir de la MEP de cette fonctionnalité (voir la date renseignée dans shouldValidateBeneficiaryAddressAndParse dans conventionRefinements.ts).
Après l'envoi de la convention par le bénéficiaire, l'adresse du candidat est visible dans :
- la page de validation du conseiller : 
- le récapitulatif avant signature : 
- la convention au format pdf :
=> #2023 - Ajout d'un champ adresse du candidat dans le formulaire de mini stage

back/src/domains/agency/adapters/PgAgencyRepository.integration.test.ts, back/src/domains/agency/adapters/PgAgencyRepository.ts
1. ETQ admin, lorsque j'accède au formulaire d'édition d'une agence à deux étapes de validation qui a un conseiller et un valideur
2. Je vide le champ de mails valideurs
3. Je mets le mail du conseiller en tant que valideur
4. Je vide le champ de mails conseillers
5. Je sauvegarde
Alors je constate qu'en DB je n'ai ni valideur ni conseiller pour cette agence. 
Cela engendre des problèmes de recherche d'agence depuis le formulaire de convention car on se retrouve avec une agence sans valideurs ni conseillers.
=> #2213 - FIX ETQ admin, modifier une agence en deux étapes en une seule étape et garder le conseiller en valideur

back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.ts
On passera de 800 ms à moins de 10ms:
(sur le replicat)
=> TECH - optimisation de la query de recherche dans le cas où il n y a aucun filtres fournis

front/src/app/components/forms/establishment/EstablishmentForm.tsx, front/src/app/components/forms/establishment/sections/AvailabilitySection.tsx, front/src/app/pages/establishment-dashboard/ManageEstablishmentTab.tsx, front/src/app/routes/routes.ts, playwright/tests/establishment/establishmentWorkflow.spec.ts, shared/src/domElementIds.ts, shared/src/email/emailTemplatesByName.ts
La visibilité de l'entreprise est affichée différemment selon les cas suivants : 
- création d'offre d'immersion ou fiche établissement via lien dans le mail de suggestion de maj bi-annuel ou date d'indisponibilité dépassée : 
- fiche établissement (entreprise visible) : 
- page admin (entreprise visible): 
Les cas dans lesquels l'entreprise n'est pas visible ont été testés en local.
=> #2176 - Modification de l'affichage de la visibilité de l'entreprise

front/src/app/components/admin/conventions/BroadcastAgainButton.tsx, front/src/core-logic/domain/convention/convention.epics.ts, front/src/core-logic/domain/convention/convention.selectors.ts, front/src/core-logic/domain/convention/convention.slice.ts, front/src/core-logic/domain/convention/convention.test.ts
Eviter les messages d'alertes dans la barre d'action.
Avant:
Avec cette PR:
=> #2184 - Afficher les retours de synchronisation de convention dans une modale

back/src/domains/agency/use-cases/UpdateAgencyReferingToUpdatedAgency.unit.test.ts, back/src/domains/agency/use-cases/UpdateAgencyReferringToUpdatedAgency.ts, back/src/domains/core/events/events.ts
Lorsqu'un usecase a été déclenché par l'outbox, il n'a pas de `currentUser` de défini.
Or dans le usecase `UpdateAgencyReferringToUpdatedAgency` on cherchait à accéder à l'id de ce `currentUser` qui est undefined. On obtenait finalement l'erreur:
> Cannot read properties of undefined (reading 'id')"
Définir le déclencheur comme étant le crawler quand le usecase a été déclenché par lui
=> TECH - définir le déclencheur comme étant le crawler quand le usecase a été déclenché par lui

front/src/app/components/layout/DefaultMetaContent.tsx, front/src/app/contents/meta/metaContents.ts, front/src/app/main.tsx, front/src/app/pages/search/SearchResultPage.tsx
- **added missing routes, static content**
- **handle dynamic meta using Helmet component in search pages**
=> #2295 - Ajout des meta manquantes

front/src/app/components/forms/convention/useUpdateConventionValuesInUrl.ts, front/src/app/components/forms/establishment/EstablishmentForm.tsx, front/src/app/hooks/search.hooks.ts, front/src/app/utils/url.utils.ts, front/src/app/utils/url.utils.unit.test.ts
- **always update businessName from siret, stop infinite loop on route params**
- **filterParamsForRoute params as obj**
=> Tech - params de filterParamsForRoute sous forme d'objet

back/src/adapters/primary/routers/admin/createAdminRouter.ts, back/src/domains/agency/use-cases/UpdateAgency.ts, back/src/domains/agency/use-cases/UpdateAgency.unit.test.ts, back/src/domains/agency/use-cases/UpdateAgencyReferingToUpdatedAgency.unit.test.ts, back/src/domains/agency/use-cases/UpdateAgencyReferringToUpdatedAgency.ts, back/src/domains/convention/use-cases/notifications/NotifyIcUserAgencyRightChanged.ts, back/src/domains/convention/use-cases/notifications/NotifyIcUserAgencyRightChanged.unit.test.ts, back/src/domains/core/authentication/inclusion-connect/adapters/InMemoryUserRepository.ts, back/src/domains/core/authentication/inclusion-connect/adapters/PgUserRepository.integration.test.ts, back/src/domains/core/authentication/inclusion-connect/adapters/PgUserRepository.ts, back/src/domains/core/authentication/inclusion-connect/port/UserRepository.ts, back/src/domains/core/events/events.ts, back/src/domains/core/events/subscribeToEvents.ts, back/src/domains/inclusion-connected-users/use-cases/CreateUserForAgency.unit.test.ts, back/src/domains/inclusion-connected-users/use-cases/RemoveUserFromAgency.ts, back/src/domains/inclusion-connected-users/use-cases/RemoveUserFromAgency.unit.test.ts, front/src/core-logic/adapters/AdminGateway/HttpAdminGateway.ts, front/src/core-logic/adapters/AdminGateway/SimulatedAdminGateway.ts, front/src/core-logic/adapters/AdminGateway/TestAdminGateway.ts, front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.slice.ts, front/src/core-logic/ports/AdminGateway.ts, shared/src/admin/admin.dto.ts, shared/src/admin/admin.schema.ts
Mettre à jour les mails des valideurs de la structure d'accompagnement lorsque ceux de la structure prescriptrice parente ont changé.
Pour la mise à jour des infos déjà présentes en DB, les requêtes SQL à jouer sur la prod après mep de cette PR sont dans le  ticket: https://github.com/gip-inclusion/immersion-facile/issues/2269
=> #2269 - La liste des utilisateurs des agences accompagnantes est mise à jour en fonction de l'agence prescriptrice

front/src/app/components/forms/convention/ConventionForm.tsx
=> #2308 - suppression du block warning dans le formulaire de convention (ces infos sont toujours présentes après la soumission du form)

front/src/app/components/forms/convention/sections/schedule/ScheduleSection.tsx, shared/src/errors/errors.ts
Lorsque l'on soumet une convention sur ces deux dates:
- date start: 18/10
- date end: 18/11
et que l'on convertit en objet Date, on obtient:
- Fri Oct 18 2024 02:00:00 GMT+0200 (Central European Summer Time)
- Mon Nov 18 2024 01:00:00 GMT+0100 (Central European Standard Time)
La différence de jour entre les deux dates est bien de 30 jours et non 31.
La création est alors créée alors que l'on ne le souhaite pas car elle excède pas 30 jours.
==> à noter que l'on a seulement ce soucis sur ces dates à cause du changement d'heure. Sur les autres mois de l'année, il n'y avait pas de soucis.
- éviter de convertir une Date en string puis Date à nouveau
- utiliser differenceInCalendarDays de date-fns au lieu de differenceInDays
=> #2376 - etq utilisateur je peux initier une convention de plus de 30 jours

front/src/app/contents/standard/accessibilite.ts
Mise à jour du lien de contact depuis la page d'accessibilité
https://immersion-facile.beta.gouv.fr/aide/ fonctionne, mais pas https://immersion-facile.beta.gouv.fr/aide 😢
=> Fix - Mise à jour du lien de contact depuis la page d'accessibilité

front/src/app/pages/convention/ConventionImmersionPage.tsx
=> #1854 - wording Pole Emploi devient France Travail dans la page de partage de convention

front/src/app/components/forms/commons/SchedulePicker/WeekdayPicker.tsx
Sur une création de convention du 26/10/2024 au 01/11/2024, le vendredi du WeekdayPicker est grisé et impossible de le sélectionner.
=> FIX - Pouvoir sélectionner une date à cheval sur le changement d'heure

front/src/app/components/layout/LayoutHeader.tsx
ETQ utilisateur connecté, lorsque je clique sur Mon espace > Modifier mes informations, je suis redirigé sur https://connect.inclusion.beta.gouv.fr/accounts/login/?next=/accounts/my-account/ .
Or suite au passage à ProConnect, je veux être redirigé pour modifier les infos de mon compte ProConnect et non Inclusion Connect.
Sur la production:
- si FT ProConnect activé: redirection sur https://app.moncomptepro.beta.gouv.fr/personal-information
- sinon https://connect.inclusion.beta.gouv.fr/accounts/my-account
Sur les autres environnements on reste sur Inclusion Connect (en attendant l'url de recette ProConnect):
- https://recette.connect.inclusion.beta.gouv.fr/accounts/my-account
On n'a pas encore l'url de modification des infos ProConnect pour la staging.
=> #2444 - Mis à jour du lien de la page de modification des informations du compte utilisateur

back/src/adapters/primary/routers/admin/createAdminRouter.ts, front/src/app/components/agency/AgencyTag.tsx, front/src/app/components/agency/EditAgency.tsx, front/src/app/components/forms/agency/AdminAgencyDetail.tsx, front/src/app/pages/admin/AdminTabs.tsx, front/src/app/pages/admin/AdminUserDetail.tsx, front/src/app/pages/admin/UsersTab.tsx, front/src/app/routes/InclusionConnectedPrivateRoute.tsx, front/src/app/routes/Router.tsx, front/src/app/routes/routes.ts, front/src/core-logic/adapters/AdminGateway/HttpAdminGateway.ts, front/src/core-logic/adapters/AdminGateway/SimulatedAdminGateway.ts, front/src/core-logic/adapters/AdminGateway/TestAdminGateway.ts, front/src/core-logic/domain/admin/adminPreloadedState.ts, front/src/core-logic/domain/admin/fetchUser/fetchUser.epic.ts, front/src/core-logic/domain/admin/fetchUser/fetchUser.selectors.ts, front/src/core-logic/domain/admin/fetchUser/fetchUser.slice.ts, front/src/core-logic/domain/admin/fetchUser/fetchUser.test.ts, front/src/core-logic/ports/AdminGateway.ts, front/src/core-logic/storeConfig/store.ts, libs/react-design-system/src/immersionFacile/components/tag/Tag.scss, libs/react-design-system/src/immersionFacile/components/tag/Tag.styles.ts, libs/react-design-system/src/immersionFacile/components/tag/Tag.tsx, shared/src/admin/admin.routes.ts, shared/src/admin/adminTabs.ts, shared/src/agency/agency.dto.ts
- **rework admin front routes to avoid using a params for tabs, making it easier to extend**
- **fix playwright typecheck**
- **add slug to admin routes**
- **making manage convention admin sub part of admin routes (/admin/conventions/:conventionId)**
- **add admin user detail route**
- **implement Redux logic to fetch a user as an admin + add a backend route specific for this (using an existing usecaes)**
=> #2448 - création de la page de détail d'un utilisateur (pour les super admin uniquement) - accessible depuis l'onglet admin - utilisateurs

front/src/app/components/SelectConventionFromIdForm.tsx, front/src/app/pages/admin/ConventionTab.tsx, front/src/app/pages/agency-dashboard/AgencyDashboardPage.tsx, front/src/app/pages/establishment-dashboard/EstablishmentDashboardPage.tsx
=> remise en place du bouton 'piloter la convention' pour accès rapide à une convention avec son ID

front/src/app/components/agency/AgencyTag.tsx, front/src/app/components/agency/AgencyUsers.tsx, front/src/app/components/agency/AgencyUsersTable.tsx, front/src/app/components/agency/EditAgency.tsx, front/src/app/components/forms/agency/AdminAgencyDetail.tsx, front/src/app/pages/admin/AdminUserDetail.tsx, front/src/core-logic/domain/admin/listUsers/listUsers.epics.ts
Voilà un aperçu de la nouvelle version pour les structures d'accompagnement :
Et pour les prescripteurs (une agence qui ne réfère pas à une autre) :
=> #2190 - dans la vue d'agence admin, les utilsateurs sont séparés entre structure d'accompagnement et agence parente

front/src/core-logic/domain/convention/convention.epics.ts, front/src/core-logic/domain/convention/convention.test.ts, front/src/core-logic/domain/feedback/feedback.slice.ts
Après clique sur "Rediffuser", on a ce message :
Et au bout de 10 secondes :
=> #2388 - ajout d'un delai de 10 secondes avant de pouvoir diffuser de nouveau une convention

front/src/app/components/forms/establishment/EstablishmentForm.tsx
Vérification en local:
- Création établissement en mode form à étape > exclu
- Modification établissement par lien magique en mode form à étape > exclu
- Modification établissement en mode connecté en mode form complet mais en mode tab > exclu tant qu'on a pas un approche responsable d'établissements multiple
Il reste la modification en mode Pilotage Etablissement en Admin qui navigue sur une page dédiée et nécessite un retour au menu de pilotage des établissement où on peut avoir le tableau de bord Metabase des établissements.
=> #2400 - Fix bouton de retour au pilotage des établissements uniquement en admin

front/src/app/contents/convention/conventionSummary.helpers.tsx, libs/react-design-system/src/immersionFacile/components/convention-summary/ConventionSummary.tsx
Une fois la convention validée, un flag apparaît dans l'encart "Structure du bénéficiaire" :
Ce flag devrait mentionner "Validée" plutôt que "Signée"
=> #2363 - Mise à jour du badge de l'agence sur la page de récap de convention

front/src/app/contents/convention/conventionSummary.helpers.tsx, libs/react-design-system/src/immersionFacile/components/convention-summary/ConventionSummary.scss, libs/react-design-system/src/immersionFacile/components/convention-summary/ConventionSummary.styles.ts, libs/react-design-system/src/immersionFacile/components/convention-summary/ConventionSummary.tsx, libs/react-design-system/src/immersionFacile/components/copy-button/CopyButton.tsx
Prise en compte des retours sur la page de convention:
- ne plus avoir de chevauchements entre adresse mail et numéro de téléphone pour les résolutions entre 768 et 1200 px lorsqu'une adresse est trop longue
- dans le bloc "Métier observé", remplacer "Objectif" par "Objectif de l'immersion", comme sur la maquette
- passer le mot "SIRET" en lettres capitales
- ajouter plus d'espace entre les lignes de semaines pour gagner en lisibilité
- ajouter les flags "En attente de signature" pour les parties prenantes n'ayant pas encore signé
- bloc "Information complémentaire" : ne mettre les ":" après le "Oui" que lorsque le champ de détail a été rempli
- bloc "Convention" : Sur mobile le bouton passe sous l'illustration, il devrait être aligné avec l'ID de la convention
- les textes sont en Corps …
=> #2363 - fix retours sur la page de convention

front/src/app/components/forms/convention/sections/schedule/ScheduleSection.tsx
Il n'est pas possible de valider un formulaire d'édition de convention.
Nous avons un useEffect qui met à jour la valeur des champs de début et fin de l'immersion.
Mais ce hook n'inclut pas la mise à jour de la valeur maximale du champ de date de fin.
Le formulaire est donc toujours invalide car on se retrouve alors avec date de fin > date de fin max.
=> #2586 - Fix soumission d'un formulaire de convention édité

back/src/config/pg/migrations/1732192784073_establishment-contacts-to-establishment-rights.ts
- apply default contact mode for establishments without legacy contacts
- avoid conflict of insert of contact admins with same email
=> fix migration

front/src/app/contents/convention/conventionSummary.helpers.tsx
Sur la page de récap d'une convention, le nom affiché de l'agence et la structure d'accompagnement sont inversés.
=> #2657 - Fix inversion agence et structure d'accompagnement sur l'affichage de la convention

back/src/adapters/primary/routers/agencies/createAgenciesRouter.ts, back/src/domains/inclusion-connected-users/helpers/agencyRights.helper.ts, back/src/domains/inclusion-connected-users/use-cases/UpdateUserForAgency.ts, back/src/domains/inclusion-connected-users/use-cases/UpdateUserForAgency.unit.test.ts, front/src/app/components/UserDetail.tsx, front/src/app/components/agency/AgencyUserModificationForm.tsx, front/src/app/components/agency/AgencyUsers.tsx, front/src/app/components/agency/IcUserAgenciesToReview.tsx, front/src/app/pages/MyProfile.tsx, front/src/app/pages/admin/AdminUserDetail.tsx, front/src/core-logic/adapters/AgencyGateway/HttpAgencyGateway.ts, front/src/core-logic/adapters/AgencyGateway/SimulatedAgencyGateway.ts, front/src/core-logic/adapters/AgencyGateway/TestAgencyGateway.ts, front/src/core-logic/domain/admin/fetchUser/fetchUser.slice.ts, front/src/core-logic/domain/admin/fetchUser/fetchUser.test.ts, front/src/core-logic/domain/agencies/agencies.helpers.ts, front/src/core-logic/domain/agencies/update-user-on-agency/updateUserOnAgency.epic.ts, front/src/core-logic/domain/agencies/update-user-on-agency/updateUserOnAgency.selectors.ts, front/src/core-logic/domain/agencies/update-user-on-agency/updateUserOnAgency.slice.ts, front/src/core-logic/domain/agencies/update-user-on-agency/updateUserOnAgency.test.ts, front/src/core-logic/domain/feedback/feedback.slice.ts, front/src/core-logic/domain/inclusionConnected/inclusionConnected.slice.ts, front/src/core-logic/domain/inclusionConnected/inclusionConnected.test.ts, front/src/core-logic/ports/AgencyGateway.ts, front/src/core-logic/storeConfig/store.ts, shared/src/errors/errors.ts, shared/src/routes/agencyRoutes.ts
- ETQ Admin IF, pouvoir modifier les rôles et préférences de notifications d'un utilisateur sur la page /admin/users/:idUser
- ETQ Admin d'agence, modifier les rôles et préférences de notifications d'un utilisateur sur la page /admin/users/:idUser
- ETQ utilisateur, pouvoir modifier ses préférences de notifications sur la page /mon-profil
=> #1815 - Gestion des agences de rattachement utilisateur

front/src/app/components/UserDetail.tsx, front/src/app/pages/MyProfile.tsx, front/src/app/pages/admin/AdminUserDetail.tsx, front/src/core-logic/domain/admin/fetchUser/fetchUser.slice.ts, front/src/core-logic/domain/admin/fetchUser/fetchUser.test.ts, front/src/core-logic/domain/agencies/agencies.helpers.ts, front/src/core-logic/domain/inclusionConnected/inclusionConnected.slice.ts, front/src/core-logic/domain/inclusionConnected/inclusionConnected.test.ts
1. ETQ admin IF, sur la page de détail d'un utilisateur, pouvoir modifier ses rôles dans la modale.
2. Lorsque je navigue entre les pages de modifications utilisateur, je veux voir les informations à jour
=> #1815 - Fix multiples sur #1815

shared/src/routes/formCompletion.routes.ts, shared/src/search/searchText.schema.ts, shared/src/search/searchText.unit.test.ts
Lorsque l'on saisie des caractères spéciaux dans le champ de recherche, on obtient une erreur sql:
```
durationInSeconds: 0.0021460669999942184
error: {
"error": "syntax error in tsquery: \"<toto\"",
"query": "select \"public_appellations_data\".\"ogr_appellation\", \"public_appellations_data\".\"libelle_appellation_long\", \"public_romes_data\".\"libelle_rome\", \"public_romes_data\".\"code_rome\" from \"public_appellations_data\" inner join \"public_romes_data\" on \"public_appellations_data\".\"code_rome\" = \"public_romes_data\".\"code_rome\" where ((\"libelle_appellation_long_without_special_char\" @@ to_tsquery('french', $1) and \"libelle_appellation_long_without_special_char\" ilike $2) or (\"libelle_appellation_long_without_special_char\" ilike $3 and …
```
=> #2652 - remplacer les caractères spéciaux du texte recherché par un espace

front/src/app/components/forms/commons/SchedulePicker/ComplexSchedulePicker.tsx, front/src/app/components/forms/commons/SchedulePicker/RegularSchedulePicker.tsx, front/src/app/components/forms/commons/SchedulePicker/WeekdayPicker.tsx, front/src/app/components/forms/convention/sections/schedule/ScheduleSection.tsx
Une utilisatrice en Martinique veut saisir une convention du 02/01 au 16/01, avec des horaires irrégulières.
Sur le dernier jour, le 16/01, elle ne peut pas ajouter d'horaires.
On avait constaté ce problème sur la saisie des horaires irrégulières, mais les horaires régulières avaient aussi un problème avec les changements de timezones.
=> #2764 - Fix choix de jour sur le formulaire de convention pour autres timezones

front/src/app/routes/InclusionConnectedPrivateRoute.tsx
avec un gros `as` des familles.
=> #2760 - Deconnexion possible tout de suite après connexion (suppr. du param token dans l'url)

back/src/domains/core/notifications/adapters/BrevoNotificationGateway.manual.test.ts, back/src/domains/core/notifications/adapters/BrevoNotificationGateway.ts, back/src/domains/core/notifications/adapters/InMemoryNotificationGateway.ts, back/src/domains/core/notifications/ports/NotificationGateway.ts, back/src/domains/establishment/use-cases/discussions/SendExchangeToRecipient.ts, back/src/domains/establishment/use-cases/discussions/SendExchangeToRecipient.unit.test.ts
Nous avons fréquemment cette erreur de prod `blob.arrayBuffer is not a function` lorsque nous récupérons une pièce jointe depuis Brevo. Lorsque nous avons un code de retour 200, nous assumons qu'il s'agit d'un blob et nous appellons la focntion ` blob.arrayBuffer()`. Or ce n'est pas toujours un blob.
Nous ignorons dans cette PR les pièces jointes qui ne sont pas des blobs. Ainsi, les utilisateurs reçoivent tout de même leurs mails, même sans pièce jointe.
=> TECH - supprimer les pièces jointes des emails de MER s'il ne s'agit pas d'un blob

back/src/domains/convention/adapters/PgAssessmentRepository.integration.test.ts, back/src/domains/convention/adapters/PgAssessmentRepository.ts
Les heures manquées renseignées sont parfois de 0.
Au moment de la création du dto, on veut pouvoir récupérer cette information car on ne la remontait pas si c'était 0 avant.
=> TECH - bilan: récupérer les heures manquées si l'info est présente

back/src/adapters/primary/routers/convention/convention.e2e.test.ts, back/src/adapters/primary/routers/magicLink/assessment.e2e.test.ts, back/src/domains/convention/entities/AssessmentEntity.ts, back/src/domains/convention/entities/Convention.ts, back/src/domains/convention/use-cases/CreateAssessment.ts, back/src/domains/convention/use-cases/CreateAssessment.unit.test.ts, back/src/domains/convention/use-cases/GetAssessmentByConventionId.ts, back/src/domains/convention/use-cases/GetAssessmentByConventionId.unit.test.ts, back/src/domains/convention/use-cases/GetConvention.ts, back/src/domains/convention/use-cases/GetConvention.unit.test.ts, back/src/domains/convention/use-cases/RenewConventionMagicLink.ts, back/src/domains/convention/use-cases/UpdateConventionStatus.ts, back/src/domains/convention/use-cases/notifications/NotifyAgencyThatAssessmentIsCreated.ts, back/src/domains/convention/use-cases/notifications/NotifySignatoriesThatConventionSubmittedNeedsSignatureAfterModification.ts, back/src/utils/assessment.ts, back/src/utils/convention.ts, back/src/utils/emailHash.ts, shared/src/errors/errors.ts, shared/src/tokens/jwt.utils.ts
Inclus un peu de rangement pour regrouper un bon paquet de fonctions liées au check de mail hash.
=> #2824 #2825 - ETQ conseiller ou validateur notifié, je peux créer ou vérifier l'existence du bilan à partir d'un lien magique

.github/workflows/continous-delivery.yml, .github/workflows/deploy-to-scalingo.yml
Suite au passage de Discord à Slack, j'ajoute dans cette PR les envois de notifications à Slack.
Il est possible de voir le visuel sur le canal #if-mise-en-recette sur Slack. Tous les boutons n'y sont pas fonctionnels car les liens ne sont pas corrects.
=> TECH - envoyer des notifications sur Slack depuis nos github actions

back/src/config/bootstrap/appConfig.ts, back/src/domains/core/authentication/inclusion-connect/adapters/oauth-gateway/HttpOAuthGateway.ts, back/src/domains/core/authentication/inclusion-connect/entities/OAuthIdTokenPayload.ts, back/src/domains/core/authentication/inclusion-connect/port/OAuthGateway.ts, back/src/domains/core/authentication/inclusion-connect/use-cases/AuthenticateWithInclusionCode.ts, front/src/app/routes/InclusionConnectedPrivateRoute.tsx, front/src/app/routes/routes.ts, front/src/core-logic/domain/auth/auth.epics.ts, front/src/core-logic/ports/DeviceRepository.ts, shared/src/inclusionConnect/inclusionConnect.dto.ts
Première partie de ce ticket: [#2641](https://github.com/gip-inclusion/immersion-facile/issues/2641)
Dans cette PR on récupère dans le front le siret de l'utilusateur pro connecté et on le stocke dans le le local storage.
On n'en fait rien pour l'instant. Ca viendra dans la suite de ce ticket.
=> #2641 - récupérer le siret de l'utilisateur Pro Connecté

back/src/config/helpers/handleHttpJsonResponseError.ts, back/src/config/pg/kysely/kyselyUtils.ts, back/src/domains/convention/adapters/france-travail-gateway/HttpFranceTravailGateway.ts, back/src/domains/core/authentication/ft-connect/adapters/ft-connect-gateway/HttpFtConnectGateway.ts, back/src/domains/core/authentication/inclusion-connect/use-cases/AuthenticateWithInclusionCode.ts, back/src/domains/core/events/adapters/EventCrawlerImplementations.ts, back/src/domains/core/events/adapters/InMemoryEventBus.ts, back/src/domains/establishment/adapters/PgFormEstablishmentRepository.ts, back/src/domains/establishment/use-cases/SuggestEditEstablishment.ts, back/src/scripts/handleCRONScript.ts, back/src/utils/notifyTeam.manual.test.ts, back/src/utils/notifyTeam.ts
Les notifications Slack, d'information et de succès, sont toujours envoyés au canal d'erreur.
On voudrait pouvoir distinguer le type de notification et renvoyer seulement les erreurs au canal d'erreur.
=> TECH - rediriger les notifications Slack vers le bon canal

shared/src/schedule/ScheduleUtils.ts
Le signataire ne peut pas accéder à la convention pour la signer car il obtient l’erreur: “Le mini-stage ne peut pas se dérouler un dimanche” alors que son emploi du temps est correct.
=> #2918 - fix timezone pour signature de la convention

front/src/app/components/agency/agency-dashboard/NoActiveAgencyRights.tsx, front/src/app/pages/agency-dashboard/AgencyDashboardPage.tsx
ETQ Prescripteur , je me connecte à mon espace, j'ai le visu suivant
N'afficher ce titre que sur les pages de rattachement d'agences.
=> #2941 - Fix affichage du titre sur le tableau de bord prescripteur

front/src/app/pages/convention/AssessmentDocumentPage.tsx
Fix de typo sur la page de bilan: "réaliséepar" (manque un espace)
=> #2157 - Fix typo sur la page de bilan

back/src/config/bootstrap/createGateways.ts, back/src/domains/establishment/adapters/la-bonne-boite/HttpLaBonneBoiteGateway.manual.test.ts, back/src/domains/establishment/adapters/la-bonne-boite/HttpLaBonneBoiteGateway.ts
Nous avons des erreurs 429 sur nos appels à LBB (trop de requêtes).
Pour éviter cela, nous mettons en place le cache sur ces appels.
=> TECH - Ajout de cache sur les appels LBB

front/src/app/contents/convention/conventionSummary.helpers.tsx, libs/react-design-system/src/immersionFacile/components/convention-summary/ConventionSummary.tsx, libs/react-design-system/src/immersionFacile/components/copy-button/CopyButton.tsx, libs/react-design-system/src/immersionFacile/components/copy-button/useCopyButton.ts
Remettre le bouton de copie possiblement sans label et sans bordure sur la page de récap de convention
=> #3004 - page de récap de convention: remettre les boutons de copie sans labels + sans bordures

front/src/app/components/agency/CopyAgencyId.tsx
=> #3004 - fix du bouton de copie d'id agence sur la page d'agence

back/src/adapters/primary/routers/magicLink/assessment.e2e.test.ts, back/src/config/bootstrap/createUseCases.ts, back/src/domains/convention/use-cases/CreateAssessment.ts, back/src/domains/convention/use-cases/CreateAssessment.unit.test.ts, back/src/domains/convention/use-cases/GetAssessmentByConventionId.ts, back/src/domains/convention/use-cases/GetAssessmentByConventionId.unit.test.ts, back/src/domains/convention/use-cases/notifications/NotifyAgencyThatAssessmentIsCreated.ts, back/src/domains/convention/use-cases/notifications/NotifyAgencyThatAssessmentIsCreated.unit.test.ts, back/src/domains/convention/use-cases/notifications/NotifyBeneficiaryThatAssessmentIsCreated.ts, back/src/domains/convention/use-cases/notifications/NotifyBeneficiaryThatAssessmentIsCreated.unit.test.ts, back/src/domains/core/events/subscribeToEvents.ts, back/src/utils/assessment.ts, front/src/app/pages/admin/EmailPreviewTab.tsx, shared/src/email/EmailParamsByEmailType.ts, shared/src/email/emailTemplatesByName.ts
Le bénéficiaire reçoit un mail avec un lien vers le bilan une fois que l'entreprise l'a complété.
=> #2450 - Envoyer le résultat du bilan au bénéficiaire

shared/src/convention/convention.ts
Les champs du représentant légal du bénéficiaire ne s'affiche plus lorsque le candidat a 18 ans l'année de l'immersion.
1. Sur le formulaire de convention, saisir 30/11/2007 comme date de naissance du candidat
2. Constater que les champs du représentant légal du bénéficiaire ne s'affichent pas
Utiliser `differenceInISOWeekYears` au lieu de `differenceInCalendarISOWeekYears` de date-fns, qui permet de considérer la progression dans l'année et pas juste l'année.
=> #2955 - fix affichage des champs du représentant légal du bénéficiaire

back/src/scripts/triggerUpdateEstablishmentsFromSireneApiScript.ts
On utilisait `createFetchSharedClient` où l'on définissait explicitement le content-type de la requête à `application/x-www-form-urlencoded`.
Or ce header n'est pas pris en compte lors de l'execution de fetch.
Pour débloquer la situation, nous retournons pour le moment à axios avec `createAxiosSharedClient`.
=> TECH - fix appel à l'api Insee: retour à axios

front/src/app/pages/convention/ConventionDocumentPage.tsx, shared/src/errors/errors.ts, shared/src/role/role.utils.ts
Certaines conventions ont été validées sans conseiller alors qu'elles sont rattachées à une structure d'accompagnement.
On a alors ce message d'erreur sur le document de convention:
=> #3080 - Fix: afficher un message d'erreur correct

front/src/app/components/layout/LayoutFooter.tsx, front/src/app/components/layout/LayoutHeader.tsx, front/src/app/contents/home/content.ts, shared/src/domElementIds.ts
Ça donne ça (+ un lien dans le footer) : 
=> #3047 - ajout des liens d'accès à pages.immersion-facile.beta.gouv.fr dans le footer et dans la partie prescripteur (menu et accueil)

shared/src/convention/ConventionDto.unit.test.ts, shared/src/convention/convention.dto.ts, shared/src/convention/convention.schema.ts, shared/src/convention/conventionRefinements.ts, shared/src/email/emailTemplatesByName.ts
On utilise `differenceInYears` pour calculer l'âge du candidat.
Or le calcul ne retourne pas toujours l'âge comme on s'y attendrait:
- differenceInYears(new Date("2025-04-07"), new Date("2007-04-07")) // retourne 18 -> OK
- differenceInYears(new Date("2025-03-26"), new Date("2007-03-26")) // retourne 17 -> ??
--> C'est parce que quand on crée une date avec new Date("YYYY-MM-DD"), elle est interprétée en UTC, ce qui peut entrainer des différences d'horaires
Comparer les dates au début du jour avec `startOfDay`: 
`differenceInYears(new Date("2025-04-07"), new Date("2007-04-07"))`.
Créer une convention avec ces exactes dates:
- date de naissance : 26/03/2007
- date de démarrage : 26/03/2025
=> #3112 - Fix création de convention sur une date où le bénéficiaire devient majeur le 26/03

front/src/app/components/forms/convention/ConventionForm.tsx, front/src/app/components/forms/convention/ConventionFormWrapper.tsx, front/src/app/pages/convention/ConventionImmersionPage.tsx, front/src/app/pages/convention/ConventionMiniStagePage.tsx, front/src/app/pages/convention/ConventionPageForExternals.tsx, shared/src/domElementIds.ts
On veut pouvoir distinguer dans nos trackings:
- les accès au formulaire en immersion vs mini-stage
- la création d'une modification de convention
- si c’est une création suite à un partage de convention
Les ids possibles sur le formulaire de convention seront:
Pour le mini-stage
- im-convention-mini-stage-cci-form--edit
- im-convention-mini-stage-cci-form--create-from-shared
- im-convention-mini-stage-cci-form--create-from-scratch
Pour l'immersion
- im-convention-immersion-form--edit
- im-convention-immersion-form--create-from-shared
- im-convention-immersion-form--create-from-scratch
=> #3053 - Distinguer les différents modes et types de formulaire de convention pour le tracking

front/src/app/components/agency/agency-dashboard/AgencyDashboard.tsx, front/src/app/components/agency/agency-dashboard/tabs/ConventionTabContent.tsx, front/src/app/pages/convention/ConventionImmersionPage.tsx, front/src/app/routes/routes.ts, shared/src/domElementIds.ts
- add initiate convention button in agency dashboard
- don't show shared convention page when initiated from dashboard
=> #3041 - Initier une convention pré remplie avec les infos de l'agence depuis le dashboard d'agence

back/src/domains/convention/use-cases/notifications/NotifyActorThatConventionNeedsModifications.ts
Lors d'une modification d'un mini-stage, on est sur la page d'immersion /demande-immersion.
Puisque l'on est pas sur la bonne route, l'id du form de convention est "im-convention-immersion-form--edit" au lieu de "im-convention-mini-stage-cci-form--edit".
Créer le lien magique sur la bonne route.
A noter que sur la route de demande-mini-stage, on a plus de header et footer du site IF.
=> #3053 - Fix id du formulaire de convention

back/src/config/pg/migrations/1742468849412_add-index-in-discussion-for-preformances.ts, back/src/config/pg/migrations/1742469808774_add-index-on-actors-email.ts, back/src/domains/core/authentication/inclusion-connect/adapters/PgUserRepository.ts
check de discussion existante pour un email : on passe de 230 ms à moins de 0.2 ms
Cette PR optimize les 3 spans qu'on voit dans cette trace. Qui au passage sont joué 2 fois pour cette query (une fois dans le middleware et une fois dans le usecase). On va donc gagner pratiquement 1 secondes sur toutes ces requêtes.
=> TECH - optimisations SQL 

back/src/adapters/primary/routers/magicLink/assessment.e2e.test.ts, back/src/config/pg/kysely/model/database.ts, back/src/domains/convention/adapters/PgAssessmentRepository.ts, back/src/domains/convention/entities/AssessmentEntity.ts, back/src/domains/convention/use-cases/GetAssessmentByConventionId.ts, back/src/domains/convention/use-cases/GetAssessmentByConventionId.unit.test.ts, back/src/utils/assessment.ts, front/src/app/pages/convention/AssessmentDocumentPage.tsx, front/src/core-logic/adapters/AssessmentGateway/HttpAssessmentGateway.ts, front/src/core-logic/domain/assessment/assessment.slice.ts, front/src/core-logic/ports/AssessmentGateway.ts, shared/src/assessment/assessment.dto.ts, shared/src/assessment/assessment.schema.ts, shared/src/convention/convention.routes.ts
- **handle legacy assessments**
- **fix front to handle LegacyAssessments**
Ça donne ça :
=> #3167 - ajout de la gestion des anciens format de bilan (y compris dans la page de Bilan, coté front)

shared/src/schedule/ScheduleUtils.ts
Lorsque le mini-stage commence un lundi, on a l'erreur suivante:
En résolvant ce problème, je découvre que les dates affichées ne sont pas correctes 😭 
Le mini-stage ci-dessous devrait se dérouler du 17/02 au 20/02 !
C'est peut-être lié à ce ticket de bug: https://github.com/gip-inclusion/immersion-facile/issues/3232
=> #3230 - Fix accès à la convention mini-stage

back/scalingo/cron.json
Vu que nous avons des soucis d'envoi de mails de bilan le jeudi en raison de la quantité de conventions concernées, nous pouvons mettre le cron en matinée pour prévoir de le rejouer en fin d'aprem si jamais il a planté.
Un autre ticket https://github.com/gip-inclusion/immersion-facile/issues/3272 est prévu pour corriger le problème.
=> TECH - Modification de l'heure du cron d'envoi de lien de formulaire bilan

back/src/domains/convention/adapters/PgConventionQueries.integration.test.ts, back/src/domains/convention/use-cases/RenewConventionMagicLink.ts, back/src/domains/convention/use-cases/SendSignatureLink.ts, back/src/domains/convention/use-cases/notifications/NotifyActorThatConventionNeedsModifications.ts, back/src/domains/convention/use-cases/notifications/NotifyAllActorsOfFinalConventionValidation.ts, back/src/domains/convention/use-cases/notifications/NotifyAllActorsOfFinalConventionValidation.unit.test.ts, back/src/domains/convention/use-cases/notifications/NotifyAllActorsThatConventionTransferred.ts, back/src/domains/convention/use-cases/notifications/NotifyConventionReminder.ts, back/src/domains/convention/use-cases/notifications/NotifyNewConventionNeedsReview.ts, back/src/domains/convention/use-cases/notifications/NotifySignatoriesThatConventionSubmittedNeedsSignature.ts, back/src/domains/convention/use-cases/notifications/NotifySignatoriesThatConventionSubmittedNeedsSignatureAfterModification.ts, back/src/domains/convention/use-cases/notifications/NotifyToAgencyConventionSubmitted.ts, back/src/domains/core/notifications/adapters/InMemoryNotificationRepository.ts, back/src/domains/core/short-link/ShortLink.ts, back/src/utils/assessment.ts, front/src/app/components/admin/conventions/ConventionManageActions.tsx, front/src/app/pages/admin/EmailPreviewTab.tsx, front/src/app/pages/admin/NotificationsTab.tsx, front/src/app/pages/immersion-assessment/AssessmentPage.tsx, shared/src/email/EmailParamsByEmailType.ts, shared/src/email/emailTemplatesByName.ts, shared/src/role/role.dto.ts, shared/src/role/role.utils.ts
- modify get assessment usecase to accept connected user jwt
- modify create assessment usecase to accept connected user jwt
- modify assessment pages to workconnected users
- add buttons to access and fullfill assessment in convention manage action page
- fix wrong message on fetch convention erro in assessment document page
- fix assessment pages with magic link
- do not allow back-office admin to fullfill assessment
- rename prepare magic short link
- add link to assessment page to convention tutor in convention final validation email
=> #3129 -  Ajout du lien pour déclarer un abandon dans le mail de confirmation final du tuteur de l'immersion

back/src/config/bootstrap/createAppDependencies.ts, back/src/config/bootstrap/createEventCrawler.ts, back/src/config/pg/migrations/1745336151992_fix-outbox-status-type.ts, back/src/config/pg/migrations/1745336151992_mark-old-event-as-failed.ts, back/src/domains/core/events/adapters/EventCrawlerImplementations.ts, back/src/domains/core/events/adapters/InMemoryOutboxRepository.ts, back/src/domains/core/events/adapters/PgOutboxRepository.integration.test.ts, back/src/domains/core/events/adapters/PgOutboxRepository.ts, back/src/domains/core/events/ports/OutboxRepository.ts
Lorsqu'une MEP est déclenchée, le crawler redémarre et les évènements outbox qui étaient au statut "in-process" le restent et ne sont plus traitées (donc pas d'envois de mails).
Mettre les évènements de plus de 2h au statut "to-republish"
Les évènements outbox de plus de 1j qui sont en statut "in-process" seront marqué en "failed-too-many-times".
=> #3264 - Traiter les évènements bloqués après une MEP

back/src/config/pg/migrations/1693581341030_add-status-column-to-outbox.ts, back/src/config/pg/migrations/1708954107350_add-in-process-to-type-event-status.ts, back/src/config/pg/migrations/1745336151992_fix-outbox-status-type.ts
Tous les fichiers de migration sont joués dans une même transaction.
Mais `addTypeValue` (type utilisé pour status de outbox) est joué dans une transaction à part: donc il n'est pas possible de faire un update sur le status. On a ce problème lorsque l'on joue tous les fichiers de migration à la suite.
=> TECH - fix migrations

back/src/domains/convention/adapters/PgConventionQueries.integration.test.ts, back/src/domains/convention/adapters/PgConventionQueries.ts, back/src/scripts/handleCRONScript.ts, back/src/utils/notifyTeam.ts
- si échec du cron -> notification envoyée dans #if-prod-errors ET #if-prod-notifications
- amélioration des perfs de la requête qui récupère
- les conventions qui finissent dans +/-1 jour mais qui n'ont pas encore reçu de bilan
- et les conventions qui ont terminés mais ont été validés hier ou aujourd'hui
Ce qui posait problème avec cette requête trop longue :
- on avait parfois des timeout
- difficile de relancer la requête en journée quand la DB est déjà bien sollicitée
Dans cette PR je ne tiens compte **que de l'optimisation des clauses WHERE et de jointures de la requête après** `createConventionQueryBuilder`. Il pourrait aussi être recommandé de ne pas utiliser `createConventionQueryBuilder` car elle remonterait des colonnes qui ne nous sont pas nécessaires.
En sql, l'ancienne …
=> #3272 - Fix timeout sur la récupération des conventions pour lesquelles envoyer un bilan

back/src/adapters/primary/routers/DtoAndSchemas/v2/input/GetConventionByFiltersQueriesV2.schema.ts, back/src/adapters/primary/routers/apiKeyAuthRouter/conventionPublicV2.e2e.test.ts
Maintenant que le on reçoit des paramètre inconnu, l'API renvera ceci :
```
{
"status": 400,
"message": "Shared-route schema 'queryParamsSchema' was not respected in adapter 'express'.\nRoute: GET /v2/conventions",
"issues": [" : Unrecognized key(s) in object: 'fieldWithTypo123'"]
}
```
=> TECH - faire en sorte de renvoyer un message explicit lorsque l'API de listing de conventions est appelée avec de mauvais paramètres

front/src/app/contents/admin/types.ts, shared/src/convention/ConventionDtoBuilder.ts, shared/src/convention/convention.dto.ts, shared/src/convention/convention.schema.ts, shared/src/convention/convention.ts
On avait appliqué le type `personNameSchema` à la fois:
- à agencyReferent (nom et prénom du conseiller dans le form de convention)
- à agencyCounsellor (nom et prénom du conseiller qui pré-valide la convention)
- à agencyValidator (nom et prénom du valideur qui valide la convention)
Or, pour agencyCounsellor et agencyValidator nous avons déjà en DB des données qui ressemble à:
- "lastname": "firstname.lastname@francetravail.fr", "firstname": "firstname.lastname@francetravail.fr"
- "lastname": "Avenir Actif", "firstname": "Conseil St Brieuc / Plérin"
Problème: avec le type personNameSchema, les / et ponctuation ne sont pas acceptés.
Vu avec Gaël: on veut garder l'état des données actuelle en DB. Donc pour agencyCounsellor et agencyValidator, on ne met qu'un typage string.
=> FIX - Noms et Prénoms des conseillers/valideurs moins restrictifs 

back/scalingo/cron.json
Actuellement, les mails partent entre 8h30 et 9h.
Puisque nous avons des problèmes de requêtes SQL sur la table convention en timeout, on avance l'heure d'envois des mails à un moment où la table serait moins sollicitée.
=> #3435 - Envois des mails de liens de complétion de bilan 1h plus tôt

front/src/app/components/admin/conventions/ConventionValidation.tsx
Sur la page de pilotage d'une convention, lorsque je déclenche une demande de signature par SMS trop tôt (moins de 24h avant le précédent), j'ai bien un appel api en erreur HTTP 429 mais j'ai un autre écran qui s'affiche au lieu du feedback d'erreur:
=> #3523 - Fix affichage du message d'erreur lorsque l'on déclenche un envoi de sms < 24h

back/package.json, back/src/config/bootstrap/createGateways.ts, back/src/config/bootstrap/createUseCases.ts, back/src/domains/agency/adapters/InMemoryAgencyRepository.ts, back/src/domains/agency/adapters/PgAgencyRepository.integration.test.ts, back/src/domains/agency/adapters/PgAgencyRepository.ts, back/src/domains/agency/ports/AgencyRepository.ts, back/src/domains/agency/use-cases/AddAgenciesAndUsers.ts, back/src/domains/agency/use-cases/AddAgenciesAndUsers.unit.test.ts, back/src/domains/agency/use-cases/ListAgenciesByFilter.ts, back/src/domains/connected-users/helpers/connectedUser.helper.ts, back/src/domains/connected-users/use-cases/CreateUserForAgency.ts, back/src/scripts/triggerAddAgenciesAndUsers.ts, shared/src/errors/errors.ts
Insertions des agences à partir d'un fichier CSV:
- pour les agences dont le siret est présent sur IF: créer ou mettre à jour les utilisateurs avec les rôles "agency-admin" et "validator"
- pour les agences avec un duplica dans ce même fichier (même siret + nom structure + e-mail authentification + adresse ligne 1 + code postal + ville + téléphone): créer 1 seule agence chez IF + créer/mettre à jour un utilisateur
- pour les agences restantes:
- dont le siret est déjà dans ce fichier, suffixer le nom avec le type de stucture
- sinon créer 1 seule agence chez IF + créer/mettre à jour un utilisateur
=> #3049 - Script d'insertion des agences et utilisateurs depuis un fichiers CSV

back/src/domains/core/authentication/ft-connect/dto/FtConnect.dto.ts, back/src/domains/core/authentication/ft-connect/use-cases/LinkFranceTravailAdvisorAndRedirectToConvention.ts, back/src/domains/core/authentication/ft-connect/use-cases/LinkFranceTravailAdvisorAndRedirectToConvention.unit.test.ts, back/src/utils/emailHash.ts, front/src/app/components/forms/convention/ConventionForm.tsx, front/src/app/pages/convention/ConventionDocumentPage.tsx, shared/src/federatedIdentities/federatedIdentity.dto.ts, shared/src/federatedIdentities/federatedIdentity.schema.ts
- **remove condition to open slot when FT connected**
- **make advisor optional when Ft connected**
=> conserver systematiquement l'identifiant FT connect (isJobSeeker n'est pas important), et le transmettre à FT lors de la diffusion

back/src/domains/establishment/use-cases/AssessmentReminder.ts, back/src/domains/establishment/use-cases/AssessmentReminder.unit.test.ts, back/src/domains/establishment/use-cases/SendAssessmentNeededNotifications.ts, back/src/domains/establishment/use-cases/SendAssessmentNeededNotifications.unit.test.ts, back/src/scripts/triggerAssessmentReminder.ts, front/src/app/pages/admin/EmailPreviewTab.tsx, shared/src/email/EmailParamsByEmailType.ts, shared/src/email/emailTemplatesByName.ts
Les conseillers et valideurs reçoivent trop de mails.
Cette PR :
- supprime l'envoi au conseiller/valideur lors de l'envoi du mail initial au tuteur
- envoie le mail au conseiller/valideurs en même temps que le reminder au tuteur à J+3 et J+10
=> #3717 - Ne plus envoyer la première notification de bilan à l’agence mais la notifier si le tuteur n’a pas encore compléter le bilan à J+3 et J+10
